### ISSUE TITLE
test-pose.h5 no such file

### ISSUE THREAD

**Issue by EvanZhonghuaWu** [MVIG-SJTU/AlphaPose#10]
I found that I haven't downloaded such h5 file when I run run.sh. Where can I download this file?

**Comment by YuliangXiu** [comment]
You can download it via wget/curl command in terminal or some other downloaders, such as Thunder or some built-in downloaders of your browser. You will find the download link in readme.

**Comment by YuliangXiu** [comment]
Maybe you encounter the same problem as #7 , make sure you installed torch correctly. If not work, please paste the command and error logs so we can know the problem

**Comment by crh19970307** [comment]
Hi, please paste the full output message so I can know the problem

**Comment by crh19970307** [comment]
Hi, please paste the full output message so we can know the problem

**Comment by duangenquan** [comment]
Please install torch properly.
These are some tips I use for a clean installation in ubuntu16.04+cudnn6:

`git clone https://github.com/torch/distro.git ~/torch --recursive
git clone https://github.com/torch/distro.git ~/torch --recursive
cd ~/torch; bash install-deps;

sudo apt-get install liblua5.2-dev
git clone https://github.com/luarocks/luarocks.git
./configure
make build
make install
sudo apt-get install libhdf5-serial-dev
luarocks install hdf5
luarocks install torch
luarocks install cutorch
luarocks install cunn
luarocks install cudnn
git clone https://github.com/soumith/cudnn.torch -b R6
cd cudnn.torch
luarocks make
`

**Comment by EvanZhonghuaWu** [comment]
Hi all, thanks. I haven't installed torch correctly. I have fixed the problem.

Thanks

**Comment by baiyoulong** [comment]
I have the same problems.
Thanks

**Comment by ujsyehao** [comment]
you can follow the official documents to install torch
http://torch.ch/docs/getting-started.html

**Comment by block98k** [comment]
hello, i have some question. 
1)before i run ./configure step, I think I need cd luarocks which clone last step, right?
2) I did like 1, but failed with "Lua interpreter not found in $PATH. You may want to use the flags --with-lua, --with-lua-bin and/or --lua-suffix. See --help. configure failed.", I don't know how to do

**Comment by block98k** [comment]
hello, I have some questions.
1)before i run ./configure step, I think I need cd luarocks which clone last step, right?
2) I did like 1, but failed with "Lua interpreter not found in $PATH. You may want to use the flags --with-lua, --with-lua-bin and/or --lua-suffix. See --help. configure failed.", I don't know how to do

**Comment by block98k** [comment]
hello, I have some questions.
1)Before I run ./configure step, I think I need cd luarocks which cloned last step, right?
2)I did like 1, but failed with "Lua interpreter not found in $PATH. You may want to use the flags --with-lua, --with-lua-bin and/or --lua-suffix. See --help. configure failed.", I don't know how to do

**Comment by block98k** [comment]
I did this again, it seems work, but when i run "make install", there are some other bugs like:
---------------------------------------------------------------------------------------------------------
mkdir -p "/usr/local/bin"
cd src/bin && \
luaver="5.1" && [ -n "$luaver" ] || luaver=` -e 'print(_VERSION:sub(5))'`; \
for f in luarocks luarocks-admin; \
do \
   cp "$f" "/usr/local/bin/$f-$luaver"; \
   chmod +rx "/usr/local/bin/$f-$luaver"; \
   ln -nfs "$f-$luaver" "/usr/local/bin/$f"; \
done
cp: cannot create regular file '/usr/local/bin/luarocks-5.1': Permission denied
chmod: cannot access '/usr/local/bin/luarocks-5.1': No such file or directory
ln: failed to create symbolic link '/usr/local/bin/luarocks': Permission denied
cp: cannot create regular file '/usr/local/bin/luarocks-admin-5.1': Permission denied
chmod: cannot access '/usr/local/bin/luarocks-admin-5.1': No such file or directory
ln: failed to create symbolic link '/usr/local/bin/luarocks-admin': Permission denied
Makefile.install.inc:5: recipe for target 'install_bins' failed
make: *** [install_bins] Error 1
---------------------------------------------------------------------------------------------------------
please give me some help, thanks

**Comment by block98k** [comment]
I did this again, it seems work, but when i run "make install", there are some other bugs like:
-------------------------------------------------------------------------
mkdir -p "/usr/local/bin"
cd src/bin &&
luaver="5.1" && [ -n "$luaver" ] || luaver=-e 'print(_VERSION:sub(5))';
for f in luarocks luarocks-admin;
do
cp "$f" "/usr/local/bin/$f-$luaver";
chmod +rx "/usr/local/bin/$f-$luaver";
ln -nfs "$f-$luaver" "/usr/local/bin/$f";
done
cp: cannot create regular file '/usr/local/bin/luarocks-5.1': Permission denied
chmod: cannot access '/usr/local/bin/luarocks-5.1': No such file or directory
ln: failed to create symbolic link '/usr/local/bin/luarocks': Permission denied
cp: cannot create regular file '/usr/local/bin/luarocks-admin-5.1': Permission denied
chmod: cannot access '/usr/local/bin/luarocks-admin-5.1': No such file or directory
ln: failed to create symbolic link '/usr/local/bin/luarocks-admin': Permission denied
Makefile.install.inc:5: recipe for target 'install_bins' failed
make: *** [install_bins] Error 1
---------------------------------------------------------------------------------
please give me some help, thanks

**Comment by block98k** [comment]
sudo luarocks install hdf5
Installing https://luarocks.org/hdf5-2.0.0-1.src.rock
Warning: variable CFLAGS was not passed in build_variables
make[1]: Entering directory '/tmp/luarocks_hdf5-2.0.0-1-TKGaVu/lua-hdf5/gcc-lua'
make[2]: Entering directory '/tmp/luarocks_hdf5-2.0.0-1-TKGaVu/lua-hdf5/gcc-lua/gcc'
gcclua-config.h:1:24: fatal error: gcc-plugin.h: No such file or directory
compilation terminated.
gcc -c -o gcclua.o -I/usr/lib/gcc/x86_64-linux-gnu/5/plugin/include -fPIC  -O2 -Wall -Wformat-security -I/usr/include/lua5.2 gcclua.c
gcclua.c:7:24: fatal error: gcc-plugin.h: No such file or directory
compilation terminated.
Makefile:29: recipe for target 'gcclua.o' failed
make[2]: *** [gcclua.o] Error 1
make[2]: Leaving directory '/tmp/luarocks_hdf5-2.0.0-1-TKGaVu/lua-hdf5/gcc-lua/gcc'
Makefile:38: recipe for target 'gcc' failed
make[1]: *** [gcc] Error 2
make[1]: Leaving directory '/tmp/luarocks_hdf5-2.0.0-1-TKGaVu/lua-hdf5/gcc-lua'
Makefile:44: recipe for target 'gcc-lua' failed
make: *** [gcc-lua] Error 2

Error: Build error: Failed building.
--------------------------------------------------------
please help me, thanks

**Comment by WeiSong123** [comment]
What if there are no sudo commands in docker?

**Comment by AnnLoya** [comment]
have you solved the fatal error: gcc-plugin.h: No such file or directory? I have the same problem with you...and I did install the gcc-4.8-plugin-dev.

**Comment by AnnLoya** [comment]
finally i solved the problem by removing torch and installing it again with lua5.2 instead of luaJIT, and the rest hints are the same as above. refer to http://torch.ch/docs/getting-started.html. thank you

**Comment by WeiSong123** [comment]
hi!  my problem is:
 `zhanghua@zhanghua-System-Product-Name:~/AlphaPose$ ./run.sh --indir examples/demo/ --outdir examples/results/ --vis
0
generating bbox from Faster RCNN...
2018-04-16 15:48:19.729543: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2018-04-16 15:48:20.037014: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.6575
pciBusID: 0000:65:00.0
totalMemory: 10.90GiB freeMemory: 10.44GiB
2018-04-16 15:48:20.037044: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-04-16 15:48:20.229660: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-04-16 15:48:20.229700: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2018-04-16 15:48:20.229705: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2018-04-16 15:48:20.229898: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10102 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:65:00.0, compute capability: 6.1)
Loaded network ../output/res152/coco_2014_train+coco_2014_valminusminival/default/res152.ckpt
/home/zhanghua/AlphaPose/examples/demo/

100%|█████████████████████████████████████████████| 3/3 [00:03<00:00,  1.12s/it]
pose estimation with RMPE...
Found Environment variable CUDNN_PATH = /usr/local/cuda/lib64/libcudnn.so.9.0:/usr/local/cuda-9.0/bin:/home/zhanghua/torch/install/bin:/home/zhanghua/bin:/home/zhanghua/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin	
/home/zhanghua/torch/install/bin/luajit: /home/zhanghua/torch/install/share/lua/5.1/trepl/init.lua:389: /home/zhanghua/torch/install/share/lua/5.1/trepl/init.lua:389: /home/zhanghua/torch/install/share/lua/5.1/cudnn/ffi.lua:1618: /usr/local/cuda/lib64/libcudnn.so.9.0:/usr/local/cuda-9.0/bin:/home/zhanghua/torch/install/bin:/home/zhanghua/bin:/home/zhanghua/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin: cannot open shared object file: No such file or directory
stack traceback:
	[C]: in function 'error'
	/home/zhanghua/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	/home/zhanghua/AlphaPose/predict/util.lua:12: in main chunk
	[C]: in function 'dofile'
	main-alpha-pose.lua:7: in main chunk
	[C]: in function 'dofile'
	...ghua/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
Traceback (most recent call last):
  File "parametric-pose-nms-MPII.py", line 256, in <module>
    get_result_json(args)
  File "parametric-pose-nms-MPII.py", line 243, in get_result_json
    test_parametric_pose_NMS_json(delta1, delta2, mu, gamma,args.outputpath)
  File "parametric-pose-nms-MPII.py", line 99, in test_parametric_pose_NMS_json
    h5file = h5py.File(os.path.join(outputpath,"POSE/test-pose.h5"), 'r')
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/files.py", line 272, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/files.py", line 92, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/build/h5py-nQFNYZ/h5py-2.6.0/h5py/_objects.c:2577)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/build/h5py-nQFNYZ/h5py-2.6.0/h5py/_objects.c:2536)
  File "h5py/h5f.pyx", line 76, in h5py.h5f.open (/build/h5py-nQFNYZ/h5py-2.6.0/h5py/h5f.c:1811)
IOError: Unable to open file (Unable to open file: name = '/home/zhanghua/alphapose/examples/results/pose/test-pose.h5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)
visualization...
Traceback (most recent call last):
  File "json-video.py", line 63, in <module>
    with open(jsonpath) as f:
IOError: [Errno 2] No such file or directory: '/home/zhanghua/AlphaPose/examples/results/POSE/alpha-pose-results-forvis.json'
`

**Comment by WeiSong123** [comment]
hi! my problem is:
`zhanghua@zhanghua-System-Product-Name:~/AlphaPose$ ./run.sh --indir examples/demo/ --outdir examples/results/ --vis
0
generating bbox from Faster RCNN...
2018-04-16 15:48:19.729543: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2018-04-16 15:48:20.037014: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties:
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.6575
pciBusID: 0000:65:00.0
totalMemory: 10.90GiB freeMemory: 10.44GiB
2018-04-16 15:48:20.037044: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-04-16 15:48:20.229660: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-04-16 15:48:20.229700: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929] 0
2018-04-16 15:48:20.229705: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0: N
2018-04-16 15:48:20.229898: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10102 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:65:00.0, compute capability: 6.1)
Loaded network ../output/res152/coco_2014_train+coco_2014_valminusminival/default/res152.ckpt
/home/zhanghua/AlphaPose/examples/demo/

100%|█████████████████████████████████████████████| 3/3 [00:03<00:00, 1.12s/it]
pose estimation with RMPE...
Found Environment variable CUDNN_PATH = /usr/local/cuda/lib64/libcudnn.so.9.0:/usr/local/cuda-9.0/bin:/home/zhanghua/torch/install/bin:/home/zhanghua/bin:/home/zhanghua/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
/home/zhanghua/torch/install/bin/luajit: /home/zhanghua/torch/install/share/lua/5.1/trepl/init.lua:389: /home/zhanghua/torch/install/share/lua/5.1/trepl/init.lua:389: /home/zhanghua/torch/install/share/lua/5.1/cudnn/ffi.lua:1618: /usr/local/cuda/lib64/libcudnn.so.9.0:/usr/local/cuda-9.0/bin:/home/zhanghua/torch/install/bin:/home/zhanghua/bin:/home/zhanghua/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin: cannot open shared object file: No such file or directory
stack traceback:
[C]: in function 'error'
/home/zhanghua/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
/home/zhanghua/AlphaPose/predict/util.lua:12: in main chunk
[C]: in function 'dofile'
main-alpha-pose.lua:7: in main chunk
[C]: in function 'dofile'
...ghua/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
[C]: at 0x00405d50
Traceback (most recent call last):
File "parametric-pose-nms-MPII.py", line 256, in 
get_result_json(args)
File "parametric-pose-nms-MPII.py", line 243, in get_result_json
test_parametric_pose_NMS_json(delta1, delta2, mu, gamma,args.outputpath)
File "parametric-pose-nms-MPII.py", line 99, in test_parametric_pose_NMS_json
h5file = h5py.File(os.path.join(outputpath,"POSE/test-pose.h5"), 'r')
File "/usr/lib/python2.7/dist-packages/h5py/_hl/files.py", line 272, in init
fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
File "/usr/lib/python2.7/dist-packages/h5py/_hl/files.py", line 92, in make_fid
fid = h5f.open(name, flags, fapl=fapl)
File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/build/h5py-nQFNYZ/h5py-2.6.0/h5py/_objects.c:2577)
File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/build/h5py-nQFNYZ/h5py-2.6.0/h5py/_objects.c:2536)
File "h5py/h5f.pyx", line 76, in h5py.h5f.open (/build/h5py-nQFNYZ/h5py-2.6.0/h5py/h5f.c:1811)
IOError: Unable to open file (Unable to open file: name = '/home/zhanghua/alphapose/examples/results/pose/test-pose.h5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)
visualization...
Traceback (most recent call last):
File "json-video.py", line 63, in 
with open(jsonpath) as f:
IOError: [Errno 2] No such file or directory: '/home/zhanghua/AlphaPose/examples/results/POSE/alpha-pose-results-forvis.json'
`
This is my problem,help me!  thanks！！！！
The environment is cuda9.0 + cudnn7.1+torch7+tensorflow1.8+lua5.2

**Comment by jerryajay** [comment]
Also this may be required:
luarocks install luabitop

**Comment by hellboywyh** [comment]
> hi! my problem is:
> `zhanghua@zhanghua-System-Product-Name:~/AlphaPose$ ./run.sh --indir examples/demo/ --outdir examples/results/ --vis
> 0
> generating bbox from Faster RCNN...
> 2018-04-16 15:48:19.729543: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
> 2018-04-16 15:48:20.037014: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties:
> name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.6575
> pciBusID: 0000:65:00.0
> totalMemory: 10.90GiB freeMemory: 10.44GiB
> 2018-04-16 15:48:20.037044: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
> 2018-04-16 15:48:20.229660: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2018-04-16 15:48:20.229700: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929] 0
> 2018-04-16 15:48:20.229705: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0: N
> 2018-04-16 15:48:20.229898: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10102 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:65:00.0, compute capability: 6.1)
> Loaded network ../output/res152/coco_2014_train+coco_2014_valminusminival/default/res152.ckpt
> /home/zhanghua/AlphaPose/examples/demo/
> 
> 100%|█████████████████████████████████████████████| 3/3 [00:03<00:00, 1.12s/it]
> pose estimation with RMPE...
> Found Environment variable CUDNN_PATH = /usr/local/cuda/lib64/libcudnn.so.9.0:/usr/local/cuda-9.0/bin:/home/zhanghua/torch/install/bin:/home/zhanghua/bin:/home/zhanghua/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
> /home/zhanghua/torch/install/bin/luajit: /home/zhanghua/torch/install/share/lua/5.1/trepl/init.lua:389: /home/zhanghua/torch/install/share/lua/5.1/trepl/init.lua:389: /home/zhanghua/torch/install/share/lua/5.1/cudnn/ffi.lua:1618: /usr/local/cuda/lib64/libcudnn.so.9.0:/usr/local/cuda-9.0/bin:/home/zhanghua/torch/install/bin:/home/zhanghua/bin:/home/zhanghua/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin: cannot open shared object file: No such file or directory
> stack traceback:
> [C]: in function 'error'
> /home/zhanghua/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
> /home/zhanghua/AlphaPose/predict/util.lua:12: in main chunk
> [C]: in function 'dofile'
> main-alpha-pose.lua:7: in main chunk
> [C]: in function 'dofile'
> ...ghua/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
> [C]: at 0x00405d50
> Traceback (most recent call last):
> File "parametric-pose-nms-MPII.py", line 256, in
> get_result_json(args)
> File "parametric-pose-nms-MPII.py", line 243, in get_result_json
> test_parametric_pose_NMS_json(delta1, delta2, mu, gamma,args.outputpath)
> File "parametric-pose-nms-MPII.py", line 99, in test_parametric_pose_NMS_json
> h5file = h5py.File(os.path.join(outputpath,"POSE/test-pose.h5"), 'r')
> File "/usr/lib/python2.7/dist-packages/h5py/_hl/files.py", line 272, in init
> fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
> File "/usr/lib/python2.7/dist-packages/h5py/_hl/files.py", line 92, in make_fid
> fid = h5f.open(name, flags, fapl=fapl)
> File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/build/h5py-nQFNYZ/h5py-2.6.0/h5py/_objects.c:2577)
> File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/build/h5py-nQFNYZ/h5py-2.6.0/h5py/_objects.c:2536)
> File "h5py/h5f.pyx", line 76, in h5py.h5f.open (/build/h5py-nQFNYZ/h5py-2.6.0/h5py/h5f.c:1811)
> IOError: Unable to open file (Unable to open file: name = '/home/zhanghua/alphapose/examples/results/pose/test-pose.h5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)
> visualization...
> Traceback (most recent call last):
> File "json-video.py", line 63, in
> with open(jsonpath) as f:
> IOError: [Errno 2] No such file or directory: '/home/zhanghua/AlphaPose/examples/results/POSE/alpha-pose-results-forvis.json'
> `
> This is my problem,help me! thanks！！！！
> The environment is cuda9.0 + cudnn7.1+torch7+tensorflow1.8+lua5.2

I have the similar question to you. Have you solved it?
