### ISSUE TITLE
No module named 'utils.utils'

### ISSUE THREAD

**Issue by zhanghui-china** [MVIG-SJTU/AlphaPose#1001]
(py36) user@MYHOST:~/AlphaPose$ python scripts/demo_inference.py --cfg 256x192_res50_lr1e-3_1x-simple.yaml --checkpoint simple_res50_256x192.pth --indir examples/demo/
Traceback (most recent call last):
  File "scripts/demo_inference.py", line 14, in <module>
    from trackers.tracker_api import Tracker
  File "/home/ascend/AlphaPose/trackers/tracker_api.py", line 21, in <module>
    from utils.utils import *
ModuleNotFoundError: No module named 'utils.utils'

How can i solve the problem ?

**Comment by akucsd** [comment]
Hey have you found any solution to this error? Please let me know

**Comment by akucsd** [comment]
@zhanghui-china just put trackers.utils.utils everywhere, it will solve the err

**Comment by p445ccm4** [comment]
Have you installed the package? I just faced the same issue and solved.

For me, I looked into the installation path (~/.local/lib/python3.8/site-packages/trackers) and I only found "ReidModels' and "tracking" folders but no "utils" folder. 

So I copy the "utils" folder from the repository into there and solved the problem.

Hope it helps!

**Comment by jzt-dongli** [comment]
Add __init__.py to the utils folder
