### ISSUE TITLE
Error running `python setup.py build develop` in Linux (Arch)

### ISSUE THREAD

**Issue by BeeMargarida** [MVIG-SJTU/AlphaPose#1002]
Hi!

First of all I would like to thank you for this library, was looking for a project that provided this type of functionaly with having to deal with atlas and this is a godsend.

I was trying to run the demo and could not move past `python setup.py build develop`. I followed all steps in https://github.com/MVIG-SJTU/AlphaPose/blob/master/docs/INSTALL.md#recommended-install-with-conda (except the ones specific for Ubuntu) and the error happened.

Could you possible tell me what am I missing?

```
Installed /home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/munkres-1.1.4-py3.7.egg
Searching for halpecocotools
Reading https://pypi.tuna.tsinghua.edu.cn/simple/halpecocotools/
Downloading https://pypi.tuna.tsinghua.edu.cn/packages/f9/b0/f2e783a29a30cf0e66e3bbc45cdc4da6e9214bc21f4df948ee9a7d79764e/halpecocotools-0.0.0.tar.gz#sha256=8355964f7d14e69b2a555be7e116eae8979ec2a04f0eef16d140b38d04f933eb
Best match: halpecocotools 0.0.0
Processing halpecocotools-0.0.0.tar.gz
Writing /tmp/easy_install-80f613th/halpecocotools-0.0.0/setup.cfg
Running halpecocotools-0.0.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-80f613th/halpecocotools-0.0.0/egg-dist-tmp-cv6bb8aw
warning: no files found matching '*.pxd'
warning: no files found matching '*.pyx'
/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/easy_install-80f613th/halpecocotools-0.0.0/halpecocotools/_mask.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
Traceback (most recent call last):
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 2218, in visit_FuncDefNode
    node.body = node.body.analyse_expressions(node.local_scope)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 436, in analyse_expressions
    for stat in self.stats]
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 436, in <listcomp>
    for stat in self.stats]
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 6265, in analyse_expressions
    self.if_clauses = [if_clause.analyse_expressions(env) for if_clause in self.if_clauses]
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 6265, in <listcomp>
    self.if_clauses = [if_clause.analyse_expressions(env) for if_clause in self.if_clauses]
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 6331, in analyse_expressions
    self.body = self.body.analyse_expressions(env)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 436, in analyse_expressions
    for stat in self.stats]
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 436, in <listcomp>
    for stat in self.stats]
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 6702, in analyse_expressions
    self.item = self.item.coerce_to(self.target.type, env)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/ExprNodes.py", line 952, in coerce_to
    src = PyTypeTestNode(src, dst_type, env)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/ExprNodes.py", line 13015, in __init__
    assert dst_type.is_extension_type or dst_type.is_builtin_type, "PyTypeTest on non extension type"
AssertionError: PyTypeTest on non extension type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/setuptools/sandbox.py", line 156, in save_modules
    yield saved
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/setuptools/sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-80f613th/halpecocotools-0.0.0/setup.py", line 28, in <module>
    def _minimal_ext_cmd(cmd):
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 193, in build_extensions
    ext.sources = self.cython_sources(ext.sources, ext)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 347, in cython_sources
    full_module_name=module_name)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/Main.py", line 778, in compile
    return compile_single(source, options, full_module_name)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/Main.py", line 727, in compile_single
    return run_pipeline(source, options, full_module_name)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/Main.py", line 515, in run_pipeline
    err, enddata = Pipeline.run_pipeline(pipeline, source)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/Pipeline.py", line 355, in run_pipeline
    data = run(phase, data)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/Pipeline.py", line 335, in run
    return phase(data)
  File "Cython/Compiler/Visitor.py", line 302, in Cython.Compiler.Visitor.CythonTransform.__call__
  File "Cython/Compiler/Visitor.py", line 284, in Cython.Compiler.Visitor.VisitorTransform.__call__
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 2213, in visit_ModuleNode
    self.visitchildren(node)
  File "Cython/Compiler/Visitor.py", line 247, in Cython.Compiler.Visitor.VisitorTransform.visitchildren
  File "Cython/Compiler/Visitor.py", line 251, in Cython.Compiler.Visitor.VisitorTransform.visitchildren
  File "Cython/Compiler/Visitor.py", line 260, in Cython.Compiler.Visitor.VisitorTransform._process_children
  File "Cython/Compiler/Visitor.py", line 221, in Cython.Compiler.Visitor.TreeVisitor._visitchildren
  File "Cython/Compiler/Visitor.py", line 193, in Cython.Compiler.Visitor.TreeVisitor._visitchild
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 312, in Cython.Compiler.Visitor.CythonTransform.visit_Node
  File "Cython/Compiler/Visitor.py", line 260, in Cython.Compiler.Visitor.VisitorTransform._process_children
  File "Cython/Compiler/Visitor.py", line 219, in Cython.Compiler.Visitor.TreeVisitor._visitchildren
  File "Cython/Compiler/Visitor.py", line 193, in Cython.Compiler.Visitor.TreeVisitor._visitchild
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 312, in Cython.Compiler.Visitor.CythonTransform.visit_Node
  File "Cython/Compiler/Visitor.py", line 260, in Cython.Compiler.Visitor.VisitorTransform._process_children
  File "Cython/Compiler/Visitor.py", line 219, in Cython.Compiler.Visitor.TreeVisitor._visitchildren
  File "Cython/Compiler/Visitor.py", line 193, in Cython.Compiler.Visitor.TreeVisitor._visitchild
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 312, in Cython.Compiler.Visitor.CythonTransform.visit_Node
  File "Cython/Compiler/Visitor.py", line 260, in Cython.Compiler.Visitor.VisitorTransform._process_children
  File "Cython/Compiler/Visitor.py", line 221, in Cython.Compiler.Visitor.TreeVisitor._visitchildren
  File "Cython/Compiler/Visitor.py", line 193, in Cython.Compiler.Visitor.TreeVisitor._visitchild
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 312, in Cython.Compiler.Visitor.CythonTransform.visit_Node
  File "Cython/Compiler/Visitor.py", line 260, in Cython.Compiler.Visitor.VisitorTransform._process_children
  File "Cython/Compiler/Visitor.py", line 219, in Cython.Compiler.Visitor.TreeVisitor._visitchildren
  File "Cython/Compiler/Visitor.py", line 193, in Cython.Compiler.Visitor.TreeVisitor._visitchild
  File "Cython/Compiler/Visitor.py", line 188, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 148, in Cython.Compiler.Visitor.TreeVisitor._raise_compiler_error
Cython.Compiler.Errors.CompilerCrash: 
Error compiling Cython file:
------------------------------------------------------------
...
    def __cinit__(self, siz n =0):
        rlesInit(&self._R, n)
        self._n = n

    # free the RLE array here
    def __dealloc__(self):
   ^
------------------------------------------------------------

halpecocotools/_mask.pyx:65:4: Compiler crash in AnalyseExpressionsTransform

ModuleNode.body = StatListNode(_mask.pyx:11:0)
StatListNode.stats[9] = StatListNode(_mask.pyx:56:5)
StatListNode.stats[0] = CClassDefNode(_mask.pyx:56:5,
    as_name = 'RLEs',
    class_name = 'RLEs',
    module_name = '',
    visibility = 'private')
CClassDefNode.body = StatListNode(_mask.pyx:57:4)
StatListNode.stats[1] = DefNode(_mask.pyx:65:4,
    modifiers = [...]/0,
    name = '__dealloc__',
    np_args_idx = [...]/0,
    num_required_args = 1,
    outer_attrs = [...]/2,
    py_wrapper_required = True,
    reqd_kw_flags_cname = '0',
    used = True)

Compiler crash traceback from this point on:
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 2218, in visit_FuncDefNode
    node.body = node.body.analyse_expressions(node.local_scope)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 436, in analyse_expressions
    for stat in self.stats]
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 436, in <listcomp>
    for stat in self.stats]
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 6265, in analyse_expressions
    self.if_clauses = [if_clause.analyse_expressions(env) for if_clause in self.if_clauses]
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 6265, in <listcomp>
    self.if_clauses = [if_clause.analyse_expressions(env) for if_clause in self.if_clauses]
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 6331, in analyse_expressions
    self.body = self.body.analyse_expressions(env)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 436, in analyse_expressions
    for stat in self.stats]
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 436, in <listcomp>
    for stat in self.stats]
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 6702, in analyse_expressions
    self.item = self.item.coerce_to(self.target.type, env)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/ExprNodes.py", line 952, in coerce_to
    src = PyTypeTestNode(src, dst_type, env)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/ExprNodes.py", line 13015, in __init__
    assert dst_type.is_extension_type or dst_type.is_builtin_type, "PyTypeTest on non extension type"
AssertionError: PyTypeTest on non extension type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 213, in <module>
    zip_safe=False)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/setuptools/command/develop.py", line 129, in install_for_development
    self.process_distribution(None, self.dist, not self.no_deps)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 745, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/pkg_resources/__init__.py", line 768, in resolve
    replace_conflicting=replace_conflicting
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1051, in best_match
    return self.obtain(req, installer)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1063, in obtain
    return installer(requirement)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 669, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 695, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1162, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1146, in run_setup
    run_setup(setup_script, args)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/setuptools/sandbox.py", line 262, in run_setup
    raise
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/setuptools/sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/setuptools/sandbox.py", line 143, in resume
    raise exc.with_traceback(self._tb)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/setuptools/sandbox.py", line 156, in save_modules
    yield saved
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/setuptools/sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-80f613th/halpecocotools-0.0.0/setup.py", line 28, in <module>
    def _minimal_ext_cmd(cmd):
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 193, in build_extensions
    ext.sources = self.cython_sources(ext.sources, ext)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 347, in cython_sources
    full_module_name=module_name)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/Main.py", line 778, in compile
    return compile_single(source, options, full_module_name)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/Main.py", line 727, in compile_single
    return run_pipeline(source, options, full_module_name)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/Main.py", line 515, in run_pipeline
    err, enddata = Pipeline.run_pipeline(pipeline, source)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/Pipeline.py", line 355, in run_pipeline
    data = run(phase, data)
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/Pipeline.py", line 335, in run
    return phase(data)
  File "Cython/Compiler/Visitor.py", line 302, in Cython.Compiler.Visitor.CythonTransform.__call__
  File "Cython/Compiler/Visitor.py", line 284, in Cython.Compiler.Visitor.VisitorTransform.__call__
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 2213, in visit_ModuleNode
    self.visitchildren(node)
  File "Cython/Compiler/Visitor.py", line 247, in Cython.Compiler.Visitor.VisitorTransform.visitchildren
  File "Cython/Compiler/Visitor.py", line 251, in Cython.Compiler.Visitor.VisitorTransform.visitchildren
  File "Cython/Compiler/Visitor.py", line 260, in Cython.Compiler.Visitor.VisitorTransform._process_children
  File "Cython/Compiler/Visitor.py", line 221, in Cython.Compiler.Visitor.TreeVisitor._visitchildren
  File "Cython/Compiler/Visitor.py", line 193, in Cython.Compiler.Visitor.TreeVisitor._visitchild
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 312, in Cython.Compiler.Visitor.CythonTransform.visit_Node
  File "Cython/Compiler/Visitor.py", line 260, in Cython.Compiler.Visitor.VisitorTransform._process_children
  File "Cython/Compiler/Visitor.py", line 219, in Cython.Compiler.Visitor.TreeVisitor._visitchildren
  File "Cython/Compiler/Visitor.py", line 193, in Cython.Compiler.Visitor.TreeVisitor._visitchild
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 312, in Cython.Compiler.Visitor.CythonTransform.visit_Node
  File "Cython/Compiler/Visitor.py", line 260, in Cython.Compiler.Visitor.VisitorTransform._process_children
  File "Cython/Compiler/Visitor.py", line 219, in Cython.Compiler.Visitor.TreeVisitor._visitchildren
  File "Cython/Compiler/Visitor.py", line 193, in Cython.Compiler.Visitor.TreeVisitor._visitchild
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 312, in Cython.Compiler.Visitor.CythonTransform.visit_Node
  File "Cython/Compiler/Visitor.py", line 260, in Cython.Compiler.Visitor.VisitorTransform._process_children
  File "Cython/Compiler/Visitor.py", line 221, in Cython.Compiler.Visitor.TreeVisitor._visitchildren
  File "Cython/Compiler/Visitor.py", line 193, in Cython.Compiler.Visitor.TreeVisitor._visitchild
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 312, in Cython.Compiler.Visitor.CythonTransform.visit_Node
  File "Cython/Compiler/Visitor.py", line 260, in Cython.Compiler.Visitor.VisitorTransform._process_children
  File "Cython/Compiler/Visitor.py", line 219, in Cython.Compiler.Visitor.TreeVisitor._visitchildren
  File "Cython/Compiler/Visitor.py", line 193, in Cython.Compiler.Visitor.TreeVisitor._visitchild
  File "Cython/Compiler/Visitor.py", line 188, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 148, in Cython.Compiler.Visitor.TreeVisitor._raise_compiler_error
setuptools.sandbox.UnpickleableException: CompilerCrash((<FileSourceDescriptor:/tmp/easy_install-80f613th/halpecocotools-0.0.0/halpecocotools/_mask.pyx>, 65, 4), 'AnalyseExpressionsTransform', 'Compiler crash in AnalyseExpressionsTransform\n\nModuleNode.body = StatListNode(_mask.pyx:11:0)\nStatListNode.stats[9] = StatListNode(_mask.pyx:56:5)\nStatListNode.stats[0] = CClassDefNode(_mask.pyx:56:5,\n    as_name = \'RLEs\',\n    class_name = \'RLEs\',\n    module_name = \'\',\n    visibility = \'private\')\nCClassDefNode.body = StatListNode(_mask.pyx:57:4)\nStatListNode.stats[1] = DefNode(_mask.pyx:65:4,\n    modifiers = [...]/0,\n    name = \'__dealloc__\',\n    np_args_idx = [...]/0,\n    num_required_args = 1,\n    outer_attrs = [...]/2,\n    py_wrapper_required = True,\n    reqd_kw_flags_cname = \'0\',\n    used = True)\n\nCompiler crash traceback from this point on:\n  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit\n  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 2218, in visit_FuncDefNode\n    node.body = node.body.analyse_expressions(node.local_scope)\n  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 436, in analyse_expressions\n    for stat in self.stats]\n  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 436, in <listcomp>\n    for stat in self.stats]\n  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 6265, in analyse_expressions\n    self.if_clauses = [if_clause.analyse_expressions(env) for if_clause in self.if_clauses]\n  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 6265, in <listcomp>\n    self.if_clauses = [if_clause.analyse_expressions(env) for if_clause in self.if_clauses]\n  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 6331, in analyse_expressions\n    self.body = self.body.analyse_expressions(env)\n  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 436, in analyse_expressions\n    for stat in self.stats]\n  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 436, in <listcomp>\n    for stat in self.stats]\n  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/Nodes.py", line 6702, in analyse_expressions\n    self.item = self.item.coerce_to(self.target.type, env)\n  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/ExprNodes.py", line 952, in coerce_to\n    src = PyTypeTestNode(src, dst_type, env)\n  File "/home/margarida/.conda/envs/alphapose/lib/python3.7/site-packages/Cython/Compiler/ExprNodes.py", line 13015, in __init__\n    assert dst_type.is_extension_type or dst_type.is_builtin_type, "PyTypeTest on non extension type"\nAssertionError: PyTypeTest on non extension type', AssertionError('PyTypeTest on non extension type'), <traceback object at 0x7f78d0b4b230>)

```

**Comment by sjwang222** [comment]
Hi Margarida,

I encounter the same issue on Ubuntu 20.04 and I fix it by adding '--user' in the end of the command (just like installing with pip), i.e., I run 
`python setup.py build develop --user`.
I dont know the exact reason (it may relate to the virtual environment) but it works. Hope it may help you.

Best

**Comment by Fang-Haoshu** [comment]
Hi @HaoyiZhu , can you help check the halpecocotools?

**Comment by HaoyiZhu** [comment]
Hi, could you try to manually run `pip install halpecocotools` and then install alphapose again?

**Comment by HaoyiZhu** [comment]
Actually, I find a similar issue here: https://github.com/open-mmlab/mmdetection/issues/1863. Hope it can help you.

**Comment by BeeMargarida** [comment]
> Hi Margarida,
> 
> I encounter the same issue on Ubuntu 20.04 and I fix it by adding '--user' in the end of the command (just like installing with pip), i.e., I run `python setup.py build develop --user`. I dont know the exact reason (it may relate to the virtual environment) but it works. Hope it may help you.
> 
> Best

Sorry, was out of here for a minute, will try again with that fix, thank you!

**Comment by optimuspaul** [comment]
I have this same issue, the fix above changed nothing for me.  I have been trying to find a solution for a few days now.

**Comment by optimuspaul** [comment]
ok, got it building, had to build `halpecocotools` from source since pip install fails.

I do this, in docker, but should be adaptable for other environments.
```
mkdir /build
cd /build && git clone https://github.com/HaoyiZhu/HalpeCOCOAPI.git
cd /build/HalpeCOCOAPI/PythonAPI && python3 setup.py build develop --user
```

**Comment by jzt-dongli** [comment]
You are right, thank you very much for the experience.

> Actually, I find a similar issue here: [open-mmlab/mmdetection#1863](https://github.com/open-mmlab/mmdetection/issues/1863). Hope it can help you.

**Comment by valentin-fngr** [comment]
+2 years after this issue has been open, we still cannot `pip install halpecocotools`, crazy

**Comment by luser350** [comment]
@optimuspaul is correct, installing from source solved the issue for me.
```
git clone https://github.com/HaoyiZhu/HalpeCOCOAPI.git
cd HalpeCOCOAPI/PythonAPI/
python setup.py build_ext --inplace
python setup.py install
```
