### ISSUE TITLE
ImportError: cannot import name 'roi_align_cuda'

### ISSUE THREAD

**Issue by akframe** [MVIG-SJTU/AlphaPose#1031]
Traceback (most recent call last):
  File "scripts/demo_inference.py", line 19, in <module>
    from alphapose.utils.detector import DetectionLoader
  File "/home/kane/code/AlphaPose/alphapose/utils/detector.py", line 12, in <module>
    from alphapose.utils.presets import SimpleTransform
  File "/home/kane/code/AlphaPose/alphapose/utils/presets/__init__.py", line 1, in <module>
    from .simple_transform import SimpleTransform
  File "/home/kane/code/AlphaPose/alphapose/utils/presets/simple_transform.py", line 22, in <module>
    from ..roi_align import RoIAlign
  File "/home/kane/code/AlphaPose/alphapose/utils/roi_align/__init__.py", line 1, in <module>
    from .roi_align import roi_align, RoIAlign
  File "/home/kane/code/AlphaPose/alphapose/utils/roi_align/roi_align.py", line 6, in <module>
    from . import roi_align_cuda
ImportError: cannot import name 'roi_align_cuda'

**Comment by dongxiaolong** [comment]
I alse get the same trouble.Have you solved it ?

**Comment by Duderino165** [comment]
Same here, I am using WSL.

**Comment by Fang-Haoshu** [comment]
Hi, did you successfully finish the installation? Seems it is not make during setup

**Comment by hajix** [comment]
@Fang-Haoshu
I'm wondering if it should be built in CPU only environments.
