### ISSUE TITLE
Questions on testing Human-ReID model with demo_inference.py

### ISSUE THREAD

**Issue by sjwang222** [MVIG-SJTU/AlphaPose#1036]
Hi there,

This project is impressive and the documentations herein are awesome!! Thanks for sharing!

I built the environment following your recommendation in  [INSTALL.md](https://github.com/MVIG-SJTU/AlphaPose/blob/master/docs/INSTALL.md) so I have pytorch == 0.1.0 and torchvision == 0.3.0 on my computer. Then I managed to infer several figures with FastResNet and the results look quite well.

Next I switched to pose tracking. I downloaded the .pth file for the ReID from Baidu Pan but I failed to load the model in the inference with the following command:
 `python scripts/demo_inference.py --cfg configs/halpe_26/resnet/256x192_res50_lr1e-3_1x.yaml --checkpoint trackers/weights/osnet_ain_x1_0_msmt17_256x128_amsgrad_ep50_lr0.0015_coslr_b64_fb10_softmax_labsmth_flip_jitter.pth --video raw_video/kj.mp4 --outdir raw_video/res/ --save_video, --pose_track`

The error message is as follows:
`
Loading pose model from trackers/weights/osnet_ain_x1_0_msmt17_256x128_amsgrad_ep50_lr0.0015_coslr_b64_fb10_softmax_labsmth_flip_jitter.pth...
Traceback (most recent call last):
  File "scripts/demo_inference.py", line 191, in <module>
    pose_model.load_state_dict(torch.load(args.checkpoint, map_location=args.device))
  File "C:\Users\1\anaconda3\envs\alphapose\lib\site-packages\torch\nn\modules\module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for FastPose:
        Missing key(s) in state_dict: "preact.conv1.weight", "preact.bn1.weight", "preact.bn1.bias", "preact.bn1.running_mean", "preact.bn1.running_var", "preact.layer1.0.conv1.weight", "preact.layer1.0.bn1.weight", "preact.layer1.0.bn1.bias", "preact.layer1.0.bn1.running_mean", "preact.layer1.0.bn1.running_var", "preact.layer1.0.conv2.weight", "preact.layer1.0.bn2.weight", "preact.layer1.0.bn2.bias", "preact.layer1.0.bn2.running_mean", "preact.layer1.0.bn2.running_var", "preact.layer1.0.conv3.weight", "preact.layer1.0.bn3.weight", "preact.layer1.0.bn3.bias", "preact.layer1.0.bn3.running_mean", "preact.layer1.0.bn3.running_var", "preact.layer1.0.se.fc.0.weight", "preact.layer1.0.se.fc.0.bias", "preact.layer1.0.se.fc.2.weight", "preact.layer1.0.se.fc.2.bias", "preact.layer1.0.downsample.0.weight", "preact.layer1.0.downsample.1.weight", "preact.layer1.0.downsample.1.bias", "preact.layer1.0.downsample.1.running_mean", "preact.layer1.0.downsample.1.running_var", "preact.layer1.1.conv1.weight",
...
`
As suggested by [another issue](https://github.com/MVIG-SJTU/AlphaPose/issues/316), this error may be caused by the difference in pytorch/torchvision versions. Then I try different porch and torchvision versions but it does not work.

I also note that this error could arise from the mismatch between the checkpoint and config as suggested in [this issue](https://github.com/MVIG-SJTU/AlphaPose/issues/504)
So what are the proper command to run this demo? or are there any other reasons that may give rise to this issue?

Thanks!

**Comment by sjwang222** [comment]
The issue is well resolved after I switch to Ubuntu 20.04. I guess there is something tricky with installation under Windows. Anyway, thanks again for sharing this model.
