### ISSUE TITLE
 libgcrypt.so.11: cannot open shared object file

### ISSUE THREAD

**Issue by nyanmn** [MVIG-SJTU/AlphaPose#1066]
I am testing alphapose and run the following command.

`python scripts/demo_inference.py --cfg configs/halpe_26/resnet/256x192_res50_lr1e-3_1x.yaml --checkpoint pretrained_models/halpe26_fast_res50_256x192.pth --indir examples/demo/ --save_img`

The error is 
`ImportError: libgcrypt.so.11: cannot open shared object file: No such file or directory`

The whole error is

```
Traceback (most recent call last):
  File "scripts/demo_inference.py", line 22, in <module>
    from alphapose.utils.vis import getTime
  File "/home/sysadmin/Nyan/AlphaPose/alphapose/utils/vis.py", line 9, in <module>
    from .render import SMPLRenderer
  File "/home/sysadmin/Nyan/AlphaPose/alphapose/utils/render.py", line 14, in <module>
    from opendr.renderer import ColoredRenderer
  File "/home/sysadmin/anaconda3/envs/alphapose/lib/python3.7/site-packages/opendr-0.78-py3.7-linux-x86_64.egg/opendr/renderer.py", line 25, in <module>
    from .contexts.ctx_mesa import OsContext
ImportError: libgcrypt.so.11: cannot open shared object file: No such file or directory

```

**Comment by Fang-Haoshu** [comment]
Thanks. I just update the code. You can pull the latest repo and try again

**Comment by nyanmn** [comment]
Thanks it works now
