### ISSUE TITLE
Installation error Linux 22.04 cuda 11.7

### ISSUE THREAD

**Issue by VisImage** [MVIG-SJTU/AlphaPose#1072]
installation error on a new desktop PC with fresh installed ubuntu 22.04. detailed info is shown in the attached files.
[hardinfo_report.txt](https://github.com/MVIG-SJTU/AlphaPose/files/9367531/hardinfo_report.txt)
[installationMessages.odt](https://github.com/MVIG-SJTU/AlphaPose/files/9367532/installationMessages.odt)

**Comment by temofy** [comment]
Hi! First, install `sudo apt-get install libosmesa6-dev`
Second, clone https://gitlab.freedesktop.org/mesa/glu and execute the followig commands: 
```
mkdir build &&
cd    build &&

meson --prefix=$XORG_PREFIX -Dgl_provider=gl --buildtype=release --prefix '/' .. && ninja

sudo ninja install &&
rm -vf /usr/lib/libGLU.a
```
And then run building with prefix "--user"
`python setup.py build develop --user`

**Comment by julienguegan** [comment]
I have `meson command not found`, do I need to install it with `pip install meson` or `apt install meson` ? Also, Do I need to run your commands inside the glu directory or outside ?

**Comment by temofy** [comment]
> I have `meson command not found`, do I need to install it with `pip install meson` or `apt install meson` ? Also, Do I need to run your commands inside the glu directory or outside ?

Yes, install via `apt instal meson` and run commands inside root of glu directory

**Comment by julienguegan** [comment]
at one point, in the compilation I have `RuntimeError: Python version >= 3.8 required` but I have an environment with python 3.7 as written in file **INSTALL.md**. Guess I have to reinstall it

**Comment by temofy** [comment]
> at one point, in the compilation I have `RuntimeError: Python version >= 3.8 required` but I have an environment with python 3.7 as written in file **INSTALL.md**. Guess I have to reinstall it

I use python 3.7 and it works for me. Did you know where the RuntimeError occurs? Did you try use Python 3.8?

**Comment by VisImage** [comment]
We have tried the solution as indicated in https://github.com/MVIG-SJTU/AlphaPose/issues/1072#issuecomment-1224283552. It progresses, but still cannot be installed successfully. 

Our issue was that Ubuntu 20.04.1 does not support the hardware in our PC, specifically the network card.  while Ubuntu 22.04 can only install a Cuda with a higher version . We have managed to install Ubuntu 20.04.4 on a Dell XPS 8950, with Cuda 11.4. The installation goes a lot of further, but still have the following error, when running "python setup.py build develop"

Using /home/yin/.local/lib/python3.7/site-packages/jsonpointer-2.3-py3.7.egg
Finished processing dependencies for alphapose==0.5.0+308cc9a
Traceback (most recent call last):
  File "setup.py", line 220, in <module>
    if not is_installed('cython_bbox'):
  File "setup.py", line 178, in is_installed
    from pip._internal.utils.misc import get_installed_distributions
ImportError: cannot import name 'get_installed_distributions' from 'pip._internal.8950utils.misc' (/home/yin/miniconda3/envs/alphapose/lib/python3.7/site-packages/pip/_internal/utils/misc.py)

please help. Thanks

**Comment by DongChengrong** [comment]
> We have tried the solution as indicated in [#1072 (comment)](https://github.com/MVIG-SJTU/AlphaPose/issues/1072#issuecomment-1224283552). It progresses, but still cannot be installed successfully.
> 
> Our issue was that Ubuntu 20.04.1 does not support the hardware in our PC, specifically the network card. while Ubuntu 22.04 can only install a Cuda with a higher version . We have managed to install Ubuntu 20.04.4 on a Dell XPS 8950, with Cuda 11.4. The installation goes a lot of further, but still have the following error, when running "python setup.py build develop"
> 
> Using /home/yin/.local/lib/python3.7/site-packages/jsonpointer-2.3-py3.7.egg Finished processing dependencies for alphapose==0.5.0+308cc9a Traceback (most recent call last): File "setup.py", line 220, in if not is_installed('cython_bbox'): File "setup.py", line 178, in is_installed from pip._internal.utils.misc import get_installed_distributions ImportError: cannot import name 'get_installed_distributions' from 'pip._internal.8950utils.misc' (/home/yin/miniconda3/envs/alphapose/lib/python3.7/site-packages/pip/_internal/utils/misc.py)
> 
> please help. Thanks

你可以把pip升级到 版本21.2.1
you can update your pip to 21.2.1

**Comment by NomiMalik0207** [comment]
@VisImage have you solved the issue?
Getting same problem.
