### ISSUE TITLE
error on "/run.sh"

### ISSUE THREAD

**Issue by wangyarui** [MVIG-SJTU/AlphaPose#108]
When I run ```sudo ./run.sh --indir examples/demo/ --outdir examples/results/ --vis ```
I get the following issues:
```
generating bbox from Faster RCNN...
Traceback (most recent call last):
  File "demo-alpha-pose.py", line 20, in <module>
    from model.test import im_detect, im_detect_fast
  File "/AlphaPose_torch/human-detection/tools/../lib/model/test.py", line 20, in <module>
    from utils.cython_nms import nms
ImportError: dynamic module does not define module export function (PyInit_cython_nms)
pose estimation with RMPE...
./run.sh: 行 78: th: 未找到命令
Traceback (most recent call last):
  File "parametric-pose-nms-MPII.py", line 256, in <module>
    get_result_json(args)
  File "parametric-pose-nms-MPII.py", line 243, in get_result_json
    test_parametric_pose_NMS_json(delta1, delta2, mu, gamma,args.outputpath)
  File "parametric-pose-nms-MPII.py", line 99, in test_parametric_pose_NMS_json
    h5file = h5py.File(os.path.join(outputpath,"POSE/test-pose.h5"), 'r')
  File "/usr/local/lib/python3.5/dist-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/local/lib/python3.5/dist-packages/h5py/_hl/files.py", line 142, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '/AlphaPose_torch/examples/results/POSE/test-pose.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
visualization...
mkdir: 无法创建目录"/AlphaPose_torch/examples/results//RENDER": 没有那个文件或目录
Traceback (most recent call last):
  File "json-video.py", line 63, in <module>
    with open(jsonpath) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'AlphaPose_torch/examples/results/POSE/alpha-pose-results-forvis.json'
```
And I have configured torch correctly...Thanks

**Comment by whitelok** [comment]
@wangyarui  please pip install nms first.

**Comment by vfsd** [comment]
When I run sudo ./run.sh --indir examples/demo/ --outdir examples/results/ --vis
I get the following issues:
(AlphaPose201809) luo@luo-ThinkPad-W540:AlphaPose$ python
Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 17:14:51) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import torchvision
>>> exit()
#---------------------------------------------
(AlphaPose201809) luo@luo-ThinkPad-W540:AlphaPose$ ./run.sh --indir examples/demo/ --outdir examples/results/ --vis
0
generating bbox from Faster RCNN...
Traceback (most recent call last):
  File "demo-alpha-pose.py", line 19, in <module>
    from model.config import cfg
  File "/home/luo/Desktop/MyFile/MVIG-SJTU/AlphaPose20180910/AlphaPose/human-detection/tools/../lib/model/__init__.py", line 1, in <module>
    from . import config
  File "/home/luo/Desktop/MyFile/MVIG-SJTU/AlphaPose20180910/AlphaPose/human-detection/tools/../lib/model/config.py", line 9, in <module>
    from easydict import EasyDict as edict
ImportError: No module named easydict
pose estimation with RMPE...
./run.sh: line 78: th: command not found
Traceback (most recent call last):
  File "parametric-pose-nms-MPII.py", line 10, in <module>
    import h5py
ImportError: No module named h5py
visualization...
mkdir: cannot create directory ‘/home/luo/Desktop/MyFile/MVIG-SJTU/AlphaPose20180910/AlphaPose/examples/results//RENDER’: No such file or directory
Traceback (most recent call last):
  File "json-video.py", line 4, in <module>
    from tqdm import tqdm
ImportError: No module named tqdm
(AlphaPose201809) luo@luo-ThinkPad-W540:AlphaPose$

**Comment by Fang-Haoshu** [comment]
Please check the FAQ and you can find the answers

**Comment by wangyarui** [comment]
@Fang-Haoshu @whitelok These don't solve my probelm, Thanks very much! I will try the pytorch version!  :+1:

**Comment by Fang-Haoshu** [comment]
Cool! Have fun!
