### ISSUE TITLE
Problem in setting up of AlphaPose  in Pycharm

### ISSUE THREAD

**Issue by SoumyajitMukherjee-droid** [MVIG-SJTU/AlphaPose#1098]
was able to successfully set up on colab...
pip freezed the requirements.txt from colab and was using the same requirements.txt to create venv in Pycharm.

PFB error stack obtained on Pycharm IDE on Windows system.

(venv) D:\IVA\IVA\IVA_Dotnet\Pose Estimation\Untitled Folder\file\content\AlphaPose>pip install -r requirements.txt
Collecting en-core-web-sm@ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.4.1/en_core_web_sm-3.4.1-py3-none-any.whl
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.4.1/en_core_web_sm-3.4.1-py3-none-any.whl (12.8 MB)
     ---------------------------------------  12.8/12.8 MB 363.3 kB/s eta 0:00:01
ERROR: Exception:
Traceback (most recent call last):
  File "d:\iva\iva\iva_dotnet\pose estimation\untitled folder\file\content\alphapose\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 437, in _error
_catcher
    yield
  File "d:\iva\iva\iva_dotnet\pose estimation\untitled folder\file\content\alphapose\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 560, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "d:\iva\iva\iva_dotnet\pose estimation\untitled folder\file\content\alphapose\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 526, in _fp_re
ad
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "d:\iva\iva\iva_dotnet\pose estimation\untitled folder\file\content\alphapose\venv\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 90, in
 read
    data = self.__fp.read(amt)
  File "C:\Program Files\Python38\lib\http\client.py", line 454, in read
    n = self.readinto(b)
  File "C:\Program Files\Python38\lib\http\client.py", line 498, in readinto
    n = self.fp.readinto(b)
  File "C:\Program Files\Python38\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Program Files\Python38\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Program Files\Python38\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\iva\iva\iva_dotnet\pose estimation\untitled folder\file\content\alphapose\venv\lib\site-packages\pip\_internal\cli\base_command.py", line 160, in exc_
logging_wrapper
    status = run_func(*args)
  File "d:\iva\iva\iva_dotnet\pose estimation\untitled folder\file\content\alphapose\venv\lib\site-packages\pip\_internal\cli\req_command.py", line 247, in wrapp
er
    return func(self, options, args)
  File "d:\iva\iva\iva_dotnet\pose estimation\untitled folder\file\content\alphapose\venv\lib\site-packages\pip\_internal\commands\install.py", line 400, in run
    requirement_set = resolver.resolve(
  File "d:\iva\iva\iva_dotnet\pose estimation\untitled folder\file\content\alphapose\venv\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", lin
e 73, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "d:\iva\iva\iva_dotnet\pose estimation\untitled folder\file\content\alphapose\venv\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line
 491, in collect_root_requirements
    req = self._make_requirement_from_install_req(
  File "d:\iva\iva\iva_dotnet\pose estimation\untitled folder\file\content\alphapose\venv\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line
 453, in _make_requirement_from_install_req
    cand = self._make_candidate_from_link(
  File "d:\iva\iva\iva_dotnet\pose estimation\untitled folder\file\content\alphapose\venv\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line
 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "d:\iva\iva\iva_dotnet\pose estimation\untitled folder\file\content\alphapose\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", l
ine 297, in __init__
    super().__init__(
  File "d:\iva\iva\iva_dotnet\pose estimation\untitled folder\file\content\alphapose\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", l
ine 162, in __init__
    self.dist = self._prepare()
  File "d:\iva\iva\iva_dotnet\pose estimation\untitled folder\file\content\alphapose\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", l
ine 231, in _prepare
    dist = self._prepare_distribution()
  File "d:\iva\iva\iva_dotnet\pose estimation\untitled folder\file\content\alphapose\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", l
ine 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "d:\iva\iva\iva_dotnet\pose estimation\untitled folder\file\content\alphapose\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 491, in pr
epare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "d:\iva\iva\iva_dotnet\pose estimation\untitled folder\file\content\alphapose\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 536, in _p
repare_linked_requirement
    local_file = unpack_url(
  File "d:\iva\iva\iva_dotnet\pose estimation\untitled folder\file\content\alphapose\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 166, in un
pack_url
    file = get_http_url(
  File "d:\iva\iva\iva_dotnet\pose estimation\untitled folder\file\content\alphapose\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 107, in ge
t_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "d:\iva\iva\iva_dotnet\pose estimation\untitled folder\file\content\alphapose\venv\lib\site-packages\pip\_internal\network\download.py", line 147, in __ca
ll__
    for chunk in chunks:
  File "d:\iva\iva\iva_dotnet\pose estimation\untitled folder\file\content\alphapose\venv\lib\site-packages\pip\_internal\cli\progress_bars.py", line 53, in _ric
h_progress_bar
    for chunk in iterable:
  File "d:\iva\iva\iva_dotnet\pose estimation\untitled folder\file\content\alphapose\venv\lib\site-packages\pip\_internal\network\utils.py", line 63, in response
_chunks
    for chunk in response.raw.stream(
  File "d:\iva\iva\iva_dotnet\pose estimation\untitled folder\file\content\alphapose\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 621, in stream

    data = self.read(amt=amt, decode_content=decode_content)
  File "d:\iva\iva\iva_dotnet\pose estimation\untitled folder\file\content\alphapose\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 586, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Program Files\Python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "d:\iva\iva\iva_dotnet\pose estimation\untitled folder\file\content\alphapose\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 442, in _error
_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='objects.githubusercontent.com', port=443): Read timed out.

(venv) D:\IVA\IVA\IVA_Dotnet\Pose Estimation\Untitled Folder\file\content\AlphaPose>

**Comment by Fang-Haoshu** [comment]
Hi, I see the HTTPSConnectionPool error. Seems to be the network issue.
