### ISSUE TITLE
Have bug in validation after train 

### ISSUE THREAD

**Issue by JulienRabault** [MVIG-SJTU/AlphaPose#1112]
train halpe26 always get some error:
```
Traceback (most recent call last):
  File "C:\Users\jrabault\Documents\00 - CNRS PRO\01 - Projet\01 - PNRIA\01 - Projet PNRIA en cours\05 - ASTANA\Code\pnria-astana\TestHPE\AlphaPose\scripts\train.py", line 350, in <module>
    main()
  File "C:\Users\jrabault\Documents\00 - CNRS PRO\01 - Projet\01 - PNRIA\01 - Projet PNRIA en cours\05 - ASTANA\Code\pnria-astana\TestHPE\AlphaPose\scripts\train.py", line 307, in main
    gt_AP = validate_gt(m.module, opt, cfg, heatmap_to_coord)
  File "C:\Users\jrabault\Documents\00 - CNRS PRO\01 - Projet\01 - PNRIA\01 - Projet PNRIA en cours\05 - ASTANA\Code\pnria-astana\TestHPE\AlphaPose\scripts\train.py", line 244, in validate_gt
    res = evaluate_mAP(os.path.join(opt.work_dir, 'test_gt_kpt.json'), ann_type='keypoints', ann_file=os.path.join(cfg.DATASET.VAL.ROOT, cfg.DATASET.VAL.ANN), halpe=halpe)
  File "c:\users\jrabault\documents\00 - cnrs pro\01 - projet\01 - pnria\01 - projet pnria en cours\05 - astana\code\pnria-astana\testhpe\alphapose\alphapose\utils\metrics.py", line 103, in evaluate_mAP
    cocoEval = COCOeval(cocoGt, cocoDt, ann_type)
  File "C:\Users\jrabault\Documents\00 - CNRS PRO\01 - Projet\01 - PNRIA\01 - Projet PNRIA en cours\05 - ASTANA\Code\pnria-astana\venv\lib\site-packages\pycocotools\cocoeval.py", line 76, in __init__
    self.params = Params(iouType=iouType) # parameters
  File "C:\Users\jrabault\Documents\00 - CNRS PRO\01 - Projet\01 - PNRIA\01 - Projet PNRIA en cours\05 - ASTANA\Code\pnria-astana\venv\lib\site-packages\pycocotools\cocoeval.py", line 529, in __init__
    self.setKpParams()
  File "C:\Users\jrabault\Documents\00 - CNRS PRO\01 - Projet\01 - PNRIA\01 - Projet PNRIA en cours\05 - ASTANA\Code\pnria-astana\venv\lib\site-packages\pycocotools\cocoeval.py", line 518, in setKpParams
    self.iouThrs = np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True)
  File "<__array_function__ internals>", line 200, in linspace
  File "C:\Users\jrabault\Documents\00 - CNRS PRO\01 - Projet\01 - PNRIA\01 - Projet PNRIA en cours\05 - ASTANA\Code\pnria-astana\venv\lib\site-packages\numpy\core\function_base.py", line 121, in linspace
    num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an integer
Exception ignored in: <alphapose.utils.metrics.evaluate_mAP.<locals>.NullWriter object at 0x0000025081C95FA0>
AttributeError: 'NullWriter' object has no attribute 'flush'
```
how to avoid this error??

**Comment by JulienRabault** [comment]
Solve : 
```
pip uninstall pycocotools
pip install pycocotools
```

**Comment by JulienRabault** [comment]
Solve : 
```
pip uninstall pycocotools
pip install pycocotools
```
