### ISSUE TITLE
ImportError: cannot import name 'deform_conv_cuda' from partially initialized module 'alphapose.models.layers.dcn' (most likely due to a circular import) (z:\alphapose-master\alphapose\models\layers\dcn\__init__.py)

### ISSUE THREAD

**Issue by Qianmengs** [MVIG-SJTU/AlphaPose#1126]
PS Z:\AlphaPose-master> python scripts/demo_inference.py --cfg configs/halpe_coco_wholebody_136/resnet/256x192_res50_lr1e-3_2x-dcn-combined.yaml --checkpoint pretrained_models/multi_domain_fast50_dcn_combined_256x192.pth --indir exa
mples/demo/ --save_img
Traceback (most recent call last):
  File "scripts/demo_inference.py", line 180, in <module>
    pose_model = builder.build_sppe(cfg.MODEL, preset_cfg=cfg.DATA_PRESET)
  File "z:\alphapose-master\alphapose\models\builder.py", line 27, in build_sppe
    return build(cfg, SPPE, default_args=default_args)
  File "z:\alphapose-master\alphapose\models\builder.py", line 18, in build
    return build_from_cfg(cfg, registry, default_args)
  File "z:\alphapose-master\alphapose\utils\registry.py", line 75, in build_from_cfg
    return obj_cls(**args)
  File "z:\alphapose-master\alphapose\models\fastpose.py", line 26, in __init__
    self.preact = SEResnet(
  File "z:\alphapose-master\alphapose\models\layers\SE_Resnet.py", line 174, in __init__
    self.layer2 = self.make_layer(
  File "z:\alphapose-master\alphapose\models\layers\SE_Resnet.py", line 204, in make_layer
    layers.append(block(self.inplanes, planes,
  File "z:\alphapose-master\alphapose\models\layers\SE_Resnet.py", line 79, in __init__
    from .dcn import DeformConv, ModulatedDeformConv
  File "z:\alphapose-master\alphapose\models\layers\dcn\__init__.py", line 1, in <module>
    from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv,
  File "z:\alphapose-master\alphapose\models\layers\dcn\deform_conv.py", line 9, in <module>
    from . import deform_conv_cuda
ImportError: cannot import name 'deform_conv_cuda' from partially initialized module 'alphapose.models.layers.dcn' (most likely due to a circular import) (z:\alphapose-master\alphapose\models\layers\dcn\__init__.py)
Loading YOLO model..

**Comment by Mp991004** [comment]
你好，请问解决这个问题了吗

**Comment by zhu-0504** [comment]
我也出现了这个问题，请问解决了吗

**Comment by BetterForerunner** [comment]
考虑您的cuda版本是否一致。我是list出了各项cuda工具版本，发现有不一致的部分。remove了 torch 以及cuda相关部分 重新下载，解决了这个问题。并且setup.py中124行修改：force_compile = True
