### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by Harry-Miral** [MVIG-SJTU/AlphaPose#1127]
I used “python scripts/demo_inference.py --cfg configs/smpl/256x192_adam_lr1e-3-res34_smpl_24_3d_base_2x_mix.yaml --checkpoint pretrained_models/pretrained_w_cam.pth --indir examples/demo/ --outdir examples/res --save_img”，which is “3D Human Pose & Shape Estimation”.

Then its error is

Loading YOLO model..
Traceback (most recent call last):
  File "D:\AlphaPose-master\AlphaPose-master\demo_inference.py", line 180, in <module>
    pose_model = builder.build_sppe(cfg.MODEL, preset_cfg=cfg.DATA_PRESET)
  File "D:\AlphaPose-master\AlphaPose-master\alphapose\models\builder.py", line 27, in build_sppe
    return build(cfg, SPPE, default_args=default_args)
  File "D:\AlphaPose-master\AlphaPose-master\alphapose\models\builder.py", line 18, in build
    return build_from_cfg(cfg, registry, default_args)
  File "D:\AlphaPose-master\AlphaPose-master\alphapose\utils\registry.py", line 75, in build_from_cfg
    return obj_cls(**args)
  File "D:\AlphaPose-master\AlphaPose-master\alphapose\models\simple3dposeSMPLWithCam.py", line 58, in __init__
    x = tm.resnet34(pretrained=True)
  File "C:\ProgramData\anaconda3\envs\AlphaPose-master\lib\site-packages\torchvision\models\resnet.py", line 288, in resnet34
    return _resnet('resnet34', BasicBlock, [3, 4, 6, 3], pretrained, progress,
  File "C:\ProgramData\anaconda3\envs\AlphaPose-master\lib\site-packages\torchvision\models\resnet.py", line 262, in _resnet
    state_dict = load_state_dict_from_url(model_urls[arch],
  File "C:\ProgramData\anaconda3\envs\AlphaPose-master\lib\site-packages\torch\hub.py", line 575, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "C:\ProgramData\anaconda3\envs\AlphaPose-master\lib\site-packages\torch\serialization.py", line 600, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "C:\ProgramData\anaconda3\envs\AlphaPose-master\lib\site-packages\torch\serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

I checked the version to confirm that it was correct.Download the model several times and replace it, again.I don't know how to fix this, it is possible that the model that provides the download is broken.

Then I looked up HybrIK.When I want to download the ResNet-34 model and cfg,very unpleasant, and it is not available for download.I don't know what to do right now and 我人麻了.

Save me, thanks！

**Comment by LiYangDoYourself** [comment]
我也遇到了同样的问题 请问你如何解决的
