### ISSUE TITLE
Alphapose 3D not working on colab

### ISSUE THREAD

**Issue by RohaanA** [MVIG-SJTU/AlphaPose#1167]
```
Loading pose model from pretrained_models/fast_res50_256x192.pth...
2023-08-17 12:31:22 [DEBUG]: Loaded backend agg version v2.2.
2023-08-17 12:31:22 [DEBUG]: Loaded backend agg version v2.2.
2023-08-17 12:31:22 [DEBUG]: Loaded backend agg version v2.2.
Loading YOLO model..
  0% 0/3 [00:01<?, ?it/s]
TypeError("FastPose.forward() got an unexpected keyword argument 'flip_test'")
An error as above occurs when processing the images, please check it
2023-08-17 12:31:27 [DEBUG]: Loaded backend agg version v2.2.
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/forkserver.py", line 274, in main
    code = _serve_one(child_r, fds,
  File "/usr/lib/python3.10/multiprocessing/forkserver.py", line 313, in _serve_one
    code = spawn._main(child_r, parent_sentinel)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "/usr/lib/python3.10/multiprocessing/synchronize.py", line 110, in __setstate__
    self._semlock = _multiprocessing.SemLock._rebuild(*state)
FileNotFoundError: [Errno 2] No such file or directory
```

I've been trying to run 3D inference (Alphapose) on the default colab, but Its not working. I am not sure if the command I am using it is the problem?

My current command is this,

`! python3 scripts/demo_3d_inference.py --cfg configs/coco/resnet/256x192_res50_lr1e-3_1x.yaml --checkpoint pretrained_models/fast_res50_256x192.pth --indir examples/demo/ --save_img
`

**Comment by RohaanA** [comment]
I was able to fix this error.

You need to choose the smpl config, and download the smpl model from github
