### ISSUE TITLE
error on 'demo.py' ,when I run alphapose for all images in a folder with: 

### ISSUE THREAD

**Issue by tianjiahao** [MVIG-SJTU/AlphaPose#117]
computervision@computervision-Precision-WorkStation-T5500:~/Desktop/AlphaPose$ python3 demo.py --indir examples/demo --outdir examples/res 
Loading YOLO model..
Traceback (most recent call last):
  File "demo.py", line 50, in <module>
    det_loader = DetectionLoader(data_loader, batchSize=args.detbatch).start()
  File "/home/computervision/Desktop/AlphaPose/dataloader.py", line 309, in start
    p.start()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.5/multiprocessing/context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.5/multiprocessing/context.py", line 281, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.5/multiprocessing/popen_forkserver.py", line 36, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.5/multiprocessing/popen_forkserver.py", line 48, in _launch
    reduction.dump(process_obj, buf)
  File "/usr/lib/python3.5/multiprocessing/reduction.py", line 59, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "/home/computervision/.local/lib/python3.5/site-packages/torch/multiprocessing/reductions.py", line 179, in reduce_storage
    raise RuntimeError("Cannot pickle CUDA storage; try pickling a CUDA tensor instead")
RuntimeError: Cannot pickle CUDA storage; try pickling a CUDA tensor instead
/usr/lib/python3.5/multiprocessing/semaphore_tracker.py:129: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))

**Comment by Fang-Haoshu** [comment]
Can you check if your CUDA works normally, like trying 'nvidia-smi' ?

**Comment by tianjiahao** [comment]
computervision@computervision-Precision-WorkStation-T5500:~$ nvidia-smi
Thu Sep 13 14:47:23 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.130                Driver Version: 384.130                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:03:00.0  On |                  N/A |
|  0%   50C    P8    19W / 250W |    203MiB / 11171MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      2334      G   /usr/lib/xorg/Xorg                           109MiB |
|    0      2938      G   compiz                                        82MiB |
|    0      3207      G   fcitx-qimpanel                                 9MiB |
+-----------------------------------------------------------------------------+
computervision@computervision-Precision-WorkStation-T5500:~$

**Comment by tianjiahao** [comment]
computervision@computervision-Precision-WorkStation-T5500:~$ python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> hello=tf.constant('hello,world!')
>>> sess=tf.Session()
2018-09-13 14:51:08.868973: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2
2018-09-13 14:51:09.054953: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-09-13 14:51:09.055503: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.6325
pciBusID: 0000:03:00.0
totalMemory: 10.91GiB freeMemory: 10.55GiB
2018-09-13 14:51:09.055534: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:03:00.0, compute capability: 6.1)
>>> print(sess.run(hello))
b'hello,world!'

**Comment by Molength** [comment]
I also met this problems.

**Comment by Molength** [comment]
I have slove this problem,,maybe you installed torch 0.4.1 .
change to the 0.4.0 ,all is ok

**Comment by tianjiahao** [comment]
Thank you for your advice, I will try it！


| |
田佳豪
|
|
tianjiahao_369@163.com
|
签名由网易邮箱大师定制
On 9/15/2018 12:33，Molength<notifications@github.com> wrote：

I have slove this problem,,maybe you installed torch 0.4.1 .
change to the 0.4.0 ,all is ok

**Comment by Fang-Haoshu** [comment]
Seems pytorch  0.4.0 can solve this problem

**Comment by vdevmcitylp** [comment]
The warning comes up when multiprocessing is being used, run the code after disabling it.
Try: python demo.py --indir <> --outdir <> --sp

`if not args.sp:`
&nbsp;&nbsp;&nbsp;&nbsp;`torch.multiprocessing.set_start_method('forkserver', force=True)`
&nbsp;&nbsp;&nbsp;&nbsp;`torch.multiprocessing.set_sharing_strategy('file_system')`

**Comment by ximitiejiang** [comment]
`python demo.py --indir <> --outdir <> --sp`
yeah, it works on my pytorch 0.4.1 by this way
