### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by comgs2** [MVIG-SJTU/AlphaPose#1191]
At the installation of thie repository, the following error occurred.

```
$ python setup.py build develop --user
/usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
/usr/lib/python3/dist-packages/pythran/tables.py:4520: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  if not hasattr(numpy, method):
/usr/lib/python3/dist-packages/pythran/tables.py:4553: FutureWarning: In the future `np.bytes` will be defined as the corresponding NumPy scalar.
  obj = getattr(themodule, elem)
/usr/lib/python3/dist-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
  warnings.warn(
running build
running build_py
copying alphapose/version.py -> build/lib.linux-x86_64-3.10/alphapose
running build_ext
/home/ishihara/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py:502: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
/home/ishihara/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py:424: UserWarning: There are no x86_64-linux-gnu-g++ version bounds defined for CUDA version 12.1
  warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
running develop
/usr/lib/python3/dist-packages/setuptools/command/easy_install.py:158: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running egg_info
writing alphapose.egg-info/PKG-INFO
writing dependency_links to alphapose.egg-info/dependency_links.txt
writing requirements to alphapose.egg-info/requires.txt
writing top-level names to alphapose.egg-info/top_level.txt
reading manifest file 'alphapose.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'alphapose.egg-info/SOURCES.txt'
running build_ext
/home/ishihara/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py:424: UserWarning: There are no x86_64-linux-gnu-g++ version bounds defined for CUDA version 12.1
  warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
copying build/lib.linux-x86_64-3.10/detector/nms/soft_nms_cpu.cpython-310-x86_64-linux-gnu.so -> detector/nms
copying build/lib.linux-x86_64-3.10/detector/nms/nms_cpu.cpython-310-x86_64-linux-gnu.so -> detector/nms
copying build/lib.linux-x86_64-3.10/detector/nms/nms_cuda.cpython-310-x86_64-linux-gnu.so -> detector/nms
copying build/lib.linux-x86_64-3.10/alphapose/utils/roi_align/roi_align_cuda.cpython-310-x86_64-linux-gnu.so -> alphapose/utils/roi_align
copying build/lib.linux-x86_64-3.10/alphapose/models/layers/dcn/deform_conv_cuda.cpython-310-x86_64-linux-gnu.so -> alphapose/models/layers/dcn
copying build/lib.linux-x86_64-3.10/alphapose/models/layers/dcn/deform_pool_cuda.cpython-310-x86_64-linux-gnu.so -> alphapose/models/layers/dcn
Creating /home/ishihara/.local/lib/python3.10/site-packages/alphapose.egg-link (link to .)
alphapose 0.5.0+c60106d is already the active version in easy-install.pth

Installed /home/ishihara/AlphaPose
Processing dependencies for alphapose==0.5.0+c60106d
Searching for halpecocotools
Reading https://pypi.tuna.tsinghua.edu.cn/simple/halpecocotools/
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
  warnings.warn(
Downloading https://pypi.tuna.tsinghua.edu.cn/packages/f9/b0/f2e783a29a30cf0e66e3bbc45cdc4da6e9214bc21f4df948ee9a7d79764e/halpecocotools-0.0.0.tar.gz#sha256=8355964f7d14e69b2a555be7e116eae8979ec2a04f0eef16d140b38d04f933eb
Best match: halpecocotools 0.0.0
Processing halpecocotools-0.0.0.tar.gz
Writing /tmp/easy_install-uwqu9zqw/halpecocotools-0.0.0/setup.cfg
Running halpecocotools-0.0.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-uwqu9zqw/halpecocotools-0.0.0/egg-dist-tmp-uvv710sd
warning: no files found matching '*.pxd'
warning: no files found matching '*.pyx'
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/easy_install-uwqu9zqw/halpecocotools-0.0.0/halpecocotools/_mask.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
Traceback (most recent call last):
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "/usr/local/lib/python3.10/dist-packages/Cython/Compiler/ParseTreeTransforms.py", line 3112, in visit_StatListNode
    if not self.current_directives['remove_unreachable']:
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 156, in save_modules
    yield saved
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-uwqu9zqw/halpecocotools-0.0.0/setup.py", line 16, in <module>
    
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 23, in run
    self.build()
  File "/usr/lib/python3.10/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_ext')
  File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/usr/lib/python3.10/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/usr/lib/python3.10/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.10/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/local/lib/python3.10/dist-packages/Cython/Distutils/build_ext.py", line 130, in build_extension
    new_ext = cythonize(
  File "/usr/local/lib/python3.10/dist-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
    cythonize_one(*args)
  File "/usr/local/lib/python3.10/dist-packages/Cython/Build/Dependencies.py", line 1300, in cythonize_one
    result = compile_single(pyx_file, options, full_module_name=full_module_name)
  File "/usr/local/lib/python3.10/dist-packages/Cython/Compiler/Main.py", line 615, in compile_single
    return run_pipeline(source, options, full_module_name)
  File "/usr/local/lib/python3.10/dist-packages/Cython/Compiler/Main.py", line 539, in run_pipeline
    err, enddata = Pipeline.run_pipeline(pipeline, source)
  File "/usr/local/lib/python3.10/dist-packages/Cython/Compiler/Pipeline.py", line 398, in run_pipeline
    data = run(phase, data)
  File "/usr/local/lib/python3.10/dist-packages/Cython/Compiler/Pipeline.py", line 375, in run
    return phase(data)
  File "Cython/Compiler/Visitor.py", line 312, in Cython.Compiler.Visitor.CythonTransform.__call__
  File "Cython/Compiler/Visitor.py", line 294, in Cython.Compiler.Visitor.VisitorTransform.__call__
  File "Cython/Compiler/Visitor.py", line 184, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 322, in Cython.Compiler.Visitor.CythonTransform.visit_Node
  File "Cython/Compiler/Visitor.py", line 260, in Cython.Compiler.Visitor.VisitorTransform._process_children
  File "Cython/Compiler/Visitor.py", line 227, in Cython.Compiler.Visitor.TreeVisitor._visitchildren
  File "Cython/Compiler/Visitor.py", line 196, in Cython.Compiler.Visitor.TreeVisitor._visitchild
  File "Cython/Compiler/Visitor.py", line 190, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 148, in Cython.Compiler.Visitor.TreeVisitor._raise_compiler_error
Cython.Compiler.Errors.CompilerCrash: 
Error compiling Cython file:
------------------------------------------------------------
...
# distutils: language = c
^
------------------------------------------------------------

halpecocotools/_mask.pyx:1:0: Compiler crash in RemoveUnreachableCode

ModuleNode.body = StatListNode(_mask.pyx:1:0)

Compiler crash traceback from this point on:
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "/usr/local/lib/python3.10/dist-packages/Cython/Compiler/ParseTreeTransforms.py", line 3112, in visit_StatListNode
    if not self.current_directives['remove_unreachable']:
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ishihara/AlphaPose/setup.py", line 187, in <module>
    setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/usr/lib/python3/dist-packages/setuptools/command/develop.py", line 129, in install_for_development
    self.process_distribution(None, self.dist, not self.no_deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 775, in process_distribution
    distros = WorkingSet([]).resolve(
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 771, in resolve
    dist = best[req.key] = env.best_match(
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1056, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1068, in obtain
    return installer(requirement)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 700, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 726, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 921, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1193, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1177, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 249, in run_setup
    with setup_context(setup_dir):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 190, in setup_context
    with save_modules():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 143, in resume
    raise exc.with_traceback(self._tb)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 156, in save_modules
    yield saved
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-uwqu9zqw/halpecocotools-0.0.0/setup.py", line 16, in <module>
    
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 23, in run
    self.build()
  File "/usr/lib/python3.10/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_ext')
  File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/usr/lib/python3.10/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/usr/lib/python3.10/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.10/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/local/lib/python3.10/dist-packages/Cython/Distutils/build_ext.py", line 130, in build_extension
    new_ext = cythonize(
  File "/usr/local/lib/python3.10/dist-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
    cythonize_one(*args)
  File "/usr/local/lib/python3.10/dist-packages/Cython/Build/Dependencies.py", line 1300, in cythonize_one
    result = compile_single(pyx_file, options, full_module_name=full_module_name)
  File "/usr/local/lib/python3.10/dist-packages/Cython/Compiler/Main.py", line 615, in compile_single
    return run_pipeline(source, options, full_module_name)
  File "/usr/local/lib/python3.10/dist-packages/Cython/Compiler/Main.py", line 539, in run_pipeline
    err, enddata = Pipeline.run_pipeline(pipeline, source)
  File "/usr/local/lib/python3.10/dist-packages/Cython/Compiler/Pipeline.py", line 398, in run_pipeline
    data = run(phase, data)
  File "/usr/local/lib/python3.10/dist-packages/Cython/Compiler/Pipeline.py", line 375, in run
    return phase(data)
  File "Cython/Compiler/Visitor.py", line 312, in Cython.Compiler.Visitor.CythonTransform.__call__
  File "Cython/Compiler/Visitor.py", line 294, in Cython.Compiler.Visitor.VisitorTransform.__call__
  File "Cython/Compiler/Visitor.py", line 184, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 322, in Cython.Compiler.Visitor.CythonTransform.visit_Node
  File "Cython/Compiler/Visitor.py", line 260, in Cython.Compiler.Visitor.VisitorTransform._process_children
  File "Cython/Compiler/Visitor.py", line 227, in Cython.Compiler.Visitor.TreeVisitor._visitchildren
  File "Cython/Compiler/Visitor.py", line 196, in Cython.Compiler.Visitor.TreeVisitor._visitchild
  File "Cython/Compiler/Visitor.py", line 190, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 148, in Cython.Compiler.Visitor.TreeVisitor._raise_compiler_error
setuptools.sandbox.UnpickleableException: CompilerCrash((<FileSourceDescriptor:/tmp/easy_install-uwqu9zqw/halpecocotools-0.0.0/halpecocotools/_mask.pyx>, 1, 0), 'RemoveUnreachableCode', 'Compiler crash in RemoveUnreachableCode\n\nModuleNode.body = StatListNode(_mask.pyx:1:0)\n\nCompiler crash traceback from this point on:\n  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit\n  File "/usr/local/lib/python3.10/dist-packages/Cython/Compiler/ParseTreeTransforms.py", line 3112, in visit_StatListNode\n    if not self.current_directives[\'remove_unreachable\']:\nTypeError: \'NoneType\' object is not subscriptable', TypeError("'NoneType' object is not subscriptable"), <traceback object at 0x7f5a2d480d00>)
```

My environment is as follows:

Ubuntu: 22.04
Python: 3.10
CUDA: 12.1
torch: 2.1.1
tensorflow: 2.15.0.post1
Cython: 3.0.6

Please tell me how to fix it on this environment.

**Comment by Ishihara-Masabumi** [comment]
I have the same issue.

**Comment by GHOST-LOVE-YOU** [comment]
same
