### ISSUE TITLE
Error During training

### ISSUE THREAD

**Issue by UsamaShaikh1** [MVIG-SJTU/AlphaPose#1196]
Hello, i am encountering an error during training. I am using the following training command
 ./scripts/train.sh ./configs/coco/resnet/256x192_res50_lr1e-3_1x.yaml exp_fastpose

The following is the error
Traceback (most recent call last):
  File "./scripts/train.py", line 345, in <module>
    main()
  File "./scripts/train.py", line 303, in main
    rcnn_AP = validate(m.module, opt, heatmap_to_coord)
  File "./scripts/train.py", line 121, in validate
    det_dataset = builder.build_dataset(cfg.DATASET.TEST, preset_cfg=cfg.DATA_PRESET, train=False, opt=opt)
  File "Desktop/AlphaPose/alphapose/models/builder.py", line 41, in build_dataset
    return build(cfg, DATASET, default_args=default_args)
  File "Desktop/AlphaPose/alphapose/models/builder.py", line 18, in build
    return build_from_cfg(cfg, registry, default_args)
  File "Desktop/AlphaPose/alphapose/utils/registry.py", line 75, in build_from_cfg
    return obj_cls(**args)
  File "Desktop/AlphaPose/alphapose/datasets/coco_det.py", line 45, in __init__
    self.write_coco_json(det_file)
  File "Desktop/AlphaPose/alphapose/datasets/coco_det.py", line 91, in write_coco_json
    det_model = get_detector(self._opt)
  File "Desktop/AlphaPose/detector/apis.py", line 12, in get_detector
    from detector.yolo_api import YOLODetector
  File "Desktop/AlphaPose/detector/yolo_api.py", line 27, in <module>
    from detector.nms import nms_wrapper
  File "Desktop/AlphaPose/detector/nms/__init__.py", line 1, in <module>
    from .nms_wrapper import nms, soft_nms
  File "Desktop/AlphaPose/detector/nms/nms_wrapper.py", line 4, in <module>
    from . import nms_cpu, nms_cuda
ImportError: Desktop/AlphaPose/detector/nms/nms_cpu.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIdEEPKNS_6detail12TypeMetaDataEv

can you please look into it and tell me where i am going wrong, Thanks.

**Comment by wl-nb** [comment]
你好，请问可以加你一个联系方式交流一下吗？刚接触alphapose有些问题，一起交流一下

**Comment by lsm101010** [comment]
@wl-nb 你好，加一下联系方式吗？我也在搞这个，交流一下吗？v:am-0017
