### ISSUE TITLE
No module named 'gpu_nms'

### ISSUE THREAD

**Issue by fanglw** [MVIG-SJTU/AlphaPose#12]
Hi, I followed the instruction to install AlphaPose, but when I run the test demo, it comes out this error. How to solve this. Thanks. 

~/project/AlphaPose$ ./run.sh --indir examples/demo/ --outdir examples/results/ --vis
0
generating bbox from Faster RCNN...
Traceback (most recent call last):
  File "demo-alpha-pose.py", line 22, in <module>
    from newnms.nms import  soft_nms
  File "/nfs/home/longwei/project/AlphaPose/human-detection/tools/../lib/newnms/nms.py", line 4, in <module>
    from gpu_nms import gpu_nms
ImportError: No module named 'gpu_nms'
pose estimation with RMPE...
./run.sh: line 78: th: command not found
_frozen_importlib:321: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
Traceback (most recent call last):
  File "parametric-pose-nms-MPII.py", line 256, in <module>
    get_result_json(args)
  File "parametric-pose-nms-MPII.py", line 243, in get_result_json
    test_parametric_pose_NMS_json(delta1, delta2, mu, gamma,args.outputpath)
  File "parametric-pose-nms-MPII.py", line 99, in test_parametric_pose_NMS_json
    h5file = h5py.File(os.path.join(outputpath,"POSE/test-pose.h5"), 'r')
  File "/nfs/home/longwei/anaconda2/envs/mask_rcnn_old/lib/python3.4/site-packages/h5py/_hl/files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/nfs/home/longwei/anaconda2/envs/mask_rcnn_old/lib/python3.4/site-packages/h5py/_hl/files.py", line 99, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '/nfs/home/longwei/project/AlphaPose/examples/results/POSE/test-pose.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
visualization...
Traceback (most recent call last):
  File "json-video.py", line 63, in <module>
    with open(jsonpath) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/nfs/home/longwei/project/AlphaPose/examples/results/POSE/alpha-pose-results-forvis.json'

**Comment by Fang-Haoshu** [comment]
Hi, do you met any problem when installing our code?
First of all, it seems the nms is not made properly. Try
```
cd AlphaPose/human-detection/lib/
make clean
make
cd newnms/
make
```
Second, torch is not installed properly. Please refer to  #10 to see how to install torch properly.
