### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '${cfg_file}'

### ISSUE THREAD

**Issue by tesonhub** [MVIG-SJTU/AlphaPose#1207]
I had this error while trying to run the code using a usb camera and cpu only. Is there a way to resolve this issue?

(alphapose) C:\Users\Teson\AlphaPose>python scripts/demo_inference.py --cfg ${cfg_file} --checkpoint ${trained_model} --outdir examples/res --vis --webcam 0
Traceback (most recent call last):
  File "scripts/demo_inference.py", line 88, in <module>
    cfg = update_config(args.cfg)
  File "c:\users\teson\alphapose\alphapose\utils\config.py", line 6, in update_config
    with open(config_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '${cfg_file}'

**Comment by Mp991004** [comment]
Have you solved this problem？

**Comment by ailettuce80** [comment]
I think you were supposed to replace it with your path. The issue is, im now looking where the config file is located. It should be YAML.

**Comment by ailettuce80** [comment]
I found out that you need to suply one of the yaml files such as `\configs\halpe_26\resnet\256x192_res50_lr1e-3_1x.yaml`
