### ISSUE TITLE
运行demo.py，出现name 'im_names' is not defined错误

### ISSUE THREAD

**Issue by linshuheng6** [MVIG-SJTU/AlphaPose#132]
D:\PythonModel\Alphapose-pytorch>python demo.py --indir ${F:\迅雷下载} --outdir examples/res --sp
Traceback (most recent call last):
  File "demo.py", line 45, in <module>
    data_loader = ImageLoader(im_names, batchSize=args.detbatch, format='yolo').start()
NameError: name 'im_names' is not defined

按照Readme一步一步来，实在不知道为什么会出现这个错误。。。看了源码也不知道为什么，求解答呀

**Comment by Jeff-sjtu** [comment]
你好，
你确保window下，这样的文件夹路径参数输入是可用的吗？

**Comment by linshuheng6** [comment]
抱歉，我命令行太菜了，还需要加强学习，用了正确的路径过后出现CUDA的问题

F:\GItclone\AlphaPose>python demo.py --indir F:\TestIma --outdir examples/res --sp
Loading YOLO model..
THCudaCheck FAIL file=..\aten\src\THC\THCGeneral.cpp line=74 error=35 : CUDA driver version is insufficient for CUDA runtime version
Traceback (most recent call last):
  File "demo.py", line 50, in <module>
    det_loader = DetectionLoader(data_loader, batchSize=args.detbatch).start()
  File "F:\GItclone\AlphaPose\dataloader.py", line 281, in __init__
    self.det_model.cuda()
  File "D:\python36\lib\site-packages\torch\nn\modules\module.py", line 258, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "D:\python36\lib\site-packages\torch\nn\modules\module.py", line 185, in _apply
    module._apply(fn)
  File "D:\python36\lib\site-packages\torch\nn\modules\module.py", line 185, in _apply
    module._apply(fn)
  File "D:\python36\lib\site-packages\torch\nn\modules\module.py", line 185, in _apply
    module._apply(fn)
  File "D:\python36\lib\site-packages\torch\nn\modules\module.py", line 191, in _apply
    param.data = fn(param.data)
  File "D:\python36\lib\site-packages\torch\nn\modules\module.py", line 258, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at ..\aten\src\THC\THCGeneral.cpp:74

我的系统为win10， cuda9.0+cudnn7，请问作者的cuda版本是多少呢

**Comment by Fang-Haoshu** [comment]
Thanks @xuchao1688
