### ISSUE TITLE
"AttributeError: 'NoneType' object has no attribute 'shape'" when using input list demo

### ISSUE THREAD

**Issue by SeanSyue** [MVIG-SJTU/AlphaPose#143]
I'm using **`Ubuntu 16.04 LTS`** and run the "Input list" demo of the `pytorch branch` with **`Python 3.6.6`**. I downloaded the `coco train2017` dataset, then I ran the command
```
img_directory=path/to/coco/train2017
python3 demo.py --list examples/list-coco-demo.txt --indir ${img_directory} --outdir examples/res --save_img
```
and got the following error message:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ee303/WORKSPACE/AlphaPose/dataloader.py", line 150, in getitem_yolo
    img_k, orig_img_k, im_dim_list_k = prep_image(im_name_k, inp_dim)
  File "/home/ee303/WORKSPACE/AlphaPose/yolo/preprocess.py", line 42, in prep_image
    dim = orig_im.shape[1], orig_im.shape[0]
AttributeError: 'NoneType' object has no attribute 'shape'

Loading pose model from ./models/sppe/duc_se.pth
 35%|███▌      | 7/20 [00:20<00:01,  6.75it/s]Traceback (most recent call last):
  File "/home/ee303/WORKSPACE/AlphaPose/demo.py", line 78, in <module>
    (inps, orig_img, im_name, boxes, scores, pt1, pt2) = det_processor.read()
  File "/home/ee303/WORKSPACE/AlphaPose/dataloader.py", line 420, in read
    return self.Q.get()
  File "/usr/lib/python3.6/queue.py", line 164, in get
    self.not_empty.wait()
  File "/usr/lib/python3.6/threading.py", line 295, in wait
    waiter.acquire()
KeyboardInterrupt
```
Is there something went wrong?

**Comment by SeanSyue** [comment]
Same issue [here](https://github.com/MVIG-SJTU/AlphaPose/issues/106#issuecomment-421889834).

**Comment by Jeff-sjtu** [comment]
Please make sure you give the right image name or image path.

**Comment by David3310273** [comment]
I have changed my img_directory param into `examples/demo` under the root directory in the project and still got the same error after I run the command, and the worst thing is, my program just got stuck at the place where it's loading the pose model from `./models/sppe/duc_se.pth`, any help would be appreciated.

**Comment by christw16** [comment]
@David3310273  Hello!
Did you solve this error?
Thank you~
