### ISSUE TITLE
用重新训练得到的模型进行检测时权重维度报错

### ISSUE THREAD

**Issue by ZhongXiaoFang** [MVIG-SJTU/AlphaPose#145]
您好，大神，根据您之前的指导初步完成了在COCO数据上的训练，当用模型进行检测的时候却出现了权重维度大小不匹配的情况，折腾很久没有解决，求指点。。。谢谢
Loading pose model from ./models/sppe/model_49.pkl
Traceback (most recent call last):
  File "demo.py", line 56, in <module>
    pose_model = InferenNet_fast(4 * 1 + 1, pose_dataset)
  File "/home/zhong/AlphaPose/SPPE/src/main_fast_inference.py", line 61, in __init__
    model.load_state_dict(torch.load('./models/sppe/model_49.pkl'))
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for FastPose:
	size mismatch for conv_out.bias: copying a param of torch.Size([33]) from checkpoint, where the shape is torch.Size([17]) in current model.
	size mismatch for conv_out.weight: copying a param of torch.Size([33, 128, 3, 3]) from checkpoint, where the shape is torch.Size([17, 128, 3, 3]) in current model.

**Comment by Jeff-sjtu** [comment]
你好，你训练时候用的网络是33*h*w，但是预测的时候用的是17*h*w的网络结构来load模型，导致冲突。

**Comment by hcsearch** [comment]
这个问题我刚才也遇到了，我训练了coco train2017，目前来说，效果还不是很好，还检测不出来任何骨骼点（我的训练次数还不多，目前只是跑下流程）。
不过目前有四个问题：
一：官方的输出分类是33，这个33是怎么回事？33个骨骼点吗？因为在coco上面是17个输出分类，所以在预测的时候我修改了输出分类为17，这样便可正常运行起来。不过我依然不太了解33是怎么回事？
二：在训练的时候官方batchsize为128，一运行的时候就出现的out of memony,所以我修改了batchsize为32才在我的机器上跑起来，官方是怎么在batchsize为128上跑起来的呢？ 难道是用很多内存撑起来的吗？
三：训练的readme上面说的第三种情况，可在预训练模式上面再训练，但是现在的输出分类数不一样，一个是17，一个预训练模型的33分类，这样看似应该就训练不起来，因为输出维度都不一样。是这样吗？
四：预训练模型的输出是33类别，在预测的时候，我保存了最后的预测图，看上去好像也只有17个heatmap的结果，这又是怎么回事呢？
这是我遇到的问题，如有错误的地方还请包含，谢过。

**Comment by Jeff-sjtu** [comment]
你好，
关于问题1&4：33的heatmap是包括了coco和mpii数据集的输出，在inference的demo中，取了前17个heatmap输出作为coco数据集的结果，如果取后16个heatmap即是mpii数据集的关键点。
问题2：batchsize需要根据你使用的gpu数量以及显存大小决定。
问题3：预训练模式是指训练到一定程度后，可以load模型，加入dpg模式训练继续在原本模型的基础上训练。如果想对我们放出来的模型在coco数据集上自行训练，需要自行对最后一层卷积层复制参数。

**Comment by hcsearch** [comment]
问题三的意思之前有点表述不清楚，其实就是想在你们放出来的模型上再加入一些数据自行训练。“如果想对我们放出来的模型在coco数据集上自行训练，需要自行对最后一层卷积层复制参数”的意思是类似于需要做fine tune吗？其它问题基本明白了，谢谢。

**Comment by Jeff-sjtu** [comment]
是的，如果想使用coco形式的keypoint输出，可以复制前17个卷积核的权重。

**Comment by hcsearch** [comment]
谢谢，我又想了下，感觉又有点迷糊了，其实我是这样意思，我想再加入一些其它场景的数据来训练，比如官方的模型在有些特定的场景下表现不太好，所以我就加入这些特定场景的数据来再次训练，不过我也不会在17个卷积核后面再加自己的网络结构，这样的话可不可以，如果可以，会不会把你们的结果反而训练得越来越差。还有就是，如果不这样做，冻结了你们的网络权重，再训练是不是需要添加自己的网络结构才行，然感觉这种情况好像又行不通，因为已经17个输出了，是这样吗？

**Comment by Jeff-sjtu** [comment]
具体表现跟你加入的数据有关，你可以将数据的coco的数据融合到一起来训练模型。没有必要再加自己的网络结构

**Comment by ZhongXiaoFang** [comment]
Jeff-sjtu，你好，那我训练的时候用33hw的网络，该再哪里设置参数呢？

**Comment by ZhongXiaoFang** [comment]
我训练的使用了17hw大小的网络，测试的时候将AlphaPose目录下的op.py文件中的‘nClasses‘的默认值由33改成17以后，测试demo可以运行，但是没有任何检测出结果，这是怎么回事呢

**Comment by Jeff-sjtu** [comment]
请问模型训练时的精度有多高？可能是没训练好

**Comment by hcsearch** [comment]
> Jeff-sjtu，你好，那我训练的时候用33hw的网络，该再哪里设置参数呢？

从代码上来看应该没有设置的地方，需要改代码才行。

**Comment by hcsearch** [comment]
这个你要问作者了，代码还没有看得很仔细，很多细节也还不太清楚，不过应该是在准备数据集，也就是生成输入图像数据与gt heatmap的时候有判断是哪个数据集，如果是coco就按coco来，如果是mpii就按mpii来，输出维度目前的训练代码网络输出默认是17，你如果想是33，修改一下输出维度应该就可以了，对应的你的输入数据也应该改成33维度。

**Comment by ZhongXiaoFang** [comment]
好的， 谢谢你们热情积极的回复 ，给你们点个赞@Jeff-sjtu @hcsearch

**Comment by konglongteng** [comment]
> 这个问题我刚才也遇到了，我训练了coco train2017，目前来说，效果还不是很好，还检测不出来任何骨骼点（我的训练次数还不多，目前只是跑下流程）。
> 不过目前有四个问题：
> 一：官方的输出分类是33，这个33是怎么回事？33个骨骼点吗？因为在coco上面是17个输出分类，所以在预测的时候我修改了输出分类为17，这样便可正常运行起来。不过我依然不太了解33是怎么回事？
> 二：在训练的时候官方batchsize为128，一运行的时候就出现的out of memony,所以我修改了batchsize为32才在我的机器上跑起来，官方是怎么在batchsize为128上跑起来的呢？ 难道是用很多内存撑起来的吗？
> 三：训练的readme上面说的第三种情况，可在预训练模式上面再训练，但是现在的输出分类数不一样，一个是17，一个预训练模型的33分类，这样看似应该就训练不起来，因为输出维度都不一样。是这样吗？
> 四：预训练模型的输出是33类别，在预测的时候，我保存了最后的预测图，看上去好像也只有17个heatmap的结果，这又是怎么回事呢？
> 这是我遇到的问题，如有错误的地方还请包涵，谢过。

您好，请问有训练的教程吗？
