### ISSUE TITLE
why does  "No module named numpy" problem occurred?

### ISSUE THREAD

**Issue by silencezx** [MVIG-SJTU/AlphaPose#146]
when i run the following code:./run.sh --indir examples/demo/ --outdir examples/results/ --vis
then generate the following mistaken.But i have already install the numpy1.14.0 model. how should i do?

generating bbox from Faster RCNN...
Traceback (most recent call last):
  File "demo-alpha-pose.py", line 19, in <module>
    from model.config import cfg
  File "/home/zhangxing/Desktop/AlphaPose/human-detection/tools/../lib/model/__init__.py", line 1, in <module>
    from . import config
  File "/home/zhangxing/Desktop/AlphaPose/human-detection/tools/../lib/model/config.py", line 7, in <module>
    import numpy as np
ImportError: No module named numpy
pose estimation with RMPE...
./run.sh: line 78: th: command not found
Traceback (most recent call last):
  File "parametric-pose-nms-MPII.py", line 9, in <module>
    import numpy as np
ImportError: No module named numpy
visualization...
Traceback (most recent call last):
  File "json-video.py", line 3, in <module>
    import numpy as np
ImportError: No module named numpy

**Comment by Fang-Haoshu** [comment]
try pip2 install
