### ISSUE TITLE
run demo.py erro

### ISSUE THREAD

**Issue by chenxu93** [MVIG-SJTU/AlphaPose#147]
HI,I want to get a quic kstart this demo but I got such error when run:
python demo.py --indir examples/demo --outdir examples/res_imgs

=====================================
/usr/local/lib/python3.6/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 37, in <module>
    import _tkinter
ModuleNotFoundError: No module named '_tkinter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo.py", line 11, in <module>
    from dataloader import ImageLoader, DetectionLoader, DetectionProcessor, DataWriter, Mscoco
  File "/home/HumanPose/AlphaPose/dataloader.py", line 7, in <module>
    from SPPE.src.utils.img import load_image, cropBox, im_to_torch
  File "/home/HumanPose/AlphaPose/SPPE/src/utils/img.py", line 10, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/backends/backend_tkagg.py", line 4, in <module>
    from . import tkagg  # Paint image to Tk photo blitter extension.
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/backends/tkagg.py", line 5, in <module>
    from six.moves import tkinter as Tk
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 92, in __get__
    result = self._resolve()
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 39, in <module>
    raise ImportError(str(msg) + ', please install the python3-tk package')
ImportError: No module named '_tkinter', please install the python3-tk package
==================================================
the res_imgs folder is created by my self.
I have try apt-get install python3-tk  and  it successfully.
how can I  do with this error？can someone help me?

**Comment by Jeff-sjtu** [comment]
try re-install matplotlib may help
