### ISSUE TITLE
multiprocess time question

### ISSUE THREAD

**Issue by cswwp** [MVIG-SJTU/AlphaPose#167]
I have test this project with demo, and i find that the multiprocess DetectionLoader.start time > DetectionLoader update time, 
my datalen = 90, det batchsize= 10, DetectionLoader.start time =5.57s(10 batchs), but the update time for one batch is just 0.4, i don't know why this phenomenon, anyone help me?

**Comment by cswwp** [comment]
i find that pytorch single process(det_loader.start time 0.00035) is faster than multi-process(det_loader.start time 5.853 s), i don't know why, anyone help me?

**Comment by xiaoweiChen** [comment]
Maybe, the multi-process data synchronization need more time. And python multi-Thread and multi-process is not faster than the single one, just according to my personal experience.

**Comment by xiaoweiChen** [comment]
@cswwp Great! I forgot the sleep operation, you mentioned that. And I will try your way. Thanks!

**Comment by Tylerjoe** [comment]
@cswwp @xiaoweiChen I can't use multiprocess, which version of opencv have you used?

**Comment by xiaoweiChen** [comment]
@Tylerjoe Can show your error information and your running environment? 
OpenCV version may not effect multiprocess.

**Comment by Tylerjoe** [comment]
@xiaoweiChen this is my develop environment: centos7.2，python3.6，opencv3.4.3，pytorch0.4

**Comment by cswwp** [comment]
@Tylerjoe I think Multi-process have nothing to do with opencv

**Comment by xiaoweiChen** [comment]
en.... I think the environment is good.
Please show your command line for execuating AlphaPose.
And show the error log for us. 

The more info will help the issue resolved quickly.

**Comment by Tylerjoe** [comment]
@xiaoweiChen > en.... I think the environment is good.
> Please show your command line for execuating AlphaPose.
> And show the error log for us.
> 
> The more info will help the issue resolved quickly.

This is the command i used(without --sp)
python3 video_demo.py --video examples/demo/1.mp4 --outdir examples/res/ --save_video

The log is like the following:
Traceback (most recent call last):
  File "video_demo.py", line 41, in <module>
    data_loader = VideoLoader(videofile, batchSize=args.detbatch).start()
  File "/data/download/projects/AlphaPose_pytorch_origin/dataloader.py", line 214, in start
    p.start()
  File "/root/anaconda3/envs/pytorch/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/multiprocessing/context.py", line 291, in _Popen
    return Popen(process_obj)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/multiprocessing/popen_forkserver.py", line 35, in __init__
    super().__init__(process_obj)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/multiprocessing/popen_forkserver.py", line 47, in _launch
    reduction.dump(process_obj, buf)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle cv2.VideoCapture objects

**Comment by xiaoweiChen** [comment]
ref #101 
Add "del self.stream" at line 194 in "dataloader.py".

the same issue : #197 #164

**Comment by Tylerjoe** [comment]
> ref #101
> Add "del self.stream" at line 194 in "dataloader.py".
> 
> if this way is not work and you can not deal it with yourself, you should add --sp option.
> the offical developers not said this issue has been solved.
> 
> the same issue : #197 #164

Thanks!
Add "del self.stream" at line 194 in "dataloader.py" means the project can't load the video stream anymore, so it could not solve this problem;
it may be a problem from opencv3.4, which version of opencv have you used?
Thanks!

**Comment by xiaoweiChen** [comment]
https://github.com/MVIG-SJTU/AlphaPose/issues/164#issuecomment-430567210

Maybe, the same suituation with you. 
You can try opencv 2.4.x. 

Because the multi-process will occupy almost computing and memory sources on my server, so I use the singal-process demo run the predict.

**Comment by dongminglin** [comment]
@Tylerjoe Do you have solved this problem that can't use the multiprocessing ,I have the same question as you, i want to know how to deal with it ,THANK YOU!

**Comment by Tylerjoe** [comment]
> @Tylerjoe Do you have solved this problem that can't use the multiprocessing ,I have the same question as you, i want to know how to deal with it ,THANK YOU!

I have not solved this problem, and I have tried another skeleton extract method

**Comment by Night-chen1** [comment]
> > @Tylerjoe Do you have solved this problem that can't use the multiprocessing ,I have the same question as you, i want to know how to deal with it ,THANK YOU!
> 
> I have not solved this problem, and I have tried another skeleton extract method

Have you tried other versions of opencv yet?
