### ISSUE TITLE
Failed to run demo

### ISSUE THREAD

**Issue by codemarsyu** [MVIG-SJTU/AlphaPose#17]
I think I have installed the package correctly! I am working on Ubuntu 16.04, TF-gpu v1.4. I literally follow the instruction of installation. But when I ran the demo:
`./run.sh --indir examples/demo/ --outdir examples/results/ --vis
`
I found error message here when the code tried to create a local save:

> /home/ruoyuli/torch/install/bin/luajit: /home/ruoyuli/.luarocks/share/lua/5.1/hdf5/file.lua:10: HDF5File.__init() requires a fileID - perhaps you want HDF5File.create()?
stack traceback:
	[C]: in function 'assert'
	/home/ruoyuli/.luarocks/share/lua/5.1/hdf5/file.lua:10: in function '__init'
	/home/ruoyuli/.luarocks/share/lua/5.1/torch/init.lua:91: in function </home/ruoyuli/.luarocks/share/lua/5.1/torch/init.lua:87>
	[C]: in function 'open'
	/home/ruoyuli/AlphaPose/predict/util.lua:34: in function 'loadAnnotations'
	main-alpha-pose.lua:27: in main chunk
	[C]: in function 'dofile'
	...yuli/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
/home/ruoyuli/.conda/envs/tf_p2.7/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "parametric-pose-nms-MPII.py", line 256, in <module>
    get_result_json(args)
  File "parametric-pose-nms-MPII.py", line 243, in get_result_json
    test_parametric_pose_NMS_json(delta1, delta2, mu, gamma,args.outputpath)
  File "parametric-pose-nms-MPII.py", line 99, in test_parametric_pose_NMS_json
    h5file = h5py.File(os.path.join(outputpath,"POSE/test-pose.h5"), 'r')
  File "/home/ruoyuli/.conda/envs/tf_p2.7/lib/python2.7/site-packages/h5py/_hl/files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/ruoyuli/.conda/envs/tf_p2.7/lib/python2.7/site-packages/h5py/_hl/files.py", line 99, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
IOError: Unable to open file (unable to open file: name = '/home/ruoyuli/AlphaPose/examples/results/POSE/test-pose.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
visualization...
Traceback (most recent call last):
  File "json-video.py", line 63, in <module>
    with open(jsonpath) as f:
IOError: [Errno 2] No such file or directory: '/home/ruoyuli/AlphaPose/examples/results/POSE/alpha-pose-results-forvis.json'

Any suggestions ? Thank you ahead!

**Comment by Fang-Haoshu** [comment]
Hi, can you paste the full screenshot of the result? Thanks.

**Comment by sunsinejust** [comment]
Hello, I can't run the demo too. The result looks like:
`XX::~/AlphaPose$ ./run.sh --indir examples/demo/ --outdir examples/results/ --gpu 0,1,2,3 --batch 5
0
generating bbox from Faster RCNN...
2018-02-14 15:50:23.741917: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-02-14 15:50:23.741941: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-02-14 15:50:23.741946: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-02-14 15:50:23.741950: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-02-14 15:50:23.741954: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2018-02-14 15:50:23.976259: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties: 
name: TITAN X (Pascal)
major: 6 minor: 1 memoryClockRate (GHz) 1.531
pciBusID 0000:06:00.0
Total memory: 11.90GiB
Free memory: 11.29GiB
2018-02-14 15:50:24.133633: W tensorflow/stream_executor/cuda/cuda_driver.cc:523] A non-primary context 0x3fe2bc0 exists before initializing the StreamExecutor. We haven't verified StreamExecutor works with that.
2018-02-14 15:50:24.134315: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 1 with properties: 
name: TITAN X (Pascal)
major: 6 minor: 1 memoryClockRate (GHz) 1.531
pciBusID 0000:0b:00.0
Total memory: 11.90GiB
Free memory: 11.75GiB
2018-02-14 15:50:24.135003: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0 1 
2018-02-14 15:50:24.135014: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y Y 
2018-02-14 15:50:24.135018: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 1:   Y Y 
2018-02-14 15:50:24.135032: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: TITAN X (Pascal), pci bus id: 0000:06:00.0)
2018-02-14 15:50:24.135039: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:1) -> (device: 1, name: TITAN X (Pascal), pci bus id: 0000:0b:00.0)
Loaded network ../output/res152/coco_2014_train+coco_2014_valminusminival/default/res152.ckpt
/home/icl/AlphaPose/examples/demo/

100%|████████████████████████████████████████████████████████| 3/3 [00:03<00:00,  1.18s/it]
pose estimation with RMPE...
/home/icl/torch/install/bin/lua: /home/icl/torch/install/share/lua/5.2/trepl/init.lua:389: /home/icl/torch/install/share/lua/5.2/trepl/init.lua:389: module 'bit' not found:No LuaRocks module found for bit
	no field package.preload['bit']
	no file '/home/icl/.luarocks/share/lua/5.2/bit.lua'
	no file '/home/icl/.luarocks/share/lua/5.2/bit/init.lua'
	no file '/home/icl/torch/install/share/lua/5.2/bit.lua'
	no file '/home/icl/torch/install/share/lua/5.2/bit/init.lua'
	no file '/home/icl/.luarocks/share/lua/5.1/bit.lua'
	no file '/home/icl/.luarocks/share/lua/5.1/bit/init.lua'
	no file '/home/icl/torch/install/share/lua/5.1/bit.lua'
	no file '/home/icl/torch/install/share/lua/5.1/bit/init.lua'
	no file './bit.lua'
	no file '/home/icl/torch/install/share/luajit-2.1.0-beta1/bit.lua'
	no file '/usr/local/share/lua/5.1/bit.lua'
	no file '/usr/local/share/lua/5.1/bit/init.lua'
	no file '/home/icl/.luarocks/lib/lua/5.2/bit.so'
	no file '/home/icl/torch/install/lib/lua/5.2/bit.so'
	no file '/home/icl/torch/install/lib/bit.so'
	no file '/home/icl/.luarocks/lib/lua/5.1/bit.so'
	no file '/home/icl/torch/install/lib/lua/5.1/bit.so'
	no file './bit.so'
	no file '/usr/local/lib/lua/5.1/bit.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'error'
	/home/icl/torch/install/share/lua/5.2/trepl/init.lua:389: in function 'require'
	/home/icl/AlphaPose/predict/util.lua:7: in main chunk
	[C]: in function 'dofile'
	/home/icl/torch/install/share/lua/5.2/paths/init.lua:84: in function 'dofile'
	main-alpha-pose.lua:7: in main chunk
	[C]: in function 'dofile'
	.../icl/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: in ?
Traceback (most recent call last):
  File "parametric-pose-nms-MPII.py", line 256, in <module>
    get_result_json(args)
  File "parametric-pose-nms-MPII.py", line 243, in get_result_json
    test_parametric_pose_NMS_json(delta1, delta2, mu, gamma,args.outputpath)
  File "parametric-pose-nms-MPII.py", line 99, in test_parametric_pose_NMS_json
    h5file = h5py.File(os.path.join(outputpath,"POSE/test-pose.h5"), 'r')
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 272, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 92, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-4rPeHA-build/h5py/_objects.c:2684)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-4rPeHA-build/h5py/_objects.c:2642)
  File "h5py/h5f.pyx", line 76, in h5py.h5f.open (/tmp/pip-4rPeHA-build/h5py/h5f.c:1930)
IOError: Unable to open file (Unable to open file: name = '/home/icl/alphapose/examples/results/pose/test-pose.h5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)
`
I try to google it. But there is no module named "bit"... Module "bit32" have been installed with lua2.
So.. Could anyone give any suggestion? 
Many thanks~

**Comment by whitelok** [comment]
@codemarsyu fixed. it works for me following: https://github.com/deepmind/torch-hdf5/issues/81

**Comment by whitelok** [comment]
P.S this project is using an old version of hdf5 1.8.*. So if you downgrade the hdf5, many problems can become more easier.
