### ISSUE TITLE
RuntimeError: Cannot pickle CUDA storage

### ISSUE THREAD

**Issue by xingyueyaohui** [MVIG-SJTU/AlphaPose#182]
When I run the demo by "python demo.py --indir indir --outdir outdir", an error occurred.
``
Traceback (most recent call last):
  File "demo.py", line 51, in <module>
    det_loader = DetectionLoader(data_loader, batchSize=args.detbatch).start()
  File "/home/pzq/AlphaPose-pytorch/dataloader.py", line 308, in start
    p.start()
  File "/home/pzq/anaconda3/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/home/pzq/anaconda3/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/pzq/anaconda3/lib/python3.6/multiprocessing/context.py", line 291, in _Popen
    return Popen(process_obj)
  File "/home/pzq/anaconda3/lib/python3.6/multiprocessing/popen_forkserver.py", line 35, in __init__
    super().__init__(process_obj)
  File "/home/pzq/anaconda3/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/pzq/anaconda3/lib/python3.6/multiprocessing/popen_forkserver.py", line 47, in _launch
    reduction.dump(process_obj, buf)
  File "/home/pzq/anaconda3/lib/python3.6/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "/home/pzq/.local/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 179, in reduce_storage
    raise RuntimeError("Cannot pickle CUDA storage; try pickling a CUDA tensor instead")
RuntimeError: Cannot pickle CUDA storage; try pickling a CUDA tensor instead
/home/pzq/anaconda3/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))

``
I think the main problem is "RuntimeError: Cannot pickle CUDA storage; try pickling a CUDA tensor instead"
The only modification to the code is that I add "os.environ["CUDA_VISIBLE_DEVICES"] = "1,2,3" " in the main function of demo.py

I really appreciate any kind of help!

**Comment by xingyueyaohui** [comment]
By the way, I guess it may be a pytorch 0.4.0 problem, but is it possible to solve it?

**Comment by xingyueyaohui** [comment]
By the way, my pytorch is 0.4.1, is the problem caused by the version?

**Comment by Fang-Haoshu** [comment]
Oh yes, 0.4.1 has a bug. Please use 0.4.0 instead

**Comment by ll490187880** [comment]
> Oh yes, 0.4.1 has a bug. Please use 0.4.0 instead

How to fix the bug in 0.4.1?

**Comment by chenxp106** [comment]
您好，请问解决这个问题了吗？

**Comment by chenxp106** [comment]
我也遇到了这个问题

**Comment by ziqipang** [comment]
> 您好，请问解决这个问题了吗？

It seems torch0.4.1 just cannot run successfully.  You can create a virtual environment specially for alpha-pose, which has torch 0.4.0, then run it.

**Comment by chenxp106** [comment]
ok,perfect

**Comment by BaiqiangGit** [comment]
Using:
-- pytorch 1.0.1
-- torchvision 0.2.1

And it works when running:
python demo.py --indir examples/demo  --outdir examples/res

**Comment by ynuwm** [comment]
I also encounter this problem.
