### ISSUE TITLE
训练时validation accuracy极低

### ISSUE THREAD

**Issue by FoolishMao** [MVIG-SJTU/AlphaPose#188]
训练参数为batch size=64； learning rate=1e-4 adam
训练到10epoch，validation acc到0.55后。train acc持续上升，而validation acc突然减小至不到0.1且随着训练validation acc会继续下降。请问我的训练参数该如何调整？

**Comment by xiaoweiChen** [comment]
和我的情况类似，val的准确度很不稳定。

我的命令行:
~/AlphaPose/train_sppe/src$ python train.py --dataset coco --expID exp1 --nClasses 17 --LR 1e-4 --nThreads 2 --trainBatch 16


```
############# Starting Epoch 46 #############
loss: 0.00061591 | acc: 79.24: 100%|████████████████████████████████████████████████████████████████████████████████████████████| 8646/8646 [53:46<00:00,  2.79it/s]
Train-46 epoch | loss:0.00061591 | acc:0.7924
loss: 0.00108763 | acc: 32.53: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 246/246 [01:39<00:00,  3.32it/s]
Valid-46 epoch | loss:0.00108763 | acc:0.3253
############# Starting Epoch 47 #############
loss: 0.00061362 | acc: 79.37: 100%|████████████████████████████████████████████████████████████████████████████████████████████| 8646/8646 [53:45<00:00,  3.03it/s]
Train-47 epoch | loss:0.00061362 | acc:0.7937
loss: 0.00101509 | acc: 42.22: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 246/246 [01:50<00:00,  2.87it/s]
Valid-47 epoch | loss:0.00101509 | acc:0.4222
############# Starting Epoch 48 #############
loss: 0.00061057 | acc: 79.55: 100%|████████████████████████████████████████████████████████████████████████████████████████████| 8646/8646 [54:43<00:00,  3.18it/s]
Train-48 epoch | loss:0.00061057 | acc:0.7955
loss: 0.00119161 | acc: 0.18: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 246/246 [01:41<00:00,  3.28it/s]
Valid-48 epoch | loss:0.00119161 | acc:0.0018
############# Starting Epoch 49 #############
loss: 0.00060797 | acc: 79.77: 100%|████████████████████████████████████████████████████████████████████████████████████████████| 8646/8646 [55:58<00:00,  3.21it/s]
Train-49 epoch | loss:0.00060797 | acc:0.7977
loss: 0.00102663 | acc: 41.17: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 246/246 [01:50<00:00,  2.93it/s]
Valid-49 epoch | loss:0.00102663 | acc:0.4117
```

**Comment by Sierkinhane** [comment]
你们的模型训练了多久？

**Comment by xiaoweiChen** [comment]
@Sierkinhane  我训了50个epoch，训练脚本默认的次数，coco 2017数据集，3天时间，用1080 ti

**Comment by SivanKe** [comment]
I'm having a similar problem, which consists even when I decrease learning rate.
Any chance that you have any news?

**Comment by yashupian** [comment]
训练sppe时遇到下面问题：
############# Starting Epoch 0 #############
  0%|                                                  | 0/1081 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 210, in <module>
    main()
  File "train.py", line 168, in main
    loss, acc = train(train_loader, m, criterion, optimizer, writer)
  File "train.py", line 27, in train
    for i, (inps, labels, setMask, imgset) in enumerate(train_loader_desc):
  File "/usr/local/lib/python3.5/dist-packages/tqdm/_tqdm.py", line 1022, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
FileNotFoundError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 57, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/smartcity/AlphaPose/train_sppe/src/utils/dataset/coco.py", line 69, in __getitem__
    'coco', sf, self, train=self.is_train)
  File "/home/smartcity/AlphaPose/train_sppe/src/utils/pose.py", line 19, in generateSampleBox
    img = load_image(img_path)
  File "/home/smartcity/AlphaPose/train_sppe/src/utils/img.py", line 39, in load_image
    return im_to_torch(scipy.misc.imread(img_path, mode='RGB'))
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "/usr/local/lib/python3.5/dist-packages/scipy/misc/pilutil.py", line 164, in imread
    im = Image.open(name)
  File "/usr/local/lib/python3.5/dist-packages/PIL/Image.py", line 2634, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '../data/coco/images/000000554886.jpg'
我是按照train-sppe中readme一步步操作的，请问你们训练是有遇到吗？

**Comment by yashupian** [comment]
训练sppe时遇到的错误：
 ############# Starting Epoch 0 #############
  0%|                                                  | 0/1081 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 210, in <module>
    main()
  File "train.py", line 168, in main
    loss, acc = train(train_loader, m, criterion, optimizer, writer)
  File "train.py", line 27, in train
    for i, (inps, labels, setMask, imgset) in enumerate(train_loader_desc):
  File "/usr/local/lib/python3.5/dist-packages/tqdm/_tqdm.py", line 1022, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 57, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/smartcity/AlphaPose/train_sppe/src/utils/dataset/coco.py", line 68, in __getitem__
    metaData = generateSampleBox(img_path, bndbox, part, self.nJoints,'coco', sf, self, train=self.is_train)
  File "/home/smartcity/AlphaPose/train_sppe/src/utils/pose.py", line 109, in generateSampleBox
    inp = cropBox(img, upLeft, bottomRight, inputResH, inputResW)
  File "/home/smartcity/AlphaPose/train_sppe/src/utils/img.py", line 140, in cropBox
    pad_size = [(lenH - box_shape[0]) // 2, (lenW - box_shape[1]) // 2]
TypeError: unsupported operand type(s) for //: 'Tensor' and 'int'
请问有人遇到过吗？

**Comment by liuchanfeng165** [comment]
“是pytorch由于cudnn加速bn层的原因，取消掉就好了。”
是屏蔽掉bn层吗？
哪位试了有效？比较需要花费3天时间啊。

**Comment by GuoHaiYang123** [comment]
请问具体怎么取消cudnn加速bn层啊？ @FoolishMao

**Comment by viva-Ia-vida** [comment]
> pad_size = [(lenH - box_shape[0]) // 2, (lenW - box_shape[1]) // 2]

将//换成/,可能是python版本原因

**Comment by liyupeng-ing** [comment]
@xiaoweiChen Maybe this is a problem of Adam, change to SGD for a try.
