### ISSUE TITLE
I meet a error which I can't understand such as  x = x.cuda(async=True)!!!

### ISSUE THREAD

**Issue by ZJsonJun** [MVIG-SJTU/AlphaPose#200]
$ python3 webcam_demo.py --vis
Traceback (most recent call last):
  File "webcam_demo.py", line 11, in <module>
    from dataloader_webcam import WebcamLoader, DetectionLoader, DetectionProcessor, DataWriter, crop_from_dets, Mscoco
  File "D:\AlphaPose\AlphaPose\dataloader_webcam.py", line 7, in <module>
    from SPPE.src.utils.img import load_image, cropBox, im_to_torch
  File "D:\AlphaPose\AlphaPose\SPPE\src\utils\img.py", line 285
    x = x.cuda(async=True)
                   ^
SyntaxError: invalid syntax

**Comment by xiaoweiChen** [comment]
same as #205
