### ISSUE TITLE
problem when run run.sh

### ISSUE THREAD

**Issue by linchaozhang** [MVIG-SJTU/AlphaPose#22]
Unable to open file: name = '/home/zlc/network/alphapose/examples/results/pose/test-pose.h5
IOError: [Errno 2] No such file or directory: '/home/zlc/Network/AlphaPose/examples/results/POSE/alpha-pose-results-forvis.json'
when i run  './run.sh --indir examples/demo/ --outdir examples/results/ --vis', i don't know where can i find these two files.

**Comment by ChangQF** [comment]
did you use the examples pics? 
the reason may be something wrong in generating bbox, more information is needed

**Comment by linchaozhang** [comment]
yes, i use the examples pics, didn't change any more @ChangQF

**Comment by ChangQF** [comment]
there must be error before "Unable to open file: name = '/home/zlc/network/alphapose/examples/results/pose/test-pose.h5". could you give more info?@linchaozhang

**Comment by Fang-Haoshu** [comment]
Yes, can you please paste the full screenshot? And you can also please refer to some closed issue like #3 or #7.

**Comment by gostop112111** [comment]
I have the same problem！

pose estimation with RMPE...
./run.sh: line 78: th: command not found
Traceback (most recent call last):
  File "parametric-pose-nms-MPII.py", line 256, in <module>
    get_result_json(args)
  File "parametric-pose-nms-MPII.py", line 243, in get_result_json
    test_parametric_pose_NMS_json(delta1, delta2, mu, gamma,args.outputpath)
  File "parametric-pose-nms-MPII.py", line 99, in test_parametric_pose_NMS_json
    h5file = h5py.File(os.path.join(outputpath,"POSE/test-pose.h5"), 'r')
  File "/usr/lib64/python2.7/site-packages/h5py/_hl/files.py", line 272, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/lib64/python2.7/site-packages/h5py/_hl/files.py", line 92, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-4rPeHA-build/h5py/_objects.c:2684)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-4rPeHA-build/h5py/_objects.c:2642)
  File "h5py/h5f.pyx", line 76, in h5py.h5f.open (/tmp/pip-4rPeHA-build/h5py/h5f.c:1930)
IOError: Unable to open file (Unable to open file: name = '/opt/xx/alphapose/examples/results/pose/test-pose.h5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)
visualization...
Traceback (most recent call last):
  File "json-video.py", line 63, in <module>
    with open(jsonpath) as f:
IOError: [Errno 2] No such file or directory: '/opt/xx/AlphaPose/examples/results/POSE/alpha-pose-results-forvis.json'

**Comment by Fang-Haoshu** [comment]
Hi, check the faq
