### ISSUE TITLE
/torch/install/bin/luajit: cannot open <models/final_model.t7> in mode r  at /tmp/luarocks_torch-scm-1-9354/torch7/lib/TH/THDiskFile.c:673

### ISSUE THREAD

**Issue by chenyuqing** [MVIG-SJTU/AlphaPose#221]
pose estimation with RMPE...
MPII	
/home/tim/torch/install/bin/luajit: cannot open <models/final_model.t7> in mode r  at /tmp/luarocks_torch-scm-1-9354/torch7/lib/TH/THDiskFile.c:673
stack traceback:
	[C]: at 0x7ff681561470
	[C]: in function 'DiskFile'
	/home/tim/torch/install/share/lua/5.1/torch/File.lua:405: in function 'load'
	main-alpha-pose.lua:94: in function 'loop'
	main-alpha-pose.lua:176: in main chunk
	[C]: in function 'dofile'
	.../tim/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
Traceback (most recent call last):
  File "parametric-pose-nms-MPII.py", line 257, in <module>
    get_result_json(args)
  File "parametric-pose-nms-MPII.py", line 244, in get_result_json
    test_parametric_pose_NMS_json(delta1, delta2, mu, gamma,args.outputpath)
  File "parametric-pose-nms-MPII.py", line 100, in test_parametric_pose_NMS_json
    h5file = h5py.File(os.path.join(outputpath,"POSE/test-pose.h5"), 'r')
  File "/home/tim/.local/lib/python2.7/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/home/tim/.local/lib/python2.7/site-packages/h5py/_hl/files.py", line 170, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 85, in h5py.h5f.open
IOError: Unable to open file (unable to open file: name = '/home/tim/AlphaPose/examples/results/POSE/test-pose.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by xiaoweiChen** [comment]
You should make sure the file exists in the right path. The error message:
> "IOError: Unable to open file (unable to open file: name = '/home/tim/AlphaPose/examples/results/POSE/test-pose.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)"

The program can not open the "test-pose.h5" file.

**Comment by yashkant** [comment]
Was this issue resolved, I am facing it too.
