### ISSUE TITLE
train.py error(pytorch version in windows)

### ISSUE THREAD

**Issue by maba3103** [MVIG-SJTU/AlphaPose#262]
When I run train.py, getting this error.
$ python train.py --dataset coco --expID exp1 --nClasses 17 --LR 1e-4

Create new model
############# Starting Epoch 0 #############
0%|          | 0/1083 [00:00<?, ?it/s]

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\opex-PC07\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\opex-PC07\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\opex-PC07\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\opex-PC07\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\opex-PC07\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\opex-PC07\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\opex-PC07\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\opex-PC07\Documents\AlphaPose\train_sppe\src\train.py", line 14, in <module>
    from evaluation import prediction
  File "C:\Users\opex-PC07\Documents\AlphaPose\train_sppe\src\evaluation.py", line 43, in <module>
    gaussian_kernel.cuda()
  File "C:\Users\opex-PC07\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 249, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "C:\Users\opex-PC07\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 182, in _apply
    param.data = fn(param.data)
  File "C:\Users\opex-PC07\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 249, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: cuda runtime error (2) : out of memory at C:/Users/Administrator/Downloads/new-builder/win-wheel/pytorch/aten/src/THC/THCTensorRandom.cu:25
THCudaCheck FAIL file=C:/Users/Administrator/Downloads/new-builder/win-wheel/pytorch/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
Traceback (most recent call last):
  File "train.py", line 210, in <module>
    main()
  File "train.py", line 168, in main
    loss, acc = train(train_loader, m, criterion, optimizer, writer)
  File "train.py", line 27, in train
    for i, (inps, labels, setMask, imgset) in enumerate(train_loader_desc):
  File "C:\Users\opex-PC07\AppData\Local\Programs\Python\Python36\lib\site-packages\tqdm\_tqdm.py", line 1000, in __iter__
    for obj in iterable:
  File "C:\Users\opex-PC07\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 451, in __iter__
    return _DataLoaderIter(self)
  File "C:\Users\opex-PC07\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 239, in __init__
    w.start()
  File "C:\Users\opex-PC07\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\opex-PC07\AppData\Local\Programs\Python\Python36\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\opex-PC07\AppData\Local\Programs\Python\Python36\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\opex-PC07\AppData\Local\Programs\Python\Python36\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\opex-PC07\AppData\Local\Programs\Python\Python36\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe

So, I changed the batch size parameter, but the same error occured.
How do I solve it?

GPU:GTX1070 8GB
pytorch:0.4.0

**Comment by Fang-Haoshu** [comment]
Hi, it seems a bug of pytorch under windows. I suggest training the network under Linux platform

**Comment by Davvwvvid** [comment]
wow,I meet the same error, Do you solve this ?
