### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by jinfei3459** [MVIG-SJTU/AlphaPose#263]
训练的时候发生了错误
`python train.py --dataset coco --expID exp1 --nClasses 17 --LR 1e-4`
`Create new model
############# Starting Epoch 0 #############
  0%|                                                                                                    | 0/1081 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 210, in <module>
    main()
  File "train.py", line 167, in main
    loss, acc = train(train_loader, m, criterion, optimizer, writer)
  File "train.py", line 25, in train
    for i, (inps, labels, setMask, imgset) in enumerate(train_loader_desc):
  File "/usr/local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 933, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/data4/zjf/code/Pose-Estimation/AlphaPose-pytorch-v2/train_sppe/src/utils/dataset/coco.py", line 70, in __getitem__
    'coco', sf, self, train=self.is_train)
  File "/data4/zjf/code/Pose-Estimation/AlphaPose-pytorch-v2/train_sppe/src/utils/pose.py", line 109, in generateSampleBox
    inp = cropBox(img, upLeft, bottomRight, inputResH, inputResW)
  File "/data4/zjf/code/Pose-Estimation/AlphaPose-pytorch-v2/train_sppe/src/utils/img.py", line 140, in cropBox
    pad_size = [(lenH - box_shape[0]) // 2, (lenW - box_shape[1]) // 2]
TypeError: unsupported operand type(s) for //: 'Tensor' and 'int'
`
另外请问一下训练的数据集使用的是coco哪几个数据集呢

**Comment by jinfei3459** [comment]
我用的pytorch是0.4.0，python版本是3.6.5

**Comment by liudatutu** [comment]
@jinfei3459 请问训练代码是在哪里的呢？说明文档里只有用lua的训练，哪里有Python的啊？

**Comment by yashupian** [comment]
> 我用的pytorch是0.4.0，python版本是3.5 coco2017数据集请问你解决这个问题了吗？

**Comment by small-sky** [comment]
I have the same problem, how do you solve it ?

**Comment by KCHENPENGFEI** [comment]
python3.6要把//换成/

**Comment by Danelljian** [comment]
请问您能提供下coco json 转h5的文件或代码吗
