### ISSUE TITLE
Running demo error 

### ISSUE THREAD

**Issue by David3310273** [MVIG-SJTU/AlphaPose#264]
After running the command as follow
`./run.sh --indir examples/demo/ --outdir examples/results/ --vis`
`luarock install hdf5`
I got an error like this, I wonder which version of the hdf5 module should I install: 
`generating bbox from Faster RCNN...
/home/xinshen/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as "np.float64 == np.dtype(float).type".
  from ._conv import register_converters as _register_converters
2019-02-01 20:44:41.760221: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Loaded network ../output/res152/coco_2014_train+coco_2014_valminusminival/default/res152.ckpt
/home/xinshen/weiyuhui/AlphaPose/examples/demo/

100%|###########################################################################################################################| 3/3 [00:26<00:00,  8.87s/it]
pose estimation with RMPE...
/home/xinshen/torch/install/bin/luajit: /home/xinshen/torch/install/share/lua/5.1/trepl/init.lua:389: /home/xinshen/torch/install/share/lua/5.1/hdf5/ffi.lua:71: **Unsupported HDF5 version: 1.10.2**
stack traceback:
	[C]: in function 'error'
	/home/xinshen/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	/home/xinshen/weiyuhui/AlphaPose/predict/util.lua:7: in main chunk
	[C]: in function 'dofile'
	main-alpha-pose.lua:7: in main chunk
	[C]: in function 'dofile'
	...shen/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
/home/xinshen/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "parametric-pose-nms-MPII.py", line 257, in <module>
    get_result_json(args)
  File "parametric-pose-nms-MPII.py", line 244, in get_result_json
    test_parametric_pose_NMS_json(delta1, delta2, mu, gamma,args.outputpath)
  File "parametric-pose-nms-MPII.py", line 100, in test_parametric_pose_NMS_json
    h5file = h5py.File(os.path.join(outputpath,"POSE/test-pose.h5"), 'r')
  File "/home/xinshen/anaconda2/lib/python2.7/site-packages/h5py/_hl/files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/xinshen/anaconda2/lib/python2.7/site-packages/h5py/_hl/files.py", line 99, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
IOError: Unable to open file (unable to open file: name = '/home/xinshen/weiyuhui/AlphaPose/examples/results/POSE/test-pose.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
visualization...
Traceback (most recent call last):
  File "json-video.py", line 65, in <module>
    with open(jsonpath) as f:
IOError: [Errno 2] No such file or directory: '/home/xinshen/weiyuhui/AlphaPose/examples/results/POSE/alpha-pose-results-forvis.json'`

**Comment by liudatutu** [comment]
@David3310273 I have the same problem,do you fit it ?

**Comment by AishuaiYao** [comment]
> @David3310273 I have the same problem,do you fit it ?

哈哈哈，又是你
