### ISSUE TITLE
IOError: Unable to open file (Unable to open file: name = 'examples/results/pose/test-pose.h5'

### ISSUE THREAD

**Issue by ztwe** [MVIG-SJTU/AlphaPose#27]
@hjhhh3000 
The log of run is shown as following:

generating bbox from Faster RCNN...
Traceback (most recent call last):
  File "demo-alpha-pose.py", line 118, in <module>
    os.mkdir(args.outputpath)
OSError: [Errno 2] No such file or directory: 'examples/results/'
pose estimation with RMPE...
./run.sh: 行 78: th: 未找到命令
Traceback (most recent call last):
  File "parametric-pose-nms-MPII.py", line 256, in <module>
    get_result_json(args)
  File "parametric-pose-nms-MPII.py", line 243, in get_result_json
    test_parametric_pose_NMS_json(delta1, delta2, mu, gamma,args.outputpath)
  File "parametric-pose-nms-MPII.py", line 99, in test_parametric_pose_NMS_json
    h5file = h5py.File(os.path.join(outputpath,"POSE/test-pose.h5"), 'r')
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/files.py", line 272, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/files.py", line 92, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/build/h5py-nQFNYZ/h5py-2.6.0/h5py/_objects.c:2577)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/build/h5py-nQFNYZ/h5py-2.6.0/h5py/_objects.c:2536)
  File "h5py/h5f.pyx", line 76, in h5py.h5f.open (/build/h5py-nQFNYZ/h5py-2.6.0/h5py/h5f.c:1811)
IOError: Unable to open file (Unable to open file: name = 'examples/results/pose/test-pose.h5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)

**Comment by Fang-Haoshu** [comment]
problem already listed in faq. Closed
