### ISSUE TITLE
Failed when try to run demo on windows 10

### ISSUE THREAD

**Issue by aligoglos** [MVIG-SJTU/AlphaPose#279]
I try to run demo on windows 10 and python 3.5.4 but this error occur :
```
Loading YOLO model..
THCudaCheck FAIL file=c:\a\w\1\s\windows\pytorch\torch\csrc\generic\StorageSharing.cpp line=232 error=63 : OS call failed or operation not supported on this OS
Traceback (most recent call last):
  File "D:\Artificial Intelligence\HumanDetection_Tracking\AlphaPose-pytorch\AlphaPose-pytorch\demo.py", line 50, in <module>
    det_loader = DetectionLoader(data_loader, batchSize=args.detbatch).start()
  File "D:\Artificial Intelligence\HumanDetection_Tracking\AlphaPose-pytorch\AlphaPose-pytorch\dataloader.py", line 309, in start
    p.start()
  File "C:\Users\127051\AppData\Local\Programs\Python\Python35\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\127051\AppData\Local\Programs\Python\Python35\lib\multiprocessing\context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\127051\AppData\Local\Programs\Python\Python35\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "C:\Users\127051\AppData\Local\Programs\Python\Python35\lib\multiprocessing\popen_spawn_win32.py", line 66, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\127051\AppData\Local\Programs\Python\Python35\lib\multiprocessing\reduction.py", line 59, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "C:\Users\127051\AppData\Local\Programs\Python\Python35\lib\site-packages\torch\multiprocessing\reductions.py", line 213, in reduce_tensor
    (device, handle, storage_size_bytes, storage_offset_bytes) = storage._share_cuda_()
RuntimeError: cuda runtime error (63) : OS call failed or operation not supported on this OS at c:\a\w\1\s\windows\pytorch\torch\csrc\generic\StorageSharing.cpp:232

D:\Artificial Intelligence\HumanDetection_Tracking\AlphaPose-pytorch\AlphaPose-pytorch>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\127051\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\127051\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 116, in _main
    self = pickle.load(from_parent)
EOFError: Ran out of input
```
i think it's torch GPU error. Can I run AlphaPose on CPU?
i upgrade my torch with this command :(`pip3 install https://download.pytorch.org/whl/cu90/torch-1.0.1-cp35-cp35m-win_amd64.wh`l) but not differ.

**Comment by aligoglos** [comment]
Windows don't support multiprocessing
