### ISSUE TITLE
run.sh error

### ISSUE THREAD

**Issue by ytgcljj** [MVIG-SJTU/AlphaPose#292]
launchx-500-10802@launchx50010802:~/AlphaPose$ ./run.sh --indir examples/demo/ --outdir examples/results/ --vis
0
generating bbox from Faster RCNN...
Traceback (most recent call last):
  File "demo-alpha-pose.py", line 24, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcudnn.so.6: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
pose estimation with RMPE...
MPII	
/home/launchx-500-10802/torch/install/bin/luajit: ...nchx-500-10802/torch/install/share/lua/5.1/hdf5/file.lua:132: HDF5File.open: no such directory /home/launchx-500-10802/AlphaPose/examples/results/BBOX
stack traceback:
	[C]: in function 'error'
	...nchx-500-10802/torch/install/share/lua/5.1/hdf5/file.lua:132: in function 'open'
	/home/launchx-500-10802/AlphaPose/predict/util.lua:34: in function 'loadAnnotations'
	main-alpha-pose.lua:27: in main chunk
	[C]: in function 'dofile'
	...0802/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
Traceback (most recent call last):
  File "parametric-pose-nms-MPII.py", line 257, in <module>
    get_result_json(args)
  File "parametric-pose-nms-MPII.py", line 244, in get_result_json
    test_parametric_pose_NMS_json(delta1, delta2, mu, gamma,args.outputpath)
  File "parametric-pose-nms-MPII.py", line 100, in test_parametric_pose_NMS_json
    h5file = h5py.File(os.path.join(outputpath,"POSE/test-pose.h5"), 'r')
  File "/home/launchx-500-10802/.local/lib/python2.7/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/home/launchx-500-10802/.local/lib/python2.7/site-packages/h5py/_hl/files.py", line 170, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 85, in h5py.h5f.open
IOError: Unable to open file (unable to open file: name = '/home/launchx-500-10802/AlphaPose/examples/results/POSE/test-pose.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
visualization...
Traceback (most recent call last):
  File "json-video.py", line 65, in <module>
    with open(jsonpath) as f:
IOError: [Errno 2] No such file or directory: '/home/launchx-500-10802/AlphaPose/examples/results/POSE/alpha-pose-results-forvis.json'

**Comment by Fang-Haoshu** [comment]
ImportError: libcudnn.so.6: cannot open shared object file: No such file or directory
CUDNN problem
You can try the pytorch branch. It's easier to run.
