### ISSUE TITLE
train sppe时的问题

### ISSUE THREAD

**Issue by zerostan** [MVIG-SJTU/AlphaPose#294]
在重新训练SPPE的时候，训练过程中遇到了如下错误，根据错误的提示我也找不到到底是哪里出错，所以来请教一下（这个是训练了大概几秒中报的错）

>  ############# Starting Epoch 0 #############
loss: 0.01385714 | acc: 1.37:   0%|          | 14/8646 [00:34<1:36:31,  1.49it/s]
Traceback (most recent call last):
  File "/media/dip_image/08A60A7FA60A6E0E/XC/AlphaPose-pytorch/train_sppe/src/train.py", line 211, in <module>
    main()
  File "/media/dip_image/08A60A7FA60A6E0E/XC/AlphaPose-pytorch/train_sppe/src/train.py", line 169, in main
    loss, acc = train(train_loader, m, criterion, optimizer, writer)
  File "/media/dip_image/08A60A7FA60A6E0E/XC/AlphaPose-pytorch/train_sppe/src/train.py", line 27, in train
    for i, (inps, labels, setMask, imgset) in enumerate(train_loader_desc):
  File "/usr/local/lib/python3.5/dist-packages/tqdm/_tqdm.py", line 979, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 272, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 57, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/media/dip_image/08A60A7FA60A6E0E/XC/AlphaPose-pytorch/train_sppe/src/utils/dataset/coco.py", line 69, in __getitem__
    'coco', sf, self, train=self.is_train)
  File "/media/dip_image/08A60A7FA60A6E0E/XC/AlphaPose-pytorch/train_sppe/src/utils/pose.py", line 109, in generateSampleBox
    inp = cropBox(img, upLeft, bottomRight, inputResH, inputResW)
  File "/media/dip_image/08A60A7FA60A6E0E/XC/AlphaPose-pytorch/train_sppe/src/utils/img.py", line 143, in cropBox
    img[:, :ul[1], :] = 0
RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 2)

**Comment by Jeff-sjtu** [comment]
你好，请问你用的是什么版本的PyTorch

**Comment by zerostan** [comment]
> 你好，请问你用的是什么版本的PyTorch

用的是0.4.0

**Comment by Jeff-sjtu** [comment]
这个是旧版本PyTorch的bug，请使用0.4.1

**Comment by zerostan** [comment]
> 这个是旧版本PyTorch的bug，请使用0.4.1

那使用0.4.1的话demo就不能运行了

**Comment by Jeff-sjtu** [comment]
抱歉。训练得到的model应该是通用的。或者可以在img.py中，加入一个判断条件。这个bug主要是pytorch不支持空索引导致的。`mg[:, :ul[1], :] = 0`中，`ul[1]=0`就会报错。
BTW，你的代码似乎不是最新版本。

**Comment by zerostan** [comment]
> 抱歉。训练得到的model应该是通用的。或者可以在img.py中，加入一个判断条件。这个bug主要是pytorch不支持空索引导致的。`mg[:, :ul[1], :] = 0`中，`ul[1]=0`就会报错。
> BTW，你的代码似乎不是最新版本。

到目前为止SPPE的训练一直没有成功，我用0.4.1跑demo的时候是直接用下载的model，但是提示报错，查了一下是版本不对的问题，必须要用0.4.0，所以又用0.4.0的版本。如果不是最新的pytorch版本，最新0.4.1版本的pytorh应该在哪里可以找到？我在github上搜索alphapose，然后点pytorch version，请问这么找是不是正确的？

**Comment by viva-Ia-vida** [comment]
你好,我也遇到了这个问题,请问你解决了吗,需要升级pytorch版本吗

**Comment by jiajiajun** [comment]
你好，我用pytorch0.4.0训练SPPE的时候也遇到了这个问题,请问是怎么解决的呢？
