### ISSUE TITLE
alpha-pose-results-forvis.json

### ISSUE THREAD

**Issue by lucheng07082221** [MVIG-SJTU/AlphaPose#3]
this file(alpha-pose-results-forvis.json) can not find

**Comment by Fang-Haoshu** [comment]
Hi, can you paste the command and screen shot of the result?

**Comment by lucheng07082221** [comment]
generating bbox from Faster RCNN...
Traceback (most recent call last):
  File "demo-alpha-pose.py", line 24, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcudnn.so.6: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
pose estimation with RMPE...
/home/lc/torch/install/bin/luajit: /home/lc/torch/install/share/lua/5.1/trepl/init.lua:389: module 'hdf5' not found:No LuaRocks module found for hdf5
	no field package.preload['hdf5']
	no file '/home/lc/.luarocks/share/lua/5.1/hdf5.lua'
	no file '/home/lc/.luarocks/share/lua/5.1/hdf5/init.lua'
	no file '/home/lc/torch/install/share/lua/5.1/hdf5.lua'
	no file '/home/lc/torch/install/share/lua/5.1/hdf5/init.lua'
	no file './hdf5.lua'
	no file '/home/lc/torch/install/share/luajit-2.1.0-beta1/hdf5.lua'
	no file '/usr/local/share/lua/5.1/hdf5.lua'
	no file '/usr/local/share/lua/5.1/hdf5/init.lua'
	no file '/home/lc/.luarocks/lib/lua/5.1/hdf5.so'
	no file '/home/lc/torch/install/lib/lua/5.1/hdf5.so'
	no file '/home/lc/torch/install/lib/hdf5.so'
	no file './hdf5.so'
	no file '/usr/local/lib/lua/5.1/hdf5.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'error'
	/home/lc/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	/home/lc/Downloads/AlphaPose/predict/util.lua:7: in main chunk
	[C]: in function 'dofile'
	main-alpha-pose.lua:7: in main chunk
	[C]: in function 'dofile'
	...e/lc/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
Traceback (most recent call last):
  File "parametric-pose-nms-MPII.py", line 256, in <module>
    get_result_json(args)
  File "parametric-pose-nms-MPII.py", line 243, in get_result_json
    test_parametric_pose_NMS_json(delta1, delta2, mu, gamma,args.outputpath)
  File "parametric-pose-nms-MPII.py", line 99, in test_parametric_pose_NMS_json
    h5file = h5py.File(os.path.join(outputpath,"POSE/test-pose.h5"), 'r')
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 272, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 92, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-4rPeHA-build/h5py/_objects.c:2684)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-4rPeHA-build/h5py/_objects.c:2642)
  File "h5py/h5f.pyx", line 76, in h5py.h5f.open (/tmp/pip-4rPeHA-build/h5py/h5f.c:1930)
IOError: Unable to open file (Unable to open file: name = '/home/lc/downloads/alphapose/examples/results/pose/test-pose.h5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)
visualization...
Traceback (most recent call last):
  File "json-video.py", line 63, in <module>
    with open(jsonpath) as f:
IOError: [Errno 2] No such file or directory: '/home/lc/Downloads/AlphaPose/examples/results/POSE/alpha-pose-results-forvis.json'

**Comment by lucheng07082221** [comment]
@Fang-Haoshu thank you for your reply. I have solved this problem, because i forgot to install hdf5

**Comment by Fang-Haoshu** [comment]
I see. Great!

**Comment by ujsyehao** [comment]
hdf5 installation steps:
`sudo apt-get install libhdf5-serial-dev hdf5-tools`
`luarocks install hdf5`

**Comment by linchaozhang** [comment]
how to install hdf5, when i use "luarocks install hdf5", 

Installing https://luarocks.org/hdf5-2.0.0-1.src.rock
Warning: variable CFLAGS was not passed in build_variables
make[1]: Entering directory '/tmp/luarocks_hdf5-2.0.0-1-U02nm7/lua-hdf5/gcc-lua'
make[2]: Entering directory '/tmp/luarocks_hdf5-2.0.0-1-U02nm7/lua-hdf5/gcc-lua/gcc'
gcclua-config.h:1:24: fatal error: gcc-plugin.h: No such file or directory
compilation terminated.
gcc -c -o gcclua.o -I/usr/lib/gcc/x86_64-linux-gnu/5/plugin/include -fPIC  -O2 -Wall -Wformat-security -I/usr/include/lua5.2 gcclua.c
gcclua.c:7:24: fatal error: gcc-plugin.h: No such file or directory
compilation terminated.
Makefile:29: recipe for target 'gcclua.o' failed
make[2]: *** [gcclua.o] Error 1
make[2]: Leaving directory '/tmp/luarocks_hdf5-2.0.0-1-U02nm7/lua-hdf5/gcc-lua/gcc'
Makefile:38: recipe for target 'gcc' failed
make[1]: *** [gcc] Error 2
make[1]: Leaving directory '/tmp/luarocks_hdf5-2.0.0-1-U02nm7/lua-hdf5/gcc-lua'
Makefile:44: recipe for target 'gcc-lua' failed
make: *** [gcc-lua] Error 2

Error: Build error: Failed building.

@Fang-Haoshu @lucheng07082221
