### ISSUE TITLE
demo出错

### ISSUE THREAD

**Issue by chenxp106** [MVIG-SJTU/AlphaPose#316]
之前还能跑通的demo，今天又不行了。我的版本pytorch4.0版本。然后一大串错
Traceback (most recent call last):
  File "demo.py", line 56, in <module>
    pose_model = InferenNet_fast(4 * 1 + 1, pose_dataset)
  File "/home/manager/cxp/code/AlphaPose-pytorch/SPPE/src/main_fast_inference.py", line 61, in __init__
    model.load_state_dict(torch.load('./models/sppe/duc_se.pth'))
  File "/home/manager/anaconda2/envs/cxpenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for FastPose:
	Missing key(s) in state_dict: "preact.bn1.num_batches_tracked", "preact.layer1.0.bn1.num_batches_tracked", "preact.layer1.0.bn2.num_batches_tracked", "preact.layer1.0.bn3.num_batches_tracked", "preact.layer1.0.downsample.1.num_batches_tracked", "preact.layer1.1.bn1.num_batches_tracked", "preact.layer1.1.bn2.num_batches_tracked", "preact.layer1.1.bn3.num_batches_tracked", "preact.layer1.2.bn1.num_batches_tracked", "preact.layer1.2.bn2.num_batches_tracked", "preact.layer1.2.bn3.num_batches_tracked", "preact.layer2.0.bn1.num_batches_tracked", "preact.layer2.0.bn2.num_batches_tracked", "preact.layer2.0.bn3.num_batches_tracked", "preact.layer2.0.downsample.1.num_batches_tracked", "preact.layer2.1.bn1.num_batches_tracked", "preact.layer2.1.bn2.num_batches_tracked", "preact.layer2.1.bn3.num_batches_tracked", "preact.layer2.2.bn1.num_batches_tracked", "preact.layer2.2.bn2.num_batches_tracked", "preact.layer2.2.bn3.num_batches_tracked", "preact.layer2.3.bn1.num_batches_tracked", "preact.layer2.3.bn2.num_batches_tracked", "preact.layer2.3.bn3.num_batches_tracked", "preact.layer3.0.bn1.num_batches_tracked", "preact.layer3.0.bn2.num_batches_tracked", "preact.layer3.0.bn3.num_batches_tracked", "preact.layer3.0.downsample.1.num_batches_tracked", "preact.layer3.1.bn1.num_batches_tracked", "preact.layer3.1.bn2.num_batches_tracked", "preact.layer3.1.bn3.num_batches_tracked", "preact.layer3.2.bn1.num_batches_tracked", "preact.layer3.2.bn2.num_batches_tracked", "preact.layer3.2.bn3.num_batches_tracked", "preact.layer3.3.bn1.num_batches_tracked", "preact.layer3.3.bn2.num_batches_tracked", "preact.layer3.3.bn3.num_batches_tracked", "preact.layer3.4.bn1.num_batches_tracked", "preact.layer3.4.bn2.num_batches_tracked", "preact.layer3.4.bn3.num_batches_tracked", "preact.layer3.5.bn1.num_batches_tracked", "preact.layer3.5.bn2.num_batches_tracked", "preact.layer3.5.bn3.num_batches_tracked", "preact.layer3.6.bn1.num_batches_tracked", "preact.layer3.6.bn2.num_batches_tracked", "preact.layer3.6.bn3.num_batches_tracked", "preact.layer3.7.bn1.num_batches_tracked", "preact.layer3.7.bn2.num_batches_tracked", "preact.layer3.7.bn3.num_batches_tracked", "preact.layer3.8.bn1.num_batches_tracked", "preact.layer3.8.bn2.num_batches_tracked", "preact.layer3.8.bn3.num_batches_tracked", "preact.layer3.9.bn1.num_batches_tracked", "preact.layer3.9.bn2.num_batches_tracked", "preact.layer3.9.bn3.num_batches_tracked", "preact.layer3.10.bn1.num_batches_tracked", "preact.layer3.10.bn2.num_batches_tracked", "preact.layer3.10.bn3.num_batches_tracked", "preact.layer3.11.bn1.num_batches_tracked", "preact.layer3.11.bn2.num_batches_tracked", "preact.layer3.11.bn3.num_batches_tracked", "preact.layer3.12.bn1.num_batches_tracked", "preact.layer3.12.bn2.num_batches_tracked", "preact.layer3.12.bn3.num_batches_tracked", "preact.layer3.13.bn1.num_batches_tracked", "preact.layer3.13.bn2.num_batches_tracked", "preact.layer3.13.bn3.num_batches_tracked", "preact.layer3.14.bn1.num_batches_tracked", "preact.layer3.14.bn2.num_batches_tracked", "preact.layer3.14.bn3.num_batches_tracked", "preact.layer3.15.bn1.num_batches_tracked", "preact.layer3.15.bn2.num_batches_tracked", "preact.layer3.15.bn3.num_batches_tracked", "preact.layer3.16.bn1.num_batches_tracked", "preact.layer3.16.bn2.num_batches_tracked", "preact.layer3.16.bn3.num_batches_tracked", "preact.layer3.17.bn1.num_batches_tracked", "preact.layer3.17.bn2.num_batches_tracked", "preact.layer3.17.bn3.num_batches_tracked", "preact.layer3.18.bn1.num_batches_tracked", "preact.layer3.18.bn2.num_batches_tracked", "preact.layer3.18.bn3.num_batches_tracked", "preact.layer3.19.bn1.num_batches_tracked", "preact.layer3.19.bn2.num_batches_tracked", "preact.layer3.19.bn3.num_batches_tracked", "preact.layer3.20.bn1.num_batches_tracked", "preact.layer3.20.bn2.num_batches_tracked", "preact.layer3.20.bn3.num_batches_tracked", "preact.layer3.21.bn1.num_batches_tracked", "preact.layer3.21.bn2.num_batches_tracked", "preact.layer3.21.bn3.num_batches_tracked", "preact.layer3.22.bn1.num_batches_tracked", "preact.layer3.22.bn2.num_batches_tracked", "preact.layer3.22.bn3.num_batches_tracked", "preact.layer4.0.bn1.num_batches_tracked", "preact.layer4.0.bn2.num_batches_tracked", "preact.layer4.0.bn3.num_batches_tracked", "preact.layer4.0.downsample.1.num_batches_tracked", "preact.layer4.1.bn1.num_batches_tracked", "preact.layer4.1.bn2.num_batches_tracked", "preact.layer4.1.bn3.num_batches_tracked", "preact.layer4.2.bn1.num_batches_tracked", "preact.layer4.2.bn2.num_batches_tracked", "preact.layer4.2.bn3.num_batches_tracked", "duc1.bn.num_batches_tracked", "duc2.bn.num_batches_tracked".

**Comment by noahcao** [comment]
In general, such bug is raised because the checkpoint file was created and loaded under different versions of Pytorch. During the migration among Pytorch 0.4.0 -> 0.4.1 -> 1.x.x, some layer names in the state_dict have been modified or not supported. You can check [a similar issue](https://discuss.pytorch.org/t/solved-unexpected-key-s-in-state-dict-batches-tracked/23884) for solutions.
