### ISSUE TITLE
ssd format for detection

### ISSUE THREAD

**Issue by xiaoheizi123** [MVIG-SJTU/AlphaPose#320]
Is there a guide for using the ssd format for the detection part?
when I run the demo.py , the class DetectionLoder cannot return the right answer,

`

(Pdb) data_loader.Q.empty()
False
(Pdb) n
Loading YOLO model..
> /home/zhengr/Documents/projects/keypoints/AlphaPose/demo.py(54)<module>()
-> sys.stdout.flush()
(Pdb) 
> /home/zhengr/Documents/projects/keypoints/AlphaPose/demo.py(56)<module>()
-> det_loader = DetectionLoader(data_loader, batchSize=args.detbatch).start()
(Pdb) 
> /home/zhengr/Documents/projects/keypoints/AlphaPose/demo.py(59)<module>()
-> det_processor = DetectionProcessor(det_loader).start()
(Pdb) Process Process-2:
Traceback (most recent call last):
  File "/home/zhengr/anaconda3/envs/keypoint/lib/python3.5/multiprocessing/process.py", line 252, in _bootstrap
    self.run()
  File "/home/zhengr/anaconda3/envs/keypoint/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zhengr/Documents/projects/keypoints/AlphaPose/dataloader.py", line 315, in update
    img, orig_img, im_name, im_dim_list = self.dataloder.getitem()
  File "/home/zhengr/Documents/projects/keypoints/AlphaPose/dataloader.py", line 171, in getitem
    return self.Q.get()
  File "/home/zhengr/anaconda3/envs/keypoint/lib/python3.5/multiprocessing/queues.py", line 113, in get
    return ForkingPickler.loads(res)
  File "/home/zhengr/anaconda3/envs/keypoint/lib/python3.5/site-packages/torch/multiprocessing/reductions.py", line 86, in rebuild_storage_filename
    storage = cls._new_shared_filename(manager, handle, size)
RuntimeError: No such file or directory at /pytorch/torch/lib/libshm/core.cpp:125

`

**Comment by michaelHaha** [comment]
I meet the same issue

**Comment by vishaldhull09** [comment]
Hi , were you able to solve it
