### ISSUE TITLE
Error message when run.sh

### ISSUE THREAD

**Issue by chikiuso** [MVIG-SJTU/AlphaPose#33]
Hi , I follow each steps and got the following error when I run the run.sh command as show on guide , pls help, thanks!

generating bbox from Faster RCNN...
Traceback (most recent call last):
  File "demo-alpha-pose.py", line 31, in <module>
    from nets.vgg16 import vgg16
  File "/home/chikiuso/Downloads/AlphaPose/human-detection/tools/../lib/nets/vgg16.py", line 11, in <module>
    import tensorflow.contrib.slim as slim
  File "/home/chikiuso/.conda/envs/py27/lib/python2.7/site-packages/tensorflow/contrib/__init__.py", line 31, in <module>
    from tensorflow.contrib import factorization
  File "/home/chikiuso/.conda/envs/py27/lib/python2.7/site-packages/tensorflow/contrib/factorization/__init__.py", line 24, in <module>
    from tensorflow.contrib.factorization.python.ops.gmm import *
  File "/home/chikiuso/.conda/envs/py27/lib/python2.7/site-packages/tensorflow/contrib/factorization/python/ops/gmm.py", line 27, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/home/chikiuso/.conda/envs/py27/lib/python2.7/site-packages/tensorflow/contrib/learn/__init__.py", line 88, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/home/chikiuso/.conda/envs/py27/lib/python2.7/site-packages/tensorflow/contrib/learn/python/__init__.py", line 23, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/home/chikiuso/.conda/envs/py27/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/__init__.py", line 25, in <module>
    from tensorflow.contrib.learn.python.learn import estimators
  File "/home/chikiuso/.conda/envs/py27/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/__init__.py", line 297, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.dnn import DNNClassifier
  File "/home/chikiuso/.conda/envs/py27/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py", line 30, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import dnn_linear_combined
  File "/home/chikiuso/.conda/envs/py27/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py", line 31, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/home/chikiuso/.conda/envs/py27/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 49, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io import data_feeder
  File "/home/chikiuso/.conda/envs/py27/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/learn_io/__init__.py", line 21, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io.dask_io import extract_dask_data
  File "/home/chikiuso/.conda/envs/py27/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/learn_io/dask_io.py", line 26, in <module>
    import dask.dataframe as dd
  File "/home/chikiuso/.conda/envs/py27/lib/python2.7/site-packages/dask/dataframe/__init__.py", line 3, in <module>
    from .core import (DataFrame, Series, Index, _Frame, map_partitions,
  File "/home/chikiuso/.conda/envs/py27/lib/python2.7/site-packages/dask/dataframe/core.py", line 40, in <module>
    pd.core.computation.expressions.set_use_numexpr(False)
AttributeError: 'module' object has no attribute 'expressions'
pose estimation with RMPE...
/home/chikiuso/torch/install/bin/lua: .../chikiuso/torch/install/share/lua/5.1/trepl/init.lua:389: ...me/chikiuso/torch/install/share/lua/5.1/hdf5/ffi.lua:56: expected align(#) on line 687
stack traceback:
	[C]: in function 'error'
	.../chikiuso/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	/home/chikiuso/Downloads/AlphaPose/predict/util.lua:7: in main chunk
	[C]: in function 'dofile'
	.../chikiuso/torch/install/share/lua/5.1/paths/init.lua:84: in function 'dofile'
	main-alpha-pose.lua:7: in main chunk
	[C]: in function 'dofile'
	.../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: ?
./run.sh: line 79: 15096 Segmentation fault      (core dumped) CUDA_VISIBLE_DEVICES=${GPU_ID} th main-alpha-pose.lua predict ${INPUT_PATH} ${OUTPUT_PATH} ${GPU_NUM} ${BATCH_SIZE} ${DATASET}
/home/chikiuso/.conda/envs/py27/lib/python2.7/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "parametric-pose-nms-MPII.py", line 256, in <module>
    get_result_json(args)
  File "parametric-pose-nms-MPII.py", line 243, in get_result_json
    test_parametric_pose_NMS_json(delta1, delta2, mu, gamma,args.outputpath)
  File "parametric-pose-nms-MPII.py", line 99, in test_parametric_pose_NMS_json
    h5file = h5py.File(os.path.join(outputpath,"POSE/test-pose.h5"), 'r')
  File "/home/chikiuso/.conda/envs/py27/lib/python2.7/site-packages/h5py/_hl/files.py", line 271, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/chikiuso/.conda/envs/py27/lib/python2.7/site-packages/h5py/_hl/files.py", line 101, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/feedstock_root/build_artefacts/h5py_1491364442174/work/h5py-2.7.0/h5py/_objects.c:2846)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/feedstock_root/build_artefacts/h5py_1491364442174/work/h5py-2.7.0/h5py/_objects.c:2804)
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open (/feedstock_root/build_artefacts/h5py_1491364442174/work/h5py-2.7.0/h5py/h5f.c:2123)
IOError: Unable to open file (Unable to open file: name = '/home/chikiuso/downloads/alphapose/examples/results/pose/test-pose.h5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)
visualization...
mkdir: cannot create directory ‘/home/chikiuso/Downloads/AlphaPose/examples/results//RENDER’: No such file or directory
Traceback (most recent call last):
  File "json-video.py", line 63, in <module>
    with open(jsonpath) as f:
IOError: [Errno 2] No such file or directory: '/home/chikiuso/Downloads/AlphaPose/examples/results/POSE/alpha-pose-results-forvis.json'

**Comment by Fang-Haoshu** [comment]
Hi, what tf version are you using?

**Comment by zhangleiedu** [comment]
same question, lack of "alpha-pose-results-forvis.json", tf version is 1.2.1。 Thanks

**Comment by Fang-Haoshu** [comment]
No response, close
