### ISSUE TITLE
mxnet加载duc_se模型报错

### ISSUE THREAD

**Issue by qiaowei1214** [MVIG-SJTU/AlphaPose#337]
加载的模型Parameter 'conv5_weight' shape不匹配
*************************
Loading yolo3_darknet53_coco ...
Modifying output layers to ignore non-person classes...
Loading SPPE ...
===Pretrain Base===
Traceback (most recent call last):
  File "video_demo.py", line 15, in <module>
    pose_estimator = PoseEstimator(img_cropper, batch_size=80)
  File "/data/kanhaipeng/AlphaPose/pipeline.py", line 500, in __init__
    self.net.load_parameters('sppe/params/duc_se.params')
  File "/root/anaconda3/envs/mxnet/lib/python3.6/site-packages/mxnet/gluon/block.py", line 402, in load_parameters
    params[name]._load_init(loaded[name], ctx)
  File "/root/anaconda3/envs/mxnet/lib/python3.6/site-packages/mxnet/gluon/parameter.py", line 237, in _load_init
    self.name, str(self.shape), str(data.shape))
AssertionError: Failed loading Parameter 'conv5_weight' from saved params: shape incompatible expected (17, 0, 3, 3) vs saved (33, 128, 3, 3)

**Comment by allenxcp** [comment]
the class must be 33,default is 17.
