### ISSUE TITLE
Detector Queue Not emptied by the DetectionProcessor hence gets into a loop

### ISSUE THREAD

**Issue by dynamicritz** [MVIG-SJTU/AlphaPose#348]

**Comment by learnermaxRL** [comment]
I am also facing the same issue as code fails at multiple stages of processing pepeline while fetching from previous queue.


*************************
Namespace(LR=0.0001, addDPG=False, board=True, confidence=0.1, crit='MSE', dataset='coco', det_model='frcnn', detbatch=1, dtype='float32', epoch=0, eps=1e-08, expID='default', format=None, gpu_id=[0], hardMining=False, hmGauss=1, inp_dim='608', inputResH=256, inputResW=192, inputlist='', inputpath='', loadModel=None, load_from_pyt=False, logging_file='training.log', lr_decay=0.1, lr_decay_epoch='20,60', map=True, mode='normal', nClasses=33, nEpochs=100, nThreads=60, nms_thresh=0.6, optMethod='rmsprop', outputResH=64, outputResW=48, outputpath='examples/res/', posebatch=80, pre_resnet=True, rotate=40, save_img=False, scale=0.3, snapshot=1, syncbn=False, trainBatch=28, trainIters=0, try_loadModel=None, use_pretrained_base=True, valIters=0, validBatch=24, vis=False, visdom=False)
*************************
Loading yolo3_darknet53_coco ...
Modifying output layers to ignore non-person classes...
Loading SPPE ...
===Pretrain Base===
  0%|                                                                                                                                                                           | 0/3 [00:00<?, ?it/s]l

 33%|██████████████████████████████████████████████████████▎                                                                                                            | 1/3 [00:01<00:02,  1.00s/it]ImageLoader: 0.152982s

 67%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                      | 2/3 [00:02<00:01,  1.00s/it]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:03<00:00,  1.00s/it]

Detector: 0.028182s
^CTraceback (most recent call last):
  File "demo.py", line 45, in <module>
    time.sleep(1)
KeyboardInterrupt
(mxnetenv) jbmai@jbmai-HP-ZBook-Studio-G4:~/Downloads/AlphaPose-mxnet$ ^C
(mxnetenv) jbmai@jbmai-HP-ZBook-Studio-G4:~/Downloads/AlphaPose-mxnet$ ^C
(mxnetenv) jbmai@jbmai-HP-ZBook-Studio-G4:~/Downloads/AlphaPose-mxnet$ python demo.py --nClasses 33
*************************
Namespace(LR=0.0001, addDPG=False, board=True, confidence=0.1, crit='MSE', dataset='coco', det_model='frcnn', detbatch=1, dtype='float32', epoch=0, eps=1e-08, expID='default', format=None, gpu_id=[0], hardMining=False, hmGauss=1, inp_dim='608', inputResH=256, inputResW=192, inputlist='', inputpath='', loadModel=None, load_from_pyt=False, logging_file='training.log', lr_decay=0.1, lr_decay_epoch='20,60', map=True, mode='normal', nClasses=33, nEpochs=100, nThreads=60, nms_thresh=0.6, optMethod='rmsprop', outputResH=64, outputResW=48, outputpath='examples/res/', posebatch=80, pre_resnet=True, rotate=40, save_img=False, scale=0.3, snapshot=1, syncbn=False, trainBatch=28, trainIters=0, try_loadModel=None, use_pretrained_base=True, valIters=0, validBatch=24, vis=False, visdom=False)
*************************
Loading yolo3_darknet53_coco ...
Modifying output layers to ignore non-person classes...
Loading SPPE ...
===Pretrain Base===
length of my imageloader job queue  0
length of my detector job queue  0
counter :  1   length of my work queue  0
  0%|                                                                                                                                                                           | 0/3 [00:00<?, ?it/s]counter :  2   length of my work queue  0
 33%|██████████████████████████████████████████████████████▎                                                                                                            | 1/3 [00:01<00:02,  1.00s/it]ImageLoader: 0.045963s
counter :  3   length of my work queue  0
 67%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                      | 2/3 [00:02<00:01,  1.00s/it]length of my detector job queue  2
length of my detector job queue  1
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.02it/s]
Detector: 0.075215s
^CTraceback (most recent call last):
  File "demo.py", line 45, in <module>
    time.sleep(1)
KeyboardInterrupt
