### ISSUE TITLE
RuntimeError: storage has wrong size

### ISSUE THREAD

**Issue by NEU-SHUAI** [MVIG-SJTU/AlphaPose#362]
您好，我在运行您的程序时遇到了以下问题无法解决，我在其他demo程序上运行也是报的这个错误，好像是sppe这个模型无法载入，请问您有什么好的解决办法吗？感谢。具体的报错信息如下所示：
`/home/robot/anaconda3/envs/alphapose_py3/bin/python3 /home/robot/Project/AlphaPose-pytorch/webcam_demo.py
Loading YOLO model..
Loading pose model from ./models/sppe/duc_se.pth
Traceback (most recent call last):
  File "/home/robot/Project/AlphaPose-pytorch/webcam_demo.py", line 55, in <module>
    pose_model = InferenNet_fast(4 * 1 + 1, pose_dataset)
  File "/home/robot/Project/AlphaPose-pytorch/SPPE/src/main_fast_inference.py", line 61, in __init__
    model.load_state_dict(torch.load('./models/sppe/duc_se.pth'))
  File "/home/robot/anaconda3/envs/alphapose_py3/lib/python3.6/site-packages/torch/serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "/home/robot/anaconda3/envs/alphapose_py3/lib/python3.6/site-packages/torch/serialization.py", line 476, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_is_real_file)
RuntimeError: storage has wrong size: expected -6351665276051172154 got 1024
terminate called without an active exception

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)`

**Comment by NEU-SHUAI** [comment]
通过重新下载duc_se.pth模型文件，我已经和解决了这个问题。感谢。
