### ISSUE TITLE
how to solve this problem

### ISSUE THREAD

**Issue by luoyuncen** [MVIG-SJTU/AlphaPose#41]
generating bbox from Faster RCNN...
Traceback (most recent call last):
  File "demo-alpha-pose.py", line 22, in <module>
    from newnms.nms import  soft_nms
  File "/home/luoyuncen/AlphaPose/human-detection/tools/../lib/newnms/nms.py", line 3, in <module>
    from cpu_nms import cpu_nms, cpu_soft_nms
ImportError: No module named cpu_nms
pose estimation with RMPE...

**Comment by kireoxdz** [comment]
Is it must have torch(lua)？I already have pytorch in my computer ,did it work?

**Comment by Fang-Haoshu** [comment]
Yes, you must have torch.
We are working on pytorch version, but not finished yet.
