### ISSUE TITLE
PyTorch版本存储空间不足报错

### ISSUE THREAD

**Issue by jhxing** [MVIG-SJTU/AlphaPose#444]
使用python3 video_demo.py --video ${path to video} --outdir examples/res --save_video 这个测试我本地的视频时，出现这个错误：
`Traceback (most recent call last):
  File "/home/smc/hongxing/body_detection/AlphaPose/video_demo.py", line 69, in <module>
    data_loader = VideoLoader(videofile, batchSize=args.detbatch).start()
  File "/home/smc/hongxing/body_detection/AlphaPose/dataloader.py", line 204, in __init__
    self.Q = mp.Queue(maxsize=queueSize)
  File "/usr/local/lib/python3.6/multiprocessing/context.py", line 102, in Queue
    return Queue(maxsize, ctx=self.get_context())
  File "/usr/local/lib/python3.6/multiprocessing/queues.py", line 42, in __init__
    self._rlock = ctx.Lock()
  File "/usr/local/lib/python3.6/multiprocessing/context.py", line 67, in Lock
    return Lock(ctx=self.get_context())
  File "/usr/local/lib/python3.6/multiprocessing/synchronize.py", line 163, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/usr/local/lib/python3.6/multiprocessing/synchronize.py", line 60, in __init__
    unlink_now)
OSError: [Errno 28] No space left on device

Process finished with exit code 1`

请问这个怎么解决？

**Comment by Fang-Haoshu** [comment]
清理本地硬盘空间
