### ISSUE TITLE
run.sh error

### ISSUE THREAD

**Issue by dengxuexiang** [MVIG-SJTU/AlphaPose#449]
zengxw@bdlk-SYS-4028GR-TR:~/python_work/AlphaPose-master$ ./run.sh --indir examples/demo/ --outdir examples/results/ --vis
0
generating bbox from Faster RCNN...
2019-11-04 17:31:15.214938: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-11-04 17:31:17.321931: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 0 with properties:
name: P102-100 major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:01:00.0
totalMemory: 9.92GiB freeMemory: 9.79GiB
2019-11-04 17:31:17.321989: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1471] Adding visible gpu devices: 0
2019-11-04 17:31:24.577141: I tensorflow/core/common_runtime/gpu/gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-11-04 17:31:24.577199: I tensorflow/core/common_runtime/gpu/gpu_device.cc:958]      0
2019-11-04 17:31:24.577208: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   N
2019-11-04 17:31:24.577326: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9463 MB memory) -> physical GPU (device: 0, name: P102-100, pci bus id: 0000:01:00.0, compute capability: 6.1)
Loaded network ../output/res152/coco_2014_train+coco_2014_valminusminival/default/res152.ckpt
/home/zengxw/python_work/AlphaPose-master/examples/demo/

100%|██████████| 3/3 [00:08<00:00,  2.74s/it]
pose estimation with RMPE...
Found Environment variable CUDNN_PATH = /home/zengxw/python_work/AlphaPose-master/cuda/lib64/libcudnn.so.5MPII
/home/zengxw/torch/install/bin/luajit: /home/zengxw/python_work/AlphaPose-master/predict/util.lua:34: attempt to index global 'hdf5' (a nil value)
stack traceback:
        /home/zengxw/python_work/AlphaPose-master/predict/util.lua:34: in function 'loadAnnotations'
        main-alpha-pose.lua:27: in main chunk
        [C]: in function 'dofile'
        ...ngxw/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: at 0x00405d80
Traceback (most recent call last):
  File "parametric-pose-nms-MPII.py", line 257, in <module>
    get_result_json(args)
  File "parametric-pose-nms-MPII.py", line 244, in get_result_json
    test_parametric_pose_NMS_json(delta1, delta2, mu, gamma,args.outputpath)
  File "parametric-pose-nms-MPII.py", line 100, in test_parametric_pose_NMS_json
    h5file = h5py.File(os.path.join(outputpath,"POSE/test-pose.h5"), 'r')
  File "/home/zengxw/.conda/envs/deng_py27/lib/python2.7/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/home/zengxw/.conda/envs/deng_py27/lib/python2.7/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
IOError: Unable to open file (unable to open file: name = '/home/zengxw/python_work/AlphaPose-master/examples/results/POSE/test-pose.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
visualization...
Traceback (most recent call last):
  File "json-video.py", line 66, in <module>
    rmpe_results = json.load(f)
  File "/home/zengxw/.conda/envs/deng_py27/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/home/zengxw/.conda/envs/deng_py27/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/home/zengxw/.conda/envs/deng_py27/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/zengxw/.conda/envs/deng_py27/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

What should I do?

**Comment by Fang-Haoshu** [comment]
Hi, it seems hdf5 is not installed in torch.
In fact, I would suggest trying the pytorch branch of AlphaPose which is faster and easy to run.

**Comment by Fang-Haoshu** [comment]
https://github.com/MVIG-SJTU/AlphaPose/tree/pytorch

**Comment by dengxuexiang** [comment]
Hello, I have installed hdf5 through "luarocks install hdf5", but it still runs incorrectly

**Comment by dengxuexiang** [comment]
thank you，Indeed, as you said, I also need to install torch-hdf5. But I'm reporting it again now: attempt to concatenate local 'headerPath' (a nil value). How can I fix this mistake? @Fang-Haoshu

**Comment by dengxuexiang** [comment]
thank you ,I have found the cause of the error. It is a problem with my local file
