### ISSUE TITLE
no such child 'xmin' for [HDF5Group 33554432 /]

### ISSUE THREAD

**Issue by gzp1993** [MVIG-SJTU/AlphaPose#45]
Hi, I met such a problem:
Loaded network ../output/res152/coco_2014_train+coco_2014_valminusminival/default/res152.ckpt
/home/yinruiying/Desktop/ring/env/AlphaPose/examples/demo/

 50%|█████████████████████████████████████████████████████████████▌                                                             | 2/4 [00:03<00:03,  1.53s/it]
Traceback (most recent call last):
  File "demo-alpha-pose.py", line 176, in <module>
    num_boxes=demo(sess, net, im_name, xminarr,yminarr,xmaxarr,ymaxarr,results,score_file,index_file,num_boxes,inputpath, mode)
  File "demo-alpha-pose.py", line 67, in demo
    scores, boxes = im_detect(sess, net, im)
  File "/home/yinruiying/Desktop/ring/env/AlphaPose/human-detection/tools/../lib/model/test.py", line 91, in im_detect
    blobs, im_scales = _get_blobs(im,scale)
  File "/home/yinruiying/Desktop/ring/env/AlphaPose/human-detection/tools/../lib/model/test.py", line 63, in _get_blobs
    blobs['data'], im_scale_factors = _get_image_blob(im,scale)
  File "/home/yinruiying/Desktop/ring/env/AlphaPose/human-detection/tools/../lib/model/test.py", line 35, in _get_image_blob
    im_orig = im.astype(np.float32, copy=True)
AttributeError: 'NoneType' object has no attribute 'astype'
pose estimation with RMPE...
MPII	
/home/yinruiying/torch/install/bin/luajit: /home/yinruiying/torch/install/share/lua/5.1/hdf5/group.lua:327: HDF5Group:read() - no such child 'xmin' for [HDF5Group 33554432 /]
stack traceback:
	[C]: in function 'error'
	/home/yinruiying/torch/install/share/lua/5.1/hdf5/group.lua:327: in function 'read'
	...e/yinruiying/Desktop/ring/env/AlphaPose/predict/util.lua:39: in function 'loadAnnotations'
	main-alpha-pose.lua:27: in main chunk
	[C]: in function 'dofile'
	...ying/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
/home/yinruiying/Desktop/ring/env/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "parametric-pose-nms-MPII.py", line 256, in <module>
    get_result_json(args)
  File "parametric-pose-nms-MPII.py", line 243, in get_result_json
    test_parametric_pose_NMS_json(delta1, delta2, mu, gamma,args.outputpath)
  File "parametric-pose-nms-MPII.py", line 99, in test_parametric_pose_NMS_json
    h5file = h5py.File(os.path.join(outputpath,"POSE/test-pose.h5"), 'r')
  File "/home/yinruiying/Desktop/ring/env/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/yinruiying/Desktop/ring/env/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 99, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
IOError: Unable to open file (unable to open file: name = '/home/yinruiying/Desktop/ring/env/AlphaPose/examples/results/POSE/test-pose.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

Then how can I settle it? Thanks...

**Comment by small-sky** [comment]
how do you solve it ?

**Comment by small-sky** [comment]
how do you solve it in the end?
