### ISSUE TITLE
pytnon3 demo.py error

### ISSUE THREAD

**Issue by dengxuexiang** [MVIG-SJTU/AlphaPose#452]
(deng_py36) zengxw@bdlk-SYS-4028GR-TR:~/python_work/AlphaPose$ python3 demo.py --indir examples/demo/ --outdir examples/res
Traceback (most recent call last):
  File "demo.py", line 1, in <module>
    import torch
  File "/home/zengxw/.conda/envs/deng_py36/lib/python3.6/site-packages/torch/__init__.py", line 78, in <module>
    from torch._C import *
ImportError: /home/zengxw/.conda/envs/deng_py36/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: THManagedSharedAllocator

hello,I installed torch version 0.4.0, cuda9.0,ubuntu16.04,What should I do now?

您好，我安装了torch0.4.0版本，cuda9.0,ubuntu16.04,现在我应该怎么办呢？

**Comment by dengxuexiang** [comment]
(deng_py36) zengxw@bdlk-SYS-4028GR-TR:~/python_work/AlphaPose$ python3 demo.py --indir examples/demo/ --outdir examples/res
Traceback (most recent call last):
  File "demo.py", line 1, in <module>
    import torch
  File "/home/zengxw/.conda/envs/deng_py36/lib/python3.6/site-packages/torch/__init__.py", line 78, in <module>
    from torch._C import *
ImportError: /home/zengxw/.conda/envs/deng_py36/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: THManagedSharedAllocator
(deng_py36) zengxw@bdlk-SYS-4028GR-TR:~/python_work/AlphaPose$
