### ISSUE TITLE
pytorch1.0 yolov3-tiny

### ISSUE THREAD

**Issue by ciayue** [MVIG-SJTU/AlphaPose#456]
使用pytorch1.0，如果用yolov3-tiny的模型，会出现以下报错，请教是什么问题：
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mdcs/server/cy/AlphaPose/dataloader.py", line 515, in update
    prediction = self.det_model(img, CUDA=True)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mdcs/server/cy/AlphaPose/yolo/darknet.py", line 353, in forward
    x = torch.cat((map1, map2), 1)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 38 and 36 in dimension 2 at /home/mdcs/server/cy/pytorch/aten/src/THC/generic/THCTensorMath.cu:83

**Comment by LiaoZihZrong** [comment]
請先更改detector/yolo_cfg.py裡面的cfg檔和weight檔位置
並且更改cfg檔的內容，裡面有個奇怪的bug
* yolov3-tiny的cfg檔的
```
[route]
layers = -1, 8
```
**請改成**
```
[route]
layers = -1, 19
```
