### ISSUE TITLE
Batch process in pycharm

### ISSUE THREAD

**Issue by Angel113110** [MVIG-SJTU/AlphaPose#481]
Hi, author
    I want to use alphapose to batch process images extracted from videos. A folder contains images extracted from one video. When I tried to do this. Error like this:

Exception in thread Thread-1:
Loading YOLO model..
Traceback (most recent call last):
  File "D:\Anaconda\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "D:\Anaconda\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "D:\pycharm\teacher_analyse\Alphapose\dataloader.py", line 151, in getitem_yolo
    img_k, orig_img_k, im_dim_list_k = prep_image(im_name_k, inp_dim)
  File "D:\pycharm\teacher_analyse\Alphapose\yolo\preprocess.py", line 42, in prep_image
    dim = orig_im.shape[1], orig_im.shape[0]
AttributeError: 'NoneType' object has no attribute 'shape'

I already set --sp flag in my code. After above error happened, 

Loading pose model from ./models/sppe/duc_se.pth
  0%|          | 0/367 [00:00<?, ?it/s]
this happened, process seemed stop. How it happened? Can you help me solve this problem?Thanks!

**Comment by Fang-Haoshu** [comment]
1. the image folder has something that is not image
2. you point to the wrong dir, maybe --indir point to a file or something that is not a dir
