### ISSUE TITLE
cannot import name 'roi_align_cuda'

### ISSUE THREAD

**Issue by Linking1** [MVIG-SJTU/AlphaPose#494]
in ubuntu16.04
when python setup.py develop
it say:
    from . import roi_align_cuda
    ImportError: cannot import name 'roi_align_cuda'

**Comment by Jeff-sjtu** [comment]
Can you please provide a more detailed running log?

**Comment by horsetif** [comment]
I have the same problem.Totally following  (https://github.com/MVIG-SJTU/AlphaPose/blob/master/docs/INSTALL.md)

**Comment by Jeff-sjtu** [comment]
@horsetif Please provide the complete error log.

**Comment by horsetif** [comment]
python setup.py develop --user
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    import alphapose
  File "/data1/mayuanxi/AlphaPose-master/alphapose/__init__.py", line 1, in <module>
    from .datasets import *  # noqa: F401,F403
  File "/data1/mayuanxi/AlphaPose-master/alphapose/datasets/__init__.py", line 1, in <module>
    from .coco_det import Mscoco_det
  File "/data1/mayuanxi/AlphaPose-master/alphapose/datasets/coco_det.py", line 15, in <module>
    from alphapose.utils.presets import SimpleTransform
  File "/data1/mayuanxi/AlphaPose-master/alphapose/utils/presets/__init__.py", line 1, in <module>
    from .simple_transform import SimpleTransform
  File "/data1/mayuanxi/AlphaPose-master/alphapose/utils/presets/simple_transform.py", line 22, in <module>
    from ..roi_align import RoIAlign
  File "/data1/mayuanxi/AlphaPose-master/alphapose/utils/roi_align/__init__.py", line 1, in <module>
    from .roi_align import roi_align, RoIAlign
  File "/data1/mayuanxi/AlphaPose-master/alphapose/utils/roi_align/roi_align.py", line 6, in <module>
    from . import roi_align_cuda
ImportError: cannot import name 'roi_align_cuda' from 'alphapose.utils.roi_align' (/data1/mayuanxi/AlphaPose-master/alphapose/utils/roi_align/__init__.py)

**Comment by AryaCao** [comment]
I have the same problem.  The cuda path is right.
the log is :
`Traceback (most recent call last):
  File "setup.py", line 57, in get_hash
    from alphapose.version import __version__
  File "/home/xx/openpose_project/AlphaPose/alphapose/__init__.py", line 1, in <module>
    from .datasets import *  # noqa: F401,F403
  File "/home/xx/openpose_project/AlphaPose/alphapose/datasets/__init__.py", line 1, in <module>
    from .coco_det import Mscoco_det
  File "/home/xx/openpose_project/AlphaPose/alphapose/datasets/coco_det.py", line 15, in <module>
    from alphapose.utils.presets import SimpleTransform
  File "/home/xx/openpose_project/AlphaPose/alphapose/utils/presets/__init__.py", line 1, in <module>
    from .simple_transform import SimpleTransform
  File "/home/xx/openpose_project/AlphaPose/alphapose/utils/presets/simple_transform.py", line 22, in <module>
    from ..roi_align import RoIAlign
  File "/home/xx/openpose_project/AlphaPose/alphapose/utils/roi_align/__init__.py", line 1, in <module>
    from .roi_align import roi_align, RoIAlign
  File "/home/xx/openpose_project/AlphaPose/alphapose/utils/roi_align/roi_align.py", line 6, in <module>
    from . import roi_align_cuda
ImportError: cannot import name 'roi_align_cuda'
`

**Comment by Jeff-sjtu** [comment]
Hi, @Linking1 @horsetif @AryaCao . The new commit 7be98097f34594ad8bf22f06c9da2b8d3059c5cc may fix this problem.

**Comment by learningpro** [comment]
> Hi, @Linking1 @horsetif @AryaCao . The new commit [7be9809](https://github.com/MVIG-SJTU/AlphaPose/commit/7be98097f34594ad8bf22f06c9da2b8d3059c5cc) may fix this problem.

Not really, It's still happening in the latest code

**Comment by darkdante2209** [comment]
Did anyone fix this?

**Comment by ryokbys** [comment]
In my case (without nvidia device), deleting the line `ext_modules=get_ext_modules(),` in setup.py causes this problem, since `roi_align_cuda.py` is not generated in `alphapose/utils/roi_align/` but `alphapose/utils/roi_align/roi_align.py` requires `roi_align_cuda.py`.

**Comment by marianoumena** [comment]
Hi all, 

I am having the same problem when trying to execute the code. does anyone know how to fix it? 

Thanks!

**Comment by maidouxiaozi** [comment]
> 就我而言（没有 nvidia 设备），删除行 setup.py 会导致此问题，因为不是生成的 inbutrequires。`ext_modules=get_ext_modules(),``roi_align_cuda.py``alphapose/utils/roi_align/``alphapose/utils/roi_align/roi_align.py``roi_align_cuda.py`

你解决次问题了吗？

**Comment by maidouxiaozi** [comment]
> > 就我而言（没有 nvidia 设备），删除行 setup.py 会导致此问题，因为不是生成的 inbutrequires。`` ext_modules=get_ext_modules(),``roi_align_cuda.py``alphapose/utils/roi_align/``alphapose/utils/roi_align/roi_align.py``roi_align_cuda.py ``
> 
> 你解决次问题了吗？

Did you fix this?

**Comment by mylittlebuds** [comment]
大佬们你们解决这个问题了吗

**Comment by ZifengLiu98** [comment]
> 大佬们你们解决这个问题了吗

兄弟，你这个问题最后咋解决的？

**Comment by ywdong** [comment]
遇到同样的问题，有谁知道怎么解决吗？
