### ISSUE TITLE
something wrong with multi-processing

### ISSUE THREAD

**Issue by horsetif** [MVIG-SJTU/AlphaPose#496]
python scripts/demo_inference.py --cfg configs/coco/hrnet/256x192_w32_lr1e-3.yaml --checkpoint pretrained_models/hrnet_w32_256x192.pth  --indir input_imgs/Kungfu/ --outdir output_imgs/Kungfu/ --gpu 1
Traceback (most recent call last):
  File "scripts/demo_inference.py", line 153, in <module>
    det_loader = DetectionLoader(input_source, get_detector(args), cfg, args, batchSize=args.detbatch, mode=mode).start()
  File "/data1/xx/AlphaPose-master/alphapose/utils/detector.py", line 93, in start
    self.image_detection_worker = self.start_worker(self.image_detection)
  File "/data1/xx/AlphaPose-master/alphapose/utils/detector.py", line 83, in start_worker
    p.start()
  File "/home/xx/anaconda3/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/home/xx/anaconda3/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/xx/anaconda3/lib/python3.7/multiprocessing/context.py", line 291, in _Popen
    return Popen(process_obj)
  File "/home/xx/anaconda3/lib/python3.7/multiprocessing/popen_forkserver.py", line 35, in __init__
    super().__init__(process_obj)
  File "/home/xx/anaconda3/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/xx/anaconda3/lib/python3.7/multiprocessing/popen_forkserver.py", line 47, in _launch
    reduction.dump(process_obj, buf)
  File "/home/xx/anaconda3/lib/python3.7/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
**TypeError: can't pickle weakref objects**
Traceback (most recent call last):
  File "/home/xx/anaconda3/lib/python3.7/multiprocessing/forkserver.py", line 261, in main
    old_handlers)
  File "/home/xx/anaconda3/lib/python3.7/multiprocessing/forkserver.py", line 297, in _serve_one
    code = spawn._main(child_r)
  File "/home/xx/anaconda3/lib/python3.7/multiprocessing/spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
  File "/home/xx/anaconda3/lib/python3.7/multiprocessing/synchronize.py", line 110, in __setstate__
    self._semlock = _multiprocessing.SemLock._rebuild(*state)
FileNotFoundError: [Errno 2] No such file or directory

**when I use --sp，the result is ok. I try to use various method but did not solve this problem.I think there is something wrong in "p = mp.Process(target=target,args=())" in detector.py 77-84 lines.**

**Comment by Fang-Haoshu** [comment]
Hi, you can check the https://github.com/MVIG-SJTU/AlphaPose/blob/master/scripts/demo_inference.py#L90
I notice your program calls the spawn.py

Did you use spawn here? How about using file_descriptor or file_system?

**Comment by Fang-Haoshu** [comment]
Hi, any updates?

**Comment by halcyon370** [comment]
When I change sharing strategy from file_system to file_descriptor, it shows FileNotFoundError.

**Comment by DongChengrong** [comment]
> Hi, you can check the https://github.com/MVIG-SJTU/AlphaPose/blob/master/scripts/demo_inference.py#L90 I notice your program calls the spawn.py
> 
> Did you use spawn here? How about using file_descriptor or file_system?

yes, I call spawn.py. How can I solve it?
thank you!

**Comment by juneleung** [comment]
I also have this issue on ubuntu 18.04
