### ISSUE TITLE
 from torchvision import _C  undefined symbol

### ISSUE THREAD

**Issue by dongzhengs** [MVIG-SJTU/AlphaPose#501]
Hi! 
   I have the following problem when I run the program on
   OS: Ubuntu 16.04
   PyTorch version: 1.1.0
   Torchvision: 0.3.0
   cuda: 9.0

Traceback (most recent call last):
  File "scripts/demo_inference.py", line 154, in <module>
    pose_model = builder.build_sppe(cfg.MODEL, preset_cfg=cfg.DATA_PRESET)
  File "/home/dongs/works/pose/AlphaPose/alphapose/models/builder.py", line 27, in build_sppe
    return build(cfg, SPPE, default_args=default_args)
  File "/home/dongs/works/pose/AlphaPose/alphapose/models/builder.py", line 18, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/dongs/works/pose/AlphaPose/alphapose/utils/registry.py", line 75, in build_from_cfg
    return obj_cls(**args)
  File "/home/dongs/works/pose/AlphaPose/alphapose/models/fastpose.py", line 30, in __init__
    import torchvision.models as tm   # noqa: F401,F403
  File "/home/dongs/anaconda3/envs/con_py36/lib/python3.6/site-packages/torchvision/__init__.py", line 1, in <module>
    from torchvision import models
  File "/home/dongs/anaconda3/envs/con_py36/lib/python3.6/site-packages/torchvision/models/__init__.py", line 11, in <module>
    from . import detection
  File "/home/dongs/anaconda3/envs/con_py36/lib/python3.6/site-packages/torchvision/models/detection/__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "/home/dongs/anaconda3/envs/con_py36/lib/python3.6/site-packages/torchvision/models/detection/faster_rcnn.py", line 7, in <module>
    from torchvision.ops import misc as misc_nn_ops
  File "/home/dongs/anaconda3/envs/con_py36/lib/python3.6/site-packages/torchvision/ops/__init__.py", line 1, in <module>
    from .boxes import nms, box_iou
  File "/home/dongs/anaconda3/envs/con_py36/lib/python3.6/site-packages/torchvision/ops/boxes.py", line 2, in <module>
    from torchvision import _C
ImportError: /home/dongs/anaconda3/envs/con_py36/lib/python3.6/site-packages/torchvision/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c107Warning4warnENS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

**Comment by dongzhengs** [comment]
I have solved this problem by downgrade cython to version 0.29.12
