### ISSUE TITLE
训练问题  opt调用失败？(so weird)

### ISSUE THREAD

**Issue by Davvwvvid** [MVIG-SJTU/AlphaPose#545]
感谢开源！ 训练上出了点问题
python train.py --dataset coco --expID exp1 --nClasses 17 --LR 1e-4运行后出现错误：

Traceback (most recent call last):
  File "train.py", line 14, in <module>
    from evaluation import prediction
  File "F:\train_sppe\src\evaluation.py", line 12, in <module>
    from predict.opt import opt
  File "F:\train_sppe\src\predict\opt.py", line 1
    ../opt.py
    ^
SyntaxError: invalid syntax
看了下貌似也没人遇到这个问题，可能是我环境配置问题，不过也不清楚怎么改。

**Comment by zxwblublu** [comment]
请问你解决了吗，我也遇见了这个问题
