### ISSUE TITLE
训练模型Broken pipe多线程问题 

### ISSUE THREAD

**Issue by Davvwvvid** [MVIG-SJTU/AlphaPose#548]
感谢开源，图片和视频均可以检测，但是用最新代码训练模型的时候出现两个错误如下：
############# Starting Epoch 0 | LR: 0.001 #############
  0%|          | 0/4682 [00:00<?, ?it/s]Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "A:\Python\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "A:\Python\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "A:\Python\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "A:\Python\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "A:\Python\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "A:\Python\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "A:\Python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\AlphaPose-master\scripts\train.py", line 6, in <module>
    import torch
  File "A:\Python\lib\site-packages\torch\__init__.py", line 81, in <module>
    from torch._C import *
ImportError: DLL load failed: ҳ▒▒▒ļ▒̫С▒▒▒޷▒▒▒ɲ▒▒▒▒▒
Traceback (most recent call last):
  File "scripts/train.py", line 253, in <module>
    main()
  File "scripts/train.py", line 200, in main
    loss, miou = train(opt, train_loader, m, criterion, optimizer, writer)
  File "scripts/train.py", line 33, in train
    for i, (inps, labels, label_masks, _, bboxes) in enumerate(train_loader):
  File "A:\Python\lib\site-packages\tqdm\_tqdm.py", line 930, in __iter__
    for obj in iterable:
  File "A:\Python\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "A:\Python\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
    w.start()
  File "A:\Python\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "A:\Python\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "A:\Python\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "A:\Python\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "A:\Python\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe

求助 这种问题该如何解决？

**Comment by anilsh** [comment]
How did you resolve this issue?

**Comment by Davvwvvid** [comment]
> How did you resolve this issue?

train.py make all num_workers=0
