### ISSUE TITLE
windows 错误OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by Davvwvvid** [MVIG-SJTU/AlphaPose#549]
感谢开源，图片和视频均可以检测，但是训练模型上出现问题，如下:
############# Starting Epoch 0 | LR: 0.001 #############
  0%|          | 0/4682 [00:00<?, ?it/s]Traceback (most recent call last):
  File "scripts/train.py", line 253, in <module>
    main()
  File "scripts/train.py", line 200, in main
    loss, miou = train(opt, train_loader, m, criterion, optimizer, writer)
  File "scripts/train.py", line 33, in train
    for i, (inps, labels, label_masks, _, bboxes) in enumerate(train_loader):
  File "A:\Python\lib\site-packages\tqdm\_tqdm.py", line 930, in __iter__
    for obj in iterable:
  File "A:\Python\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "A:\Python\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
    w.start()
  File "A:\Python\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "A:\Python\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "A:\Python\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "A:\Python\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "A:\Python\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
OSError: [Errno 22] Invalid argument

请问如何解决？

**Comment by Fang-Haoshu** [comment]
你好，好像你现在跑通了？怎么做的呢

**Comment by Davvwvvid** [comment]
您好，我的做法是：
1、把tqdm等库降级到requirements中要求的版本
2、将num_workers都设为0
具体还有哪些操作我有点记不清，想到了再来补充吧。
如果能帮助到您，深感荣幸

**Comment by Fang-Haoshu** [comment]
明白 谢谢哈
