### ISSUE TITLE
FileNotFoundError 训练时trainval2017文件读取失败问题 

### ISSUE THREAD

**Issue by Davvwvvid** [MVIG-SJTU/AlphaPose#554]
感谢开源，在训练Epoch 1 时遇到了问题，不知是否为命名错误？
Network successfully loaded
100%|▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒| 5000/5000 [20:03<00:00,  4.15it/s]
  0%|          | 0/12417 [00:00<?, ?it/s]Traceback (most recent call last):
  File "scripts/train.py", line 253, in <module>
    main()
  File "scripts/train.py", line 211, in main
    rcnn_AP = validate(m.module, opt, heatmap_to_coord)
  File "scripts/train.py", line 88, in validate
    for inps, crop_bboxes, bboxes, img_ids, scores, imghts, imgwds in tqdm(det_loader, dynamic_ncols=True):
  File "A:\Python\lib\site-packages\tqdm\_tqdm.py", line 930, in __iter__
    for obj in iterable:
  File "A:\Python\lib\site-packages\torch\utils\data\dataloader.py", line 345, in __next__
    data = self._next_data()
  File "A:\Python\lib\site-packages\torch\utils\data\dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "A:\Python\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "A:\Python\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "f:\alphapose-master\alphapose\datasets\coco_det.py", line 74, in __getitem__
    image = scipy.misc.imread(img_path, mode='RGB')
  File "A:\Python\lib\site-packages\numpy\lib\utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "A:\Python\lib\site-packages\scipy\misc\pilutil.py", line 164, in imread
    im = Image.open(name)
  File "A:\Python\lib\site-packages\PIL\Image.py", line 2609, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './data/coco/trainval2017/000000000139.jpg'

我是按照INSTALL里的命名格式来的，所以./data/coco下不存在trainval2017文件夹，000000000139.jpg图片应该是val2017文件夹下的，是否要将val2017改为trainval2017 ？

**Comment by Davvwvvid** [comment]
@Fang-Haoshu 麻烦解答，谢谢您！

**Comment by Fang-Haoshu** [comment]
你好，我们发现是https://github.com/MVIG-SJTU/AlphaPose/blob/master/alphapose/datasets/coco_det.py#L71这个位置有个bug，刚刚fix了，你看看ok了吗

**Comment by Davvwvvid** [comment]
嗯嗯，麻烦啦

**Comment by twittering0912** [comment]
您好，我也遇到了这个问题，我是用的pytorch分支，想问问您是哪里出了问题呢？ @Fang-Haoshu
