### ISSUE TITLE
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).

### ISSUE THREAD

**Issue by Wei-Zhuo** [MVIG-SJTU/AlphaPose#564]
Traceback (most recent call last):
  File "/root/anaconda2/envs/alphapose/lib/python3.6/multiprocessing/queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/root/anaconda2/envs/alphapose/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/root/anaconda2/envs/alphapose/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 315, in reduce_storage
    fd, size = storage._share_fd_()
RuntimeError: unable to write to file </torch_995_2167858072>
  0%|                                                                                          | 0/1171 [00:14<?, ?it/s]
Traceback (most recent call last):
  File "scripts/train.py", line 253, in <module>
    main()
  File "scripts/train.py", line 200, in main
    loss, miou = train(opt, train_loader, m, criterion, optimizer, writer)
  File "scripts/train.py", line 41, in train
    output = m(inps)
  File "/root/anaconda2/envs/alphapose/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda2/envs/alphapose/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 148, in forward
    inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
  File "/root/anaconda2/envs/alphapose/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 159, in scatter
    return scatter_kwargs(inputs, kwargs, device_ids, dim=self.dim)
  File "/root/anaconda2/envs/alphapose/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 35, in scatter_kwargs
    inputs = scatter(inputs, target_gpus, dim) if inputs else []
  File "/root/anaconda2/envs/alphapose/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 28, in scatter
    return scatter_map(inputs)
  File "/root/anaconda2/envs/alphapose/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 15, in scatter_map
    return list(zip(*map(scatter_map, obj)))
  File "/root/anaconda2/envs/alphapose/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 13, in scatter_map
    return Scatter.apply(target_gpus, None, dim, obj)
  File "/root/anaconda2/envs/alphapose/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 89, in forward
    outputs = comm.scatter(input, target_gpus, chunk_sizes, ctx.dim, streams)
  File "/root/anaconda2/envs/alphapose/lib/python3.6/site-packages/torch/cuda/comm.py", line 147, in scatter
    return tuple(torch._C._scatter(tensor, devices, chunk_sizes, dim, streams))
  File "/root/anaconda2/envs/alphapose/lib/python3.6/site-packages/torch/utils/data/_utils/signal_handling.py", line 63, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 999) is killed by signal: Bus error.
请问下是怎么回事，要怎么解决？

**Comment by Wei-Zhuo** [comment]
@Fred Fang

**Comment by Fang-Haoshu** [comment]
系统资源不足？ 减少一下dataloader数量

**Comment by Wei-Zhuo** [comment]
谢谢！我也通过了减少train时候加载的epoch解决了这个问题
