### ISSUE TITLE
RuntimeError: shape '[1, 1, 1152]' is invalid for input of size 56623104

### ISSUE THREAD

**Issue by Zepyhrus** [MVIG-SJTU/AlphaPose#566]
作者好，我在用batchsize 128训练的时候遇到问题，但是64的时候不会有问题。如下：
'''
Traceback (most recent call last):
  File "scripts/train.py", line 258, in <module>
    main()
  File "scripts/train.py", line 204, in main
    loss, miou = train(opt, train_loader, m, criterion, optimizer, writer)
  File "scripts/train.py", line 41, in train
    output = m(inps)
  File "/home/ubuntu/anaconda3/envs/efficientdet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/efficientdet/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/ubuntu/anaconda3/envs/efficientdet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/Workspace/AlphaPose/alphapose/models/fastpose.py", line 55, in forward
    out = self.preact(x)
  File "/home/ubuntu/anaconda3/envs/efficientdet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/Workspace/AlphaPose/alphapose/models/layers/SE_Resnet.py", line 185, in forward
    x = self.layer2(x)  # 512 * h/8 * w/8
  File "/home/ubuntu/anaconda3/envs/efficientdet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/efficientdet/lib/python3.6/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/ubuntu/anaconda3/envs/efficientdet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/Workspace/AlphaPose/alphapose/models/layers/SE_Resnet.py", line 127, in forward
    out = F.relu(self.bn2(self.conv2(out, offset)), inplace=True)
  File "/home/ubuntu/anaconda3/envs/efficientdet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/Workspace/AlphaPose/alphapose/models/layers/dcn/deform_conv.py", line 236, in forward
    self.dilation, self.groups, self.deformable_groups)
  File "/home/ubuntu/Workspace/AlphaPose/alphapose/models/layers/dcn/deform_conv.py", line 55, in forward
    cur_im2col_step)
RuntimeError: shape '[1, 1, 1152]' is invalid for input of size 56623104
'''

不知道这算不算一个bug？望解答，谢谢！

**Comment by Zepyhrus** [comment]
Problem solved.

**Comment by supercheney** [comment]
Hello, I met the same problem with you. May you tell me how to solve it, thanks!

**Comment by TianyangHuang** [comment]
> Problem solved.

请问是如何解决的呢
