### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by willfu** [MVIG-SJTU/AlphaPose#572]
Just follow the installation guide, my OS is Ubuntu1604, conda env.

(alphapose) will@will-pc:~/pose/AlphaPose$ python setup.py build develop
Compiling detector/nms/src/soft_nms_cpu.pyx because it depends on /home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Includes/numpy/__init__.pxd.
[1/1] Cythonizing detector/nms/src/soft_nms_cpu.pyx
running build
running build_py
copying alphapose/version.py -> build/lib.linux-x86_64-3.6/alphapose
running build_ext
building 'detector.nms.soft_nms_cpu' extension
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/numpy/core/include -I/home/will/anaconda3/envs/alphapose/include/python3.6m -c detector/nms/src/soft_nms_cpu.cpp -o build/temp.linux-x86_64-3.6/detector/nms/src/soft_nms_cpu.o -Wno-unused-function -Wno-write-strings -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=soft_nms_cpu -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1832:0,
                 from /home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from detector/nms/src/soft_nms_cpu.cpp:640:
/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^
g++ -pthread -shared -L/home/will/anaconda3/envs/alphapose/lib -Wl,-rpath=/home/will/anaconda3/envs/alphapose/lib,--no-as-needed build/temp.linux-x86_64-3.6/detector/nms/src/soft_nms_cpu.o -L/home/will/anaconda3/envs/alphapose/lib -lpython3.6m -o build/lib.linux-x86_64-3.6/detector/nms/soft_nms_cpu.cpython-36m-x86_64-linux-gnu.so
running develop
running egg_info
writing alphapose.egg-info/PKG-INFO
writing dependency_links to alphapose.egg-info/dependency_links.txt
writing requirements to alphapose.egg-info/requires.txt
writing top-level names to alphapose.egg-info/top_level.txt
reading manifest file 'alphapose.egg-info/SOURCES.txt'
writing manifest file 'alphapose.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-x86_64-3.6/detector/nms/soft_nms_cpu.cpython-36m-x86_64-linux-gnu.so -> detector/nms
copying build/lib.linux-x86_64-3.6/detector/nms/nms_cpu.cpython-36m-x86_64-linux-gnu.so -> detector/nms
copying build/lib.linux-x86_64-3.6/detector/nms/nms_cuda.cpython-36m-x86_64-linux-gnu.so -> detector/nms
copying build/lib.linux-x86_64-3.6/alphapose/utils/roi_align/roi_align_cuda.cpython-36m-x86_64-linux-gnu.so -> alphapose/utils/roi_align
copying build/lib.linux-x86_64-3.6/alphapose/models/layers/dcn/deform_conv_cuda.cpython-36m-x86_64-linux-gnu.so -> alphapose/models/layers/dcn
copying build/lib.linux-x86_64-3.6/alphapose/models/layers/dcn/deform_pool_cuda.cpython-36m-x86_64-linux-gnu.so -> alphapose/models/layers/dcn
Creating /home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/alphapose.egg-link (link to .)
Adding alphapose 0.3.0+6da16b0 to easy-install.pth file

Installed /home/will/pose/AlphaPose
Processing dependencies for alphapose==0.3.0+6da16b0
Searching for pycocotools
Reading https://pypi.tuna.tsinghua.edu.cn/simple/pycocotools/
Downloading https://pypi.tuna.tsinghua.edu.cn/packages/96/84/9a07b1095fd8555ba3f3d519517c8743c2554a245f9476e5e39869f948d2/pycocotools-2.0.0.tar.gz#sha256=cbb8c2fbab80450a67ee9879c63b0bc8a69e58dd9a0153d55de404c0d383a94b
Best match: pycocotools 2.0.0
Processing pycocotools-2.0.0.tar.gz
Writing /tmp/easy_install-afkav7gm/pycocotools-2.0.0/setup.cfg
Running pycocotools-2.0.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-afkav7gm/pycocotools-2.0.0/egg-dist-tmp-54qsbe2m
Compiling pycocotools/_mask.pyx because it depends on /home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Includes/numpy/__init__.pxd.
[1/1] Cythonizing pycocotools/_mask.pyx
/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/easy_install-afkav7gm/pycocotools-2.0.0/pycocotools/_mask.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
Traceback (most recent call last):
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 2217, in visit_FuncDefNode
    node.body = node.body.analyse_expressions(node.local_scope)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 436, in analyse_expressions
    for stat in self.stats]
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 436, in <listcomp>
    for stat in self.stats]
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 6692, in analyse_expressions
    self.item = self.item.coerce_to(self.target.type, env)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/ExprNodes.py", line 952, in coerce_to
    src = PyTypeTestNode(src, dst_type, env)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/ExprNodes.py", line 13002, in __init__
    assert dst_type.is_extension_type or dst_type.is_builtin_type, "PyTypeTest on non extension type"
AssertionError: PyTypeTest on non extension type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/sandbox.py", line 158, in save_modules
    yield saved
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/sandbox.py", line 199, in setup_context
    yield
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/sandbox.py", line 254, in run_setup
    _execfile(setup_script, ns)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/sandbox.py", line 49, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-afkav7gm/pycocotools-2.0.0/setup.py", line 29, in <module>
    # construct minimal environment
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1102, in cythonize
    cythonize_one(*args)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1208, in cythonize_one
    result = compile_single(pyx_file, options, full_module_name=full_module_name)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 727, in compile_single
    return run_pipeline(source, options, full_module_name)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 515, in run_pipeline
    err, enddata = Pipeline.run_pipeline(pipeline, source)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/Pipeline.py", line 355, in run_pipeline
    data = run(phase, data)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/Pipeline.py", line 335, in run
    return phase(data)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 1597, in __call__
    return super_class.__call__(root)
  File "Cython/Compiler/Visitor.py", line 355, in Cython.Compiler.Visitor.EnvTransform.__call__
  File "Cython/Compiler/Visitor.py", line 302, in Cython.Compiler.Visitor.CythonTransform.__call__
  File "Cython/Compiler/Visitor.py", line 284, in Cython.Compiler.Visitor.VisitorTransform.__call__
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 1607, in visit_ModuleNode
    node.analyse_declarations(self.current_env())
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/ModuleNode.py", line 124, in analyse_declarations
    self.body.analyse_declarations(env)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 431, in analyse_declarations
    stat.analyse_declarations(env)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 431, in analyse_declarations
    stat.analyse_declarations(env)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 7931, in analyse_declarations
    self.module_name, self.pos, relative_level=0 if self.is_absolute else -1)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/Symtab.py", line 1270, in find_module
    module_name, relative_to=relative_to, pos=pos, absolute_fallback=absolute_fallback)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 232, in find_module
    err, result = self.process_pxd(source_desc, scope, qualified_name)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 146, in process_pxd
    result = Pipeline.run_pipeline(pipeline, source_desc)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/Pipeline.py", line 355, in run_pipeline
    data = run(phase, data)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/Pipeline.py", line 335, in run
    return phase(data)
  File "Cython/Compiler/Visitor.py", line 302, in Cython.Compiler.Visitor.CythonTransform.__call__
  File "Cython/Compiler/Visitor.py", line 284, in Cython.Compiler.Visitor.VisitorTransform.__call__
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 2212, in visit_ModuleNode
    self.visitchildren(node)
  File "Cython/Compiler/Visitor.py", line 247, in Cython.Compiler.Visitor.VisitorTransform.visitchildren
  File "Cython/Compiler/Visitor.py", line 251, in Cython.Compiler.Visitor.VisitorTransform.visitchildren
  File "Cython/Compiler/Visitor.py", line 260, in Cython.Compiler.Visitor.VisitorTransform._process_children
  File "Cython/Compiler/Visitor.py", line 221, in Cython.Compiler.Visitor.TreeVisitor._visitchildren
  File "Cython/Compiler/Visitor.py", line 193, in Cython.Compiler.Visitor.TreeVisitor._visitchild
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 312, in Cython.Compiler.Visitor.CythonTransform.visit_Node
  File "Cython/Compiler/Visitor.py", line 260, in Cython.Compiler.Visitor.VisitorTransform._process_children
  File "Cython/Compiler/Visitor.py", line 219, in Cython.Compiler.Visitor.TreeVisitor._visitchildren
  File "Cython/Compiler/Visitor.py", line 193, in Cython.Compiler.Visitor.TreeVisitor._visitchild
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 312, in Cython.Compiler.Visitor.CythonTransform.visit_Node
  File "Cython/Compiler/Visitor.py", line 260, in Cython.Compiler.Visitor.VisitorTransform._process_children
  File "Cython/Compiler/Visitor.py", line 219, in Cython.Compiler.Visitor.TreeVisitor._visitchildren
  File "Cython/Compiler/Visitor.py", line 193, in Cython.Compiler.Visitor.TreeVisitor._visitchild
  File "Cython/Compiler/Visitor.py", line 188, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 148, in Cython.Compiler.Visitor.TreeVisitor._raise_compiler_error
Cython.Compiler.Errors.CompilerCrash: 
Error compiling Cython file:
------------------------------------------------------------
...
    if PyDataType_HASSUBARRAY(d):
        return <tuple>d.subarray.shape
    else:
        return ()

cdef inline char* _util_dtypestring(dtype descr, char* f, char* end, int* offset) except NULL:
    ^
------------------------------------------------------------

/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Includes/numpy/__init__.pxd:842:5: Compiler crash in AnalyseExpressionsTransform

ModuleNode.body = StatListNode(__init__.pxd:17:0)
StatListNode.stats[41] = StatListNode(__init__.pxd:842:5)
StatListNode.stats[0] = CFuncDefNode(__init__.pxd:842:5,
    args = [...]/4,
    inline_in_pxd = True,
    modifiers = [...]/1,
    visibility = 'private')

Compiler crash traceback from this point on:
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 2217, in visit_FuncDefNode
    node.body = node.body.analyse_expressions(node.local_scope)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 436, in analyse_expressions
    for stat in self.stats]
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 436, in <listcomp>
    for stat in self.stats]
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 6692, in analyse_expressions
    self.item = self.item.coerce_to(self.target.type, env)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/ExprNodes.py", line 952, in coerce_to
    src = PyTypeTestNode(src, dst_type, env)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/ExprNodes.py", line 13002, in __init__
    assert dst_type.is_extension_type or dst_type.is_builtin_type, "PyTypeTest on non extension type"
AssertionError: PyTypeTest on non extension type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 211, in <module>
    zip_safe=False)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/command/develop.py", line 36, in run
    self.install_for_development()
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/command/develop.py", line 150, in install_for_development
    self.process_distribution(None, self.dist, not self.no_deps)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 745, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/pkg_resources/__init__.py", line 863, in resolve
    replace_conflicting=replace_conflicting
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1141, in best_match
    return self.obtain(req, installer)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1153, in obtain
    return installer(requirement)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 672, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 698, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 879, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1118, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1104, in run_setup
    run_setup(setup_script, args)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/sandbox.py", line 257, in run_setup
    raise
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/sandbox.py", line 199, in setup_context
    yield
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/sandbox.py", line 170, in save_modules
    saved_exc.resume()
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/sandbox.py", line 145, in resume
    six.reraise(type, exc, self._tb)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/pkg_resources/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/sandbox.py", line 158, in save_modules
    yield saved
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/sandbox.py", line 199, in setup_context
    yield
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/sandbox.py", line 254, in run_setup
    _execfile(setup_script, ns)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/sandbox.py", line 49, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-afkav7gm/pycocotools-2.0.0/setup.py", line 29, in <module>
    # construct minimal environment
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1102, in cythonize
    cythonize_one(*args)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1208, in cythonize_one
    result = compile_single(pyx_file, options, full_module_name=full_module_name)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 727, in compile_single
    return run_pipeline(source, options, full_module_name)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 515, in run_pipeline
    err, enddata = Pipeline.run_pipeline(pipeline, source)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/Pipeline.py", line 355, in run_pipeline
    data = run(phase, data)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/Pipeline.py", line 335, in run
    return phase(data)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 1597, in __call__
    return super_class.__call__(root)
  File "Cython/Compiler/Visitor.py", line 355, in Cython.Compiler.Visitor.EnvTransform.__call__
  File "Cython/Compiler/Visitor.py", line 302, in Cython.Compiler.Visitor.CythonTransform.__call__
  File "Cython/Compiler/Visitor.py", line 284, in Cython.Compiler.Visitor.VisitorTransform.__call__
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 1607, in visit_ModuleNode
    node.analyse_declarations(self.current_env())
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/ModuleNode.py", line 124, in analyse_declarations
    self.body.analyse_declarations(env)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 431, in analyse_declarations
    stat.analyse_declarations(env)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 431, in analyse_declarations
    stat.analyse_declarations(env)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 7931, in analyse_declarations
    self.module_name, self.pos, relative_level=0 if self.is_absolute else -1)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/Symtab.py", line 1270, in find_module
    module_name, relative_to=relative_to, pos=pos, absolute_fallback=absolute_fallback)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 232, in find_module
    err, result = self.process_pxd(source_desc, scope, qualified_name)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 146, in process_pxd
    result = Pipeline.run_pipeline(pipeline, source_desc)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/Pipeline.py", line 355, in run_pipeline
    data = run(phase, data)
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/Pipeline.py", line 335, in run
    return phase(data)
  File "Cython/Compiler/Visitor.py", line 302, in Cython.Compiler.Visitor.CythonTransform.__call__
  File "Cython/Compiler/Visitor.py", line 284, in Cython.Compiler.Visitor.VisitorTransform.__call__
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 2212, in visit_ModuleNode
    self.visitchildren(node)
  File "Cython/Compiler/Visitor.py", line 247, in Cython.Compiler.Visitor.VisitorTransform.visitchildren
  File "Cython/Compiler/Visitor.py", line 251, in Cython.Compiler.Visitor.VisitorTransform.visitchildren
  File "Cython/Compiler/Visitor.py", line 260, in Cython.Compiler.Visitor.VisitorTransform._process_children
  File "Cython/Compiler/Visitor.py", line 221, in Cython.Compiler.Visitor.TreeVisitor._visitchildren
  File "Cython/Compiler/Visitor.py", line 193, in Cython.Compiler.Visitor.TreeVisitor._visitchild
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 312, in Cython.Compiler.Visitor.CythonTransform.visit_Node
  File "Cython/Compiler/Visitor.py", line 260, in Cython.Compiler.Visitor.VisitorTransform._process_children
  File "Cython/Compiler/Visitor.py", line 219, in Cython.Compiler.Visitor.TreeVisitor._visitchildren
  File "Cython/Compiler/Visitor.py", line 193, in Cython.Compiler.Visitor.TreeVisitor._visitchild
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 312, in Cython.Compiler.Visitor.CythonTransform.visit_Node
  File "Cython/Compiler/Visitor.py", line 260, in Cython.Compiler.Visitor.VisitorTransform._process_children
  File "Cython/Compiler/Visitor.py", line 219, in Cython.Compiler.Visitor.TreeVisitor._visitchildren
  File "Cython/Compiler/Visitor.py", line 193, in Cython.Compiler.Visitor.TreeVisitor._visitchild
  File "Cython/Compiler/Visitor.py", line 188, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 148, in Cython.Compiler.Visitor.TreeVisitor._raise_compiler_error
setuptools.sandbox.UnpickleableException: CompilerCrash((<FileSourceDescriptor:/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Includes/numpy/__init__.pxd>, 842, 5), 'AnalyseExpressionsTransform', 'Compiler crash in AnalyseExpressionsTransform\n\nModuleNode.body = StatListNode(__init__.pxd:17:0)\nStatListNode.stats[41] = StatListNode(__init__.pxd:842:5)\nStatListNode.stats[0] = CFuncDefNode(__init__.pxd:842:5,\n    args = [...]/4,\n    inline_in_pxd = True,\n    modifiers = [...]/1,\n    visibility = \'private\')\n\nCompiler crash traceback from this point on:\n  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit\n  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 2217, in visit_FuncDefNode\n    node.body = node.body.analyse_expressions(node.local_scope)\n  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 436, in analyse_expressions\n    for stat in self.stats]\n  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 436, in <listcomp>\n    for stat in self.stats]\n  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/Nodes.py", line 6692, in analyse_expressions\n    self.item = self.item.coerce_to(self.target.type, env)\n  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/ExprNodes.py", line 952, in coerce_to\n    src = PyTypeTestNode(src, dst_type, env)\n  File "/home/will/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Compiler/ExprNodes.py", line 13002, in __init__\n    assert dst_type.is_extension_type or dst_type.is_builtin_type, "PyTypeTest on non extension type"\nAssertionError: PyTypeTest on non extension type', AssertionError('PyTypeTest on non extension type',), <traceback object at 0x7f9f5eba87c8>)
(alphapose) will@will-pc:~/pose/AlphaPose$

**Comment by Fang-Haoshu** [comment]
Seems the problem of pycocotools. I guess it won't affect the demo

**Comment by willfu** [comment]
@Fang-Haoshu thanks for the reply. I have tried to run the demo. not working. the installation is blocked and some packages are not installed...

**Comment by Fang-Haoshu** [comment]
I see, how about remove the pycocotools from setup.py? If you do not need the training

**Comment by willfu** [comment]
yes, it works. thanks.

**Comment by liguoyu666** [comment]
> 我知道，如何从setup.py中删除pycocotools？如果您不需要培训

when I build the dockerfile, I met the same problem, how to remove the pycocotools from setup.py?

**Comment by xuchao1688** [comment]
> > 我知道，如何从setup.py中删除pycocotools？如果您不需要培训
> 
> when I build the dockerfile, I met the same problem, how to remove the pycocotools from setup.py?

[https://github.com/MVIG-SJTU/AlphaPose/blob/adaf1cd0385092ca3468d1decd4930be7466ec92/setup.py#L170](url) This line adds pycocotools package for linux os.

**Comment by macqueen09** [comment]
same question,  after remove pycocotools , compile success.
Mark first.
I'm figure out how to install pycocotools myself , because I need train this model on hand keypoint data

**Comment by Fang-Haoshu** [comment]
Hi, you might try

locale-gen C.UTF-8

# if locale-gen not found
apt-get install locales

export LANG=C.UTF-8


from: https://github.com/open-mmlab/mmdetection/issues/1025#issuecomment-563711892
