### ISSUE TITLE
error happen when run the setup.py.

### ISSUE THREAD

**Issue by tim20120526** [MVIG-SJTU/AlphaPose#580]
HI! this is a nice work!!! i meet some problems when i do the installation.
when i run python setup.py build develop, some error below happen,can you help me??Good luck with your work！！

my setting:
pytorch =1.5.0
torchvision=0.6.0
cuda=10.1

running build
running build_py
copying alphapose/version.py -> build/lib.linux-x86_64-3.6/alphapose
running build_ext
building 'detector.nms.nms_cuda' extension
Emitting ninja build file /home/daqin.luo.interns/project/AlphaPose-master/build/temp.linux-x86_64-3.6/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] c++ -MMD -MF /home/daqin.luo.interns/project/AlphaPose-master/build/temp.linux-x86_64-3.6/detector/nms/src/nms_cuda.o.d -pthread -B /home/daqin.luo.interns/anaconda3/envs/py3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/site-packages/torch/include -I/home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/site-packages/torch/include/TH -I/home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/daqin.luo.interns/anaconda3/envs/py3/include/python3.6m -c -c /home/daqin.luo.interns/project/AlphaPose-master/detector/nms/src/nms_cuda.cpp -o /home/daqin.luo.interns/project/AlphaPose-master/build/temp.linux-x86_64-3.6/detector/nms/src/nms_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14

FAILED: /home/daqin.luo.interns/project/AlphaPose-master/build/temp.linux-x86_64-3.6/detector/nms/src/nms_cuda.o

c++ -MMD -MF /home/daqin.luo.interns/project/AlphaPose-master/build/temp.linux-x86_64-3.6/detector/nms/src/nms_cuda.o.d -pthread -B /home/daqin.luo.interns/anaconda3/envs/py3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/site-packages/torch/include -I/home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/site-packages/torch/include/TH -I/home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/daqin.luo.interns/anaconda3/envs/py3/include/python3.6m -c -c /home/daqin.luo.interns/project/AlphaPose-master/detector/nms/src/nms_cuda.cpp -o /home/daqin.luo.interns/project/AlphaPose-master/build/temp.linux-x86_64-3.6/detector/nms/src/nms_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/home/daqin.luo.interns/project/AlphaPose-master/detector/nms/src/nms_cuda.cpp: In function ‘at::Tensor nms(const at::Tensor&, float)’:
/home/daqin.luo.interns/project/AlphaPose-master/detector/nms/src/nms_cuda.cpp:4:39: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
 #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                                       ^
/home/daqin.luo.interns/project/AlphaPose-master/detector/nms/src/nms_cuda.cpp:9:3: note: in expansion of macro ‘CHECK_CUDA’
   CHECK_CUDA(dets);
   ^
In file included from /home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/site-packages/torch/include/ATen/Tensor.h:11:0,
                 from /home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/site-packages/torch/include/ATen/Context.h:4,
                 from /home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/site-packages/torch/include/ATen/ATen.h:5,
                 from /home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/site-packages/torch/include/torch/extension.h:4,
                 from /home/daqin.luo.interns/project/AlphaPose-master/detector/nms/src/nms_cuda.cpp:2:
/home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:262:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^~~~
/home/daqin.luo.interns/project/AlphaPose-master/detector/nms/src/nms_cuda.cpp:4:23: error: ‘AT_CHECK’ was not declared in this scope
 #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                       ^
/home/daqin.luo.interns/project/AlphaPose-master/detector/nms/src/nms_cuda.cpp:4:23: note: in definition of macro ‘CHECK_CUDA’
 #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                       ^~~~~~~~
/home/daqin.luo.interns/project/AlphaPose-master/detector/nms/src/nms_cuda.cpp:4:23: note: suggested alternative: ‘DCHECK’
 #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                       ^
/home/daqin.luo.interns/project/AlphaPose-master/detector/nms/src/nms_cuda.cpp:4:23: note: in definition of macro ‘CHECK_CUDA’
 #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                       ^~~~~~~~
[2/2] /usr/local/cuda/bin/nvcc -I/home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/site-packages/torch/include -I/home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/site-packages/torch/include/TH -I/home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/daqin.luo.interns/anaconda3/envs/py3/include/python3.6m -c -c /home/daqin.luo.interns/project/AlphaPose-master/detector/nms/src/nms_kernel.cu -o /home/daqin.luo.interns/project/AlphaPose-master/build/temp.linux-x86_64-3.6/detector/nms/src/nms_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61 -std=c++14
/home/daqin.luo.interns/project/AlphaPose-master/detector/nms/src/nms_kernel.cu: In function ‘at::Tensor nms_cuda(at::Tensor, float)’:
/home/daqin.luo.interns/project/AlphaPose-master/detector/nms/src/nms_kernel.cu:72:62: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
   AT_ASSERTM(boxes.type().is_cuda(), "boxes must be a CUDA tensor");
                                                              ^
/home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:262:1: note: declared here
   DeprecatedTypeProperties & type() const {
 ^ ~~
/home/daqin.luo.interns/project/AlphaPose-master/detector/nms/src/nms_kernel.cu:81:50: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. [-Wdeprecated-declarations]
   scalar_t* boxes_dev = boxes_sorted.data<scalar_t>();
                                                  ^
/home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:341:1: note: declared here
   T * data() const {
 ^ ~~
/home/daqin.luo.interns/project/AlphaPose-master/detector/nms/src/nms_kernel.cu:109:46: warning: ‘T* at::Tensor::data() const [with T = long int]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. [-Wdeprecated-declarations]
   int64_t* keep_out = keep.data<int64_t>();
                                              ^
/home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:341:1: note: declared here
   T * data() const {
 ^ ~~

ninja: build stopped: subcommand failed.

Traceback (most recent call last):
  File "/home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1400, in _run_ninja_build
    check=True)
  File "/home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 211, in <module>
    zip_safe=False)
  File "/home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 87, in run
    _build_ext.run(self)
  File "/home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 580, in build_extensions
    build_ext.build_extensions(self)
  File "/home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 423, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1140, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/daqin.luo.interns/anaconda3/envs/py3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1413, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension

**Comment by tim20120526** [comment]
solved

**Comment by gosiqueira** [comment]
What did you do?

**Comment by lyrgwlr** [comment]
I met the same problem, how to solve it? @gosiqueira @tim20120526

**Comment by tim20120526** [comment]
@gosiqueira @lyrgwlr 
pytorch0.1.5->0.1.4.
torchvision->0.5.0.

**Comment by tim20120526** [comment]
@gosiqueira @lyrgwlr 
pytorch1.5.0->1.4.0
torchvision->0.5.0.

**Comment by gosiqueira** [comment]
Thank you, @tim20120526
