### ISSUE TITLE
TypeError: integer argument expected, got float

### ISSUE THREAD

**Issue by DanielRamosAcosta** [MVIG-SJTU/AlphaPose#6]
I' have followed the tutorial steps to test the demo but i'm getting the following error:

```
$ ./run.sh --indir examples/demo/ --outdir examples/results/ --vis
0
generating bbox from Faster RCNN...
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-02-05 20:54:09.837963: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
Loaded network ../output/res152/coco_2014_train+coco_2014_valminusminival/default/res152.ckpt
/home/daniel/Documentos/AlphaPose/examples/demo/

100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:48<00:00, 16.12s/it]
pose estimation with RMPE...
MPII	
 [======================================== 69/69 ======================================>]  Tot: 6s757ms | Step: 99ms    
----------Finished----------	
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
visualization...
  0%|                                                                                                            | 0/3 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "json-video.py", line 66, in <module>
    display_pose(inputpath, outputpath, imgname)    
  File "json-video.py", line 53, in display_pose
    fig.savefig(os.path.join(outputpath,'RENDER',imgname.split('/')[-1]),pad_inches = 0.0, bbox_inches=extent, dpi=12.91)
  File "/home/daniel/.local/lib/python2.7/site-packages/matplotlib/figure.py", line 1834, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/daniel/.local/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 2267, in print_figure
    **kwargs)
  File "/home/daniel/.local/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 584, in print_jpg
    return background.save(filename_or_obj, format='jpeg', **options)
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1675, in save
    save_handler(self, fp, filename)
  File "/usr/lib/python2.7/dist-packages/PIL/JpegImagePlugin.py", line 708, in _save
    ImageFile._save(im, fp, [("jpeg", (0, 0)+im.size, 0, rawmode)], bufsize)
  File "/usr/lib/python2.7/dist-packages/PIL/ImageFile.py", line 480, in _save
    e = Image._getencoder(im.mode, e, a, im.encoderconfig)
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 431, in _getencoder
    return encoder(mode, *args + extra)
TypeError: integer argument expected, got float
```

Sorry but I don't know very much about python its libs, does anyone know what's going on?

**Comment by DanielRamosAcosta** [comment]
I changed in [`json-video.py#L53`](https://github.com/MVIG-SJTU/AlphaPose/blob/master/predict/json/json-video.py#L53) the `dpi` parameter to `13` (instead of `12.97`) and now it has worked.

**Comment by Fang-Haoshu** [comment]
Thanks for your feedback! The code is updated
