### ISSUE TITLE
请问运行的时候，保存视频和图像遇到如下错误怎么办？

### ISSUE THREAD

**Issue by ShoiLyaung** [MVIG-SJTU/AlphaPose#659]
运行测试图片,成功输出json文件.
但加上--save_img保存图片后遇到如下问题:
python demo.py --indir examples/demo --outdir examples/res --save_img
Loading YOLO model..
Loading pose model from ./models/sppe/duc_se.pth
 33%|████████████████████████████                                                        | 1/3 [00:00<00:00,  3.09it/s]Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\Users\86177\anaconda3\envs\AlphaPose\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\86177\anaconda3\envs\AlphaPose\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\86177\AlphaPose\dataloader.py", line 675, in update
    img = vis_frame(orig_img, result)
  File "C:\Users\86177\AlphaPose\fn.py", line 140, in vis_frame_fast
    cv2.line(img, start_xy, end_xy, line_color[i], 2*(kp_scores[start_p] + kp_scores[end_p]) + 1)
_TypeError: Argument 'thickness' is required to be an integer_

100%|█████████████████████████████████████████████████████████ 100%|█████████████████████████████████████████████████████████ ███████████████████████████| 3/3 [00:01<00:00,  2.65it/s]
===========================> Finish Model Running.

之后一直卡在这步,ctrl C强制退出后显示
Traceback (most recent call last):
  File "demo.py", line 117, in <module>
    while(writer.running()):
  File "C:\Users\86177\AlphaPose\dataloader.py", line 688, in running
    time.sleep(0.2)
KeyboardInterrupt

运行视频时遇到类似的问题：

les/res --save_video
Loading YOLO model..
Loading pose model from ./models/sppe/duc_se.pth
  0%|▎                                                                                 | 1/225 [00:01<04:53,  1.31s/it]  1%|▋                                                                                 | 2/225 [00:01<04:00,  1.08s/it]Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\Users\86177\anaconda3\envs\AlphaPose\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\86177\anaconda3\envs\AlphaPose\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\86177\AlphaPose\dataloader.py", line 675, in update
    img = vis_frame(orig_img, result)
  File "C:\Users\86177\AlphaPose\fn.py", line 140, in vis_frame_fast
    cv2.line(img, start_xy, end_xy, line_color[i], 2*(kp_scores[start_p] + kp_scores[end_p]) + 1)
_TypeError: Argument 'thickness' is required to be an integer_

最终同样卡在最后一步,强制退出后显示
Traceback (most recent call last):
  File "video_demo.py", line 116, in <module>
    while(writer.running()):
  File "C:\Users\86177\AlphaPose\dataloader.py", line 688, in running
    time.sleep(0.2)
KeyboardInterrupt

**Comment by Fang-Haoshu** [comment]
File "C:\Users\86177\AlphaPose\fn.py", line 140, in vis_frame_fast
改成
cv2.line(img, start_xy, end_xy, line_color[i], 2*int(kp_scores[start_p] + kp_scores[end_p]) + 1)

**Comment by ShoiLyaung** [comment]
终于解决了。感谢！

**Comment by ShoiLyaung** [comment]
> File "C:\Users\86177\AlphaPose\fn.py", line 140, in vis_frame_fast
> 改成
> cv2.line(img, start_xy, end_xy, line_color[i], 2*int(kp_scores[start_p] + kp_scores[end_p]) + 1)

终于解决了，感谢！

**Comment by ShoiLyaung** [comment]
1.在vis_fast开启的情况下成功运行，但关了vis_fast之后又出现了错误
2.图片还是无法以图片形式显示结果报错：
Traceback (most recent call last):
  File "C:\Users\86177\anaconda3\envs\AlphaPose\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\86177\anaconda3\envs\AlphaPose\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\86177\AlphaPose\dataloader.py", line 675, in update
    img = vis_frame(orig_img, result)
  File "C:\Users\86177\AlphaPose\fn.py", line 198, in vis_frame
    img = cv2.addWeighted(bg, transparency, img, 1-transparency, 0)
TypeError: Argument 'alpha' can not be treated as a double

**Comment by Jerryzhangzhao** [comment]
Same error TypeError: Argument 'alpha' can not be treated as a double.
It should be a imcompatible problem with opencv-python, then I changed opencv-python from 4.4.0.46 to 4.1.0.25, and the problem solved.
