### ISSUE TITLE
1.在vis_fast开启的情况下成功运行，但关了vis_fast之后又出现了错误

### ISSUE THREAD

**Issue by ShoiLyaung** [MVIG-SJTU/AlphaPose#660]
1.在vis_fast开启的情况下成功运行，但关了vis_fast之后又出现了错误
2.图片还是无法以图片形式显示结果报错：
Traceback (most recent call last):
  File "C:\Users\86177\anaconda3\envs\AlphaPose\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\86177\anaconda3\envs\AlphaPose\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\86177\AlphaPose\dataloader.py", line 675, in update
    img = vis_frame(orig_img, result)
  File "C:\Users\86177\AlphaPose\fn.py", line 198, in vis_frame
    img = cv2.addWeighted(bg, transparency, img, 1-transparency, 0)
TypeError: Argument 'alpha' can not be treated as a double

_Originally posted by @ShoiLyaung in https://github.com/MVIG-SJTU/AlphaPose/issues/659#issuecomment-676447157_

**Comment by Fang-Haoshu** [comment]
img = cv2.addWeighted(bg, float(transparency), img, float(1-transparency), 0)

**Comment by Fang-Haoshu** [comment]
你好 我刚刚更新了一下代码 现在应该可以了
