### ISSUE TITLE
numpy.AxisError: axis 2 is out of bounds for array of dimension 2

### ISSUE THREAD

**Issue by athulvingt** [MVIG-SJTU/AlphaPose#664]
Traceback (most recent call last):
  File "./scripts/train.py", line 267, in <module>
    main()
  File "./scripts/train.py", line 224, in main
    gt_AP = validate_gt(m.module, opt, cfg, heatmap_to_coord)
  File "./scripts/train.py", line 158, in validate_gt
    keypoints = np.concatenate((pose_coords, pose_scores), axis=2)[0]
  File "<__array_function__ internals>", line 6, in concatenate
numpy.AxisError: axis 2 is out of bounds for array of dimension 2

**Comment by Fang-Haoshu** [comment]
fixed
