### ISSUE TITLE
NoneType' object has no attribute 'detector'

### ISSUE THREAD

**Issue by athulvingt** [MVIG-SJTU/AlphaPose#665]
Traceback (most recent call last):
  File "./scripts/train.py", line 262, in <module>
    main()
  File "./scripts/train.py", line 220, in main
    rcnn_AP = validate(m.module, opt, heatmap_to_coord)
  File "./scripts/train.py", line 86, in validate
    det_dataset = builder.build_dataset(cfg.DATASET.TEST, preset_cfg=cfg.DATA_PRESET, train=False)
  File "/content/AlphaPose/alphapose/models/builder.py", line 41, in build_dataset
    return build(cfg, DATASET, default_args=default_args)
  File "/content/AlphaPose/alphapose/models/builder.py", line 18, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/content/AlphaPose/alphapose/utils/registry.py", line 75, in build_from_cfg
    return obj_cls(**args)
  File "/content/AlphaPose/alphapose/datasets/coco_det.py", line 45, in __init__
    self.write_coco_json(det_file)
  File "/content/AlphaPose/alphapose/datasets/coco_det.py", line 91, in write_coco_json
    det_model = get_detector(self._opt)
  File "/content/AlphaPose/detector/apis.py", line 11, in get_detector
    if opt.detector == 'yolo':
AttributeError: 'NoneType' object has no attribute 'detector'

**Comment by Fang-Haoshu** [comment]
Hi, this bug should be fixed in the latest version. Maybe you revert the code to some point before?  
https://github.com/MVIG-SJTU/AlphaPose/blob/master/scripts/train.py#L85
