### ISSUE TITLE
AttributeError: module 'pycocotools._mask' has no attribute 'iou'

### ISSUE THREAD

**Issue by mulka-hop** [MVIG-SJTU/AlphaPose#666]
Getting this error when trying to run Alphapose.

Traceback (most recent call last):
  File "scripts/demo_inference.py", line 175, in <module>
    det_loader = DetectionLoader(input_source, get_detector(args), cfg, args, batchSize=args.detbatch, mode=mode, queueSize=args.qsize)
  File "/AlphaPose/alphapose/utils/detector.py", line 49, in __init__
    pose_dataset = builder.retrieve_dataset(self.cfg.DATASET.TRAIN)
  File "/AlphaPose/alphapose/models/builder.py", line 45, in retrieve_dataset
    exec(f'from ..datasets import {cfg.TYPE}')
  File "<string>", line 1, in <module>
  File "/AlphaPose/alphapose/datasets/__init__.py", line 3, in <module>
    from .custom import CustomDataset
  File "/AlphaPose/alphapose/datasets/custom.py", line 14, in <module>
    from pycocotools.coco import COCO
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/root/.local/share/virtualenvs/AlphaPose-3Cl233oL/lib/python3.6/site-packages/pycocotools-2.0.2a1-py3.6-linux-x86_64.egg/pycocotools/coco.py", line 55, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/root/.local/share/virtualenvs/AlphaPose-3Cl233oL/lib/python3.6/site-packages/pycocotools-2.0.2a1-py3.6-linux-x86_64.egg/pycocotools/mask.py", line 76, in <module>
AttributeError: module 'pycocotools._mask' has no attribute 'iou'

**Comment by Fang-Haoshu** [comment]
Hi! This is a bit weird 😂 Does this help? https://github.com/cocodataset/cocoapi/issues/65

**Comment by mulka-hop** [comment]
I guess I'm not sure where to locate coco/PythonAPI in order to run make on it. Seems weird that I would need to run make on a dependency to get AlphaPose to work.

**Comment by Fang-Haoshu** [comment]
Can you try python -m pip install pycocotools? Or maybe reinstall it

**Comment by mulka-hop** [comment]
Uninstalling then installing pycocotools fixed it. For some reason it was using the prerelease version 2.0.2a1. A pip install replaced that with 2.0.1

**Comment by Fang-Haoshu** [comment]
Oh I see. Glad to hear that
