### ISSUE TITLE
DLL load failed with Pyinstaller

### ISSUE THREAD

**Issue by YouMinJung** [MVIG-SJTU/AlphaPose#692]
I want to make .exe file in Windows 10.
so, I tried to use pyinstaller. (Pyinstaller Version : 4.0)

When I make exe file, I used this command.
**pyinstaller -F scripts/demo_inference.exe**

Pyinstalller makes exe file perfectly. (Pyinstaller said that INFO: Building EXE from EXE-00.toc completed successfully.)
However, when I executes this file with parameter, It failed to execute scripts.
Error message is like this,

**[16036] WARNING: file already exists but should not: C:\Users\MJ\AppData\Local\Temp\_MEI160362\torch\_C.cp37-win_amd64.pyd
Traceback (most recent call last):
  File "demo_inference.py", line 9, in <module>
  File "c:\users\mj\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "torch\__init__.py", line 81, in <module>
ImportError: DLL load failed: can't find module
[6980] Failed to execute script demo_inference**

I don't know how to solve this problem...
How can I solve this problem??
(Pytorch version : 1.2.0)

**Comment by Fang-Haoshu** [comment]
Hi, sorry that I am totally unfamiliar with pyinstaller... Any knows how to solve it?

**Comment by samylee** [comment]
hello guys, go and find c++ library: https://github.com/samylee/SamyleePoseApi-OpenLibrary
