### ISSUE TITLE
Inference do not work 

### ISSUE THREAD

**Issue by mstc-xqp** [MVIG-SJTU/AlphaPose#697]
hi!!

  File "/home/xian/peng/DepthPose-master/alphapose/models/layers/dcn/deform_conv.py", line 9, in <module>
    from . import deform_conv_cuda
ImportError: libcudart.so.10.0: cannot open shared object file: No such file or directory

**Comment by Fang-Haoshu** [comment]
hi, make sure the cuda path is set correctly

**Comment by mstc-xqp** [comment]
我的是cuda 10.1&nbsp; 不是10.0跑其它是可以的 是因为版本问题吗 但是cuda不是向下兼容吗

---Original---

**Comment by Fang-Haoshu** [comment]
不是版本问题 是编译问题或者路径问题 要是跑其他的可以推荐用其他的模型

**Comment by Wilfred-Yang** [comment]
Hi, 我也碰到相同的問題，我也是用cuda10.1，但結果也跟 @mstc-xqp 相同，請問@mstc-xqp 有找到解決辦法了嗎？

**Comment by wwdok** [comment]
我也碰到了同样的问题:
```
(base) weidawang@weidawang-TUF-Gaming-FX506LU-FX506LU:~/Repo/AlphaPose$ python scripts/demo_inference.py --cfg configs/coco/resnet/256x192_res152_lr1e-3_1x-duc.yaml --checkpoint pretrained_models/fast_421_res152_256x192.pth --video examples/videolib_repo_1905_14_6mudqe76l_SD_6mudqe76l-mobile.mp4 --outdir examples/res --detector yolo --save_img --save_video
Traceback (most recent call last):
  File "scripts/demo_inference.py", line 17, in <module>
    from alphapose.models import builder
  File "/home/weidawang/Repo/AlphaPose/alphapose/models/__init__.py", line 1, in <module>
    from .fastpose import FastPose
  File "/home/weidawang/Repo/AlphaPose/alphapose/models/fastpose.py", line 10, in <module>
    from .layers.SE_Resnet import SEResnet
  File "/home/weidawang/Repo/AlphaPose/alphapose/models/layers/SE_Resnet.py", line 9, in <module>
    from .dcn import DeformConv, ModulatedDeformConv
  File "/home/weidawang/Repo/AlphaPose/alphapose/models/layers/dcn/__init__.py", line 1, in <module>
    from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv,
  File "/home/weidawang/Repo/AlphaPose/alphapose/models/layers/dcn/deform_conv.py", line 9, in <module>
    from . import deform_conv_cuda
ImportError: libcudart.so.10.0: cannot open shared object file: No such file or directory
```
![image](https://user-images.githubusercontent.com/43233772/103975651-9b34fd80-51af-11eb-9d1d-91e6a879be57.png)

我的cuda是10.2, 我有libcudart.so.10.2, 但没有libcudart.so.10.0, 这样可以吗

**Comment by PEACEandSAFE** [comment]
你好 请问这个问题解决了吗  我更新了pytorch版本后也遇到这个问题了
