### ISSUE TITLE
quickstart not working

### ISSUE THREAD

**Issue by wiwengweng** [MVIG-SJTU/AlphaPose#72]
Hi, I just found a issue when doing a quick start with tensorflow 1.8 cpu version.

````
andes@inspiron:~/PycharmProjects/AlphaPose-master$ ./run.sh --indir examples/demo/ --outdir examples/results/ --vis
0
generating bbox from Faster RCNN...
/home/andes/.local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-06-21 05:14:23.307185: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Loaded network ../output/res152/coco_2014_train+coco_2014_valminusminival/default/res152.ckpt
/home/andes/PycharmProjects/AlphaPose-master/examples/demo/

  0%|                                                     | 0/3 [00:00<?, ?it/s]unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
 33%|███████████████                              | 1/3 [00:25<00:50, 25.10s/it]unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
 67%|██████████████████████████████               | 2/3 [00:50<00:25, 25.02s/it]unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
unknown error
100%|█████████████████████████████████████████████| 3/3 [01:14<00:00, 24.98s/it]
pose estimation with RMPE...
/home/andes/torch/install/bin/luajit: /home/andes/torch/install/share/lua/5.1/trepl/init.lua:389: /home/andes/torch/install/share/lua/5.1/hdf5/ffi.lua:71: Unsupported HDF5 version: 1.10.0
stack traceback:
	[C]: in function 'error'
	/home/andes/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	.../andes/PycharmProjects/AlphaPose-master/predict/util.lua:7: in main chunk
	[C]: in function 'dofile'
	main-alpha-pose.lua:7: in main chunk
	[C]: in function 'dofile'
	...ndes/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x561feac3d560
/home/andes/.local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "parametric-pose-nms-MPII.py", line 256, in <module>
    get_result_json(args)
  File "parametric-pose-nms-MPII.py", line 243, in get_result_json
    test_parametric_pose_NMS_json(delta1, delta2, mu, gamma,args.outputpath)
  File "parametric-pose-nms-MPII.py", line 99, in test_parametric_pose_NMS_json
    h5file = h5py.File(os.path.join(outputpath,"POSE/test-pose.h5"), 'r')
  File "/home/andes/.local/lib/python2.7/site-packages/h5py/_hl/files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/andes/.local/lib/python2.7/site-packages/h5py/_hl/files.py", line 99, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
IOError: Unable to open file (unable to open file: name = '/home/andes/PycharmProjects/AlphaPose-master/examples/results/POSE/test-pose.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
visualization...
Traceback (most recent call last):
  File "json-video.py", line 63, in <module>
    with open(jsonpath) as f:
IOError: [Errno 2] No such file or directory: '/home/andes/PycharmProjects/AlphaPose-master/examples/results/POSE/alpha-pose-results-forvis.json'
````

**Comment by Fang-Haoshu** [comment]
lua:389: /home/andes/torch/install/share/lua/5.1/hdf5/ffi.lua:71: Unsupported HDF5 version: 1.10.0
Try another HDF5 version?
