### ISSUE TITLE
AlphaPose\detector\nms\src\nms_cuda.cpp(9): error C3861: “AT_CHECK”: identifier not found

### ISSUE THREAD

**Issue by wwdok** [MVIG-SJTU/AlphaPose#725]
When i run `python setup.py build develop` to install alphapose on windows 10 , error happens:

```
D:\Repo\PoseEstimation\AlphaPose\detector\nms\src\nms_cuda.cpp(9): error C3861: “AT_CHECK”: identifier not found
[2/2] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -IC:\ProgramData\Anaconda3\lib\site-packages\torch\include -IC:\ProgramData\Anaconda3\lib\site-packages\torch\include\torch\csrc\api\include -IC:\ProgramData\Anaconda3\lib\site-packages\torch\include\TH -IC:\ProgramData\Anaconda3\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -IC:\ProgramData\Anaconda3\include -IC:\ProgramData\Anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" -c D:\Repo\PoseEstimation\AlphaPose\detector\nms\src\nms_kernel.cu -o D:\Repo\PoseEstimation\AlphaPose\build\temp.win-amd64-3.8\Release\detector\nms\src/nms_kernel.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75
C:/ProgramData/Anaconda3/lib/site-packages/torch/include\c10/util/ThreadLocalDebugInfo.h(12): warning: modifier is ignored on an enum specifier

C:/ProgramData/Anaconda3/lib/site-packages/torch/include\c10/util/ThreadLocalDebugInfo.h(12): warning: modifier is ignored on an enum specifier

nms_kernel.cu
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1516, in _run_ninja_build
    subprocess.run(
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 186, in <module>
    setup(
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "C:\ProgramData\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Anaconda3\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "C:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "C:\ProgramData\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\ProgramData\Anaconda3\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 653, in build_extensions
    build_ext.build_extensions(self)
  File "C:\ProgramData\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "C:\ProgramData\Anaconda3\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "C:\ProgramData\Anaconda3\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\ProgramData\Anaconda3\lib\distutils\command\build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 626, in win_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1233, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1538, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```

**Comment by Fang-Haoshu** [comment]
Hi, windows does not support cuda. They should not be compiled

**Comment by wwdok** [comment]
> Hi, windows does not support cuda. They should not be compiled

Then what should i do, is there a way to fix it ?

**Comment by dbgns** [comment]
> > Hi, windows does not support cuda. They should not be compiled
> 
> Then what should i do, is there a way to fix it ?

you can try to replace all `AT_CHECK` with `TORCH_CHECK` in cpp files, which should work with higher versions of pytorch

**Comment by wwdok** [comment]
> > > Hi, windows does not support cuda. They should not be compiled
> > 
> > 
> > Then what should i do, is there a way to fix it ?
> 
> you can try to replace all `AT_CHECK` with `TORCH_CHECK` in cpp files, which should work with higher versions of pytorch

Wow, you are so great, it worked like a charm ! this error has gone away ! But there is still a small version as below, how to solve it  ? 
![image](https://user-images.githubusercontent.com/43233772/98493659-f3b25200-2275-11eb-90c5-43786973bf45.png)

**Comment by dbgns** [comment]
> > > > Hi, windows does not support cuda. They should not be compiled
> > > 
> > > 
> > > Then what should i do, is there a way to fix it ?
> > 
> > 
> > you can try to replace all `AT_CHECK` with `TORCH_CHECK` in cpp files, which should work with higher versions of pytorch
> 
> @dbgns, Wow, you are so great, it worked like a charm ! this error has gone away ! But there is still a small version error as below, how to solve it ?
> ![image](https://user-images.githubusercontent.com/43233772/98493659-f3b25200-2275-11eb-90c5-43786973bf45.png)

It seems that alphapose is already installed and the setup script is checking out the requirements.  Maybe you can downgrade your torch to 1.4.0 simply by `pip install torch==1.4.0`. If you want to keep torch 1.7, you should install corresponding torchvision  by `pip install torchvision==0.8.0`

**Comment by wwdok** [comment]
@dbgns  Successfully Installed on Windows ！Many thanks ！

**Comment by samylee** [comment]
hello guys, go and find c++ library: https://github.com/samylee/SamyleePoseApi-OpenLibrary
