### ISSUE TITLE
windows training error

### ISSUE THREAD

**Issue by Ronglongzhou** [MVIG-SJTU/AlphaPose#729]
hello,everyone！when i trained alphapose on windows env，i meet question as following, Has anyone ever met the same problem? I hope you can help me solve it. Thank you very much!
############# Starting Epoch 0 | LR: 0.001 #############
  0%|                                                                                        | 0/18053 [00:00<?, ?it/s]Traceback (most recent call last):
  File "./scripts/train.py", line 268, in <module>
    main()
  File "./scripts/train.py", line 215, in main
    loss, miou = train(opt, train_loader, m, criterion, optimizer, writer)
  File "./scripts/train.py", line 34, in train
    for i, (inps, labels, label_masks, _, bboxes) in enumerate(train_loader):
  File "c:\programdata\anaconda3\envs\alphapose\lib\site-packages\tqdm\_tqdm.py", line 380, in __iter__
    for obj in iterable:
  File "c:\programdata\anaconda3\envs\alphapose\lib\site-packages\torch\utils\data\dataloader.py", line 345, in __next__
    data = self._next_data()
  File "c:\programdata\anaconda3\envs\alphapose\lib\site-packages\torch\utils\data\dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "c:\programdata\anaconda3\envs\alphapose\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "c:\programdata\anaconda3\envs\alphapose\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "c:\design\gesture recognition\alphapose-master\alphapose\datasets\custom.py", line 95, in __getitem__
    img_id = int(os.path.splitext(os.path.basename(img_path))[0])
  File "C:\ProgramData\Anaconda3\envs\AlphaPose\lib\ntpath.py", line 214, in basename
    return split(p)[1]
  File "C:\ProgramData\Anaconda3\envs\AlphaPose\lib\ntpath.py", line 183, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not dict

**Comment by Fang-Haoshu** [comment]
Hi, windows environment is usually buggy for training. We suggest using linux.
