### ISSUE TITLE
cannot import name 'deform_conv_cuda' from 'alphapose.models.layers.dcn

### ISSUE THREAD

**Issue by futureflsl** [MVIG-SJTU/AlphaPose#730]
win10  pytorch1.2,error like this:
Traceback (most recent call last):
  File "scripts/demo_inference.py", line 17, in <module>
    from alphapose.models import builder
  File "e:\ai\alphapose-master\alphapose\models\__init__.py", line 1, in <module>
    from .fastpose import FastPose
  File "e:\ai\alphapose-master\alphapose\models\fastpose.py", line 10, in <module>
    from .layers.SE_Resnet import SEResnet
  File "e:\ai\alphapose-master\alphapose\models\layers\SE_Resnet.py", line 9, in <module>
    from .dcn import DeformConv, ModulatedDeformConv
  File "e:\ai\alphapose-master\alphapose\models\layers\dcn\__init__.py", line 1, in <module>
    from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv,
  File "e:\ai\alphapose-master\alphapose\models\layers\dcn\deform_conv.py", line 9, in <module>
    from . import deform_conv_cuda
ImportError: cannot import name 'deform_conv_cuda' from 'alphapose.models.layers.dcn' (e:\ai\alphapose-master\alphapose\models\layers\dcn\__init__.py)

I saw so many issue,but they could not help me

**Comment by futureflsl** [comment]
force_compile = True , I solved it

**Comment by Usopp-sun** [comment]
> force_compile = True , I solved it

please tell me which python file you modified?

**Comment by kkk-g-y** [comment]
> > force_compile = True , I solved it
> 
> please tell me which python file you modified?

setup.py    line  124

**Comment by SCP-KAKA** [comment]
Does this method work? I deleted setup.py line 211, and modified line 124: force_compile=True, Re-execute 'python setup.py build develop', but the problem still exists.

**Comment by koalaaaaaaaaa** [comment]
@SCP-KAKA 
if you use cpu, then:
you may comment or delete line2-7 in alphapose/models/init.py
for these lines will use extension modules built by "ext_modoule = get_ext_modoule()", which you've deleted before.
if you use gpu, sorry i face the same problem
