### ISSUE TITLE
Running the train.py is reported RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 2)

### ISSUE THREAD

**Issue by Jusec** [MVIG-SJTU/AlphaPose#745]
I am using python 3.6.12 and torch==0.4.0 and torchvision==0.2.0
I changed num_workers in dataloader on line 154 of train.py to 0
The error is on line 142 of the img.py： img[:, :ul[1], :], img[:, :, :ul[0]] = 0, 0   

Traceback (most recent call last):
  File "D:/Programming/JetBrains Workspace/PyCharm-P Workspace/ai/AlphaPose/train_sppe/src/train.py", line 249, in <module>
    main()
  File "D:/Programming/JetBrains Workspace/PyCharm-P Workspace/ai/AlphaPose/train_sppe/src/train.py", line 207, in main
    loss, acc = train(train_loader, m, criterion, optimizer, writer)
  File "D:/Programming/JetBrains Workspace/PyCharm-P Workspace/ai/AlphaPose/train_sppe/src/train.py", line 30, in train
    for i, (inps, labels, setMask, imgset) in enumerate(train_loader_desc):
  File "C:\Users\Mo\.conda\envs\alphapose\lib\site-packages\tqdm\std.py", line 1171, in __iter__
    for obj in iterable:
  File "C:\Users\Mo\.conda\envs\alphapose\lib\site-packages\torch\utils\data\dataloader.py", line 264, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "C:\Users\Mo\.conda\envs\alphapose\lib\site-packages\torch\utils\data\dataloader.py", line 264, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "D:\Programming\JetBrains Workspace\PyCharm-P Workspace\ai\AlphaPose\train_sppe\src\utils\dataset\coco.py", line 69, in __getitem__
    'coco', sf, self, train=self.is_train)
  File "D:\Programming\JetBrains Workspace\PyCharm-P Workspace\ai\AlphaPose\train_sppe\src\utils\pose.py", line 109, in generateSampleBox
    inp = cropBox(img, upLeft, bottomRight, inputResH, inputResW)
  File "D:\Programming\JetBrains Workspace\PyCharm-P Workspace\ai\AlphaPose\train_sppe\src\utils\img.py", line 147, in cropBox
    img[:, :ul[1], :], img[:, :, :ul[0]] = 0, 0
RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 2)

**Comment by Jusec** [comment]
I changed num_workers in dataloader on line 154 of train.py to 0
If you don't modify this, you will report BrokenPipeError: [Errno 32] Broken pipe

**Comment by Fang-Haoshu** [comment]
Hi，is it because of the pytorch version? Does it occurs if using pytorch 1.1+?

**Comment by Jusec** [comment]
> Hi，is it because of the pytorch version? Does it occurs if using pytorch 1.1+?
Yes , using pytorch 1.1+  will not  occur this error

**Comment by Fang-Haoshu** [comment]
Oh I see. Thanks
