### ISSUE TITLE
img.py and opt.py How should it be modified?  img.py and opt.py In the train_sppe/src/predict

### ISSUE THREAD

**Issue by Jusec** [MVIG-SJTU/AlphaPose#748]
if it is not modified it will be reported SyntaxError: invalid syntax
Traceback (most recent call last):
  File "C:/software_311/Mo/AlphaPose-pytorch/train_sppe/src/train.py", line 14, in <module>
    from train_sppe.src.evaluation import prediction
  File "C:\software_311\Mo\AlphaPose-pytorch\train_sppe\src\evaluation.py", line 12, in <module>
    from predict.opt import opt
  File "C:\software_311\Mo\AlphaPose-pytorch\train_sppe\src\predict\opt.py", line 1
    ../opt.py
    ^
SyntaxError: invalid syntax

opt.py 'content is ../opt.py
img.py 'content is../utils/img.py

**Comment by 18098329072** [comment]
Hi, I also encountered this problem. Have you solved it？

**Comment by zxwblublu** [comment]
> Hi, I also encountered this problem. Have you solved it？

I also ran into this problem .Have you solved it？
