### ISSUE TITLE
fine-tune own datasets

### ISSUE THREAD

**Issue by shelly-xue** [MVIG-SJTU/AlphaPose#775]
Hello, thank you for your open code. I want to fine tune my data set and mark 17 key points like coco. After generating the JSON file, I modified the cfg file and started training. I encountered the following problems:

json.decoder.JSONDecodeError : Invalid control character at: line 1 column 3 (char 2)

Excuse me, what is the cause?

**Comment by Fang-Haoshu** [comment]
Your json file may have some problem. You need to check your json file. This is the json reading problem

**Comment by shelly-xue** [comment]
OK, thank you for your reply! Excuse me，in file custom.py function 

def _ load_ jsons(self):

pass

Why is it empty? Do I need to supplement myself? thanks a lot.

**Comment by shelly-xue** [comment]
Hello, I've checked a lot and haven't solved it yet. My JSON file is obtained through the coco annotator tool. I have seen that the key fields are the same as the JSON fields in coco format. Excuse me, can the JSON obtained in this way be directly used for training. Hope to get your reply, thank you very much

**Comment by shelly-xue** [comment]
Thank you for your reply. The problem of JSON reading has been solved. I hope you can reply. Thank you:

100%|█████████████████████████████████████████████████████████████████████████████████████████████| 35/35 [00:06<00:00,  5.42it/s]
Traceback (most recent call last):
  File "./scripts/train.py", line 272, in <module>
    main()
  File "./scripts/train.py", line 229, in main
    gt_AP = validate_gt(m.module, opt, cfg, heatmap_to_coord)
  File "./scripts/train.py", line 172, in validate_gt
    res = evaluate_mAP(os.path.join(opt.work_dir, 'test_gt_kpt.json'), ann_type='keypoints')
  File "/home/test/PycharmProjects/AlphaPose/alphapose/utils/metrics.py", line 96, in evaluate_mAP
    cocoDt = cocoGt.loadRes(res_file)
  File "/home/test/anaconda3/envs/alphapose/lib/python3.6/site-packages/pycocotools-2.0.2-py3.6-linux-x86_64.egg/pycocotools/coco.py", line 327, in loadRes
    'Results do not correspond to current coco set'
AssertionError: Results do not correspond to current coco set
Exception ignored in: <alphapose.utils.metrics.evaluate_mAP.<locals>.NullWriter object at 0x7fb562b40ba8>
AttributeError: 'NullWriter' object has no attribute 'flush'

**Comment by shelly-xue** [comment]
Thank you for your reply. The problem of JSON reading has been solved. This is a problem in training. Looking forward to your suggestion, thank you very much.

100%|█████████████████████████████████████████████████████████████████████████████████████████████| 35/35 [00:06<00:00,  5.42it/s]
Traceback (most recent call last):
  File "./scripts/train.py", line 272, in <module>
    main()
  File "./scripts/train.py", line 229, in main
    gt_AP = validate_gt(m.module, opt, cfg, heatmap_to_coord)
  File "./scripts/train.py", line 172, in validate_gt
    res = evaluate_mAP(os.path.join(opt.work_dir, 'test_gt_kpt.json'), ann_type='keypoints')
  File "/home/test/PycharmProjects/AlphaPose/alphapose/utils/metrics.py", line 96, in evaluate_mAP
    cocoDt = cocoGt.loadRes(res_file)
  File "/home/test/anaconda3/envs/alphapose/lib/python3.6/site-packages/pycocotools-2.0.2-py3.6-linux-x86_64.egg/pycocotools/coco.py", line 327, in loadRes
    'Results do not correspond to current coco set'
AssertionError: Results do not correspond to current coco set
Exception ignored in: <alphapose.utils.metrics.evaluate_mAP.<locals>.NullWriter object at 0x7fb562b40ba8>
AttributeError: 'NullWriter' object has no attribute 'flush'
@Fang-Haoshu

**Comment by shelly-xue** [comment]
@Fang-Haoshu 
hi！Sorry to disturb you again. I use the coco dataset and follow the readme.txt file  proposed training mode.The following problems appear :

100%|████████████████████████████████████████████████████████████████████████████████████████████| 69/69 [00:12<00:00,  5.57it/s]
Will create detection results to ./exp/json/test_det_yolo.json
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
  0%|                                                                                                      | 0/9 [00:00<?, ?it/s]Loading YOLO model..
  0%|                                                                                                      | 0/9 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "./scripts/train.py", line 294, in <module>
    main()
  File "./scripts/train.py", line 252, in main
    rcnn_AP = validate(m.module, opt, heatmap_to_coord)
  File "./scripts/train.py", line 85, in validate
    det_dataset = builder.build_dataset(cfg.DATASET.TEST, preset_cfg=cfg.DATA_PRESET, train=False, opt=opt)
  File "/home/test/PycharmProjects/AlphaPose/alphapose/models/builder.py", line 53, in build_dataset
    return build(cfg, DATASET, default_args=default_args)
  File "/home/test/PycharmProjects/AlphaPose/alphapose/models/builder.py", line 21, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/test/PycharmProjects/AlphaPose/alphapose/utils/registry.py", line 81, in build_from_cfg
    return obj_cls(**args)
  File "/home/test/PycharmProjects/AlphaPose/alphapose/datasets/coco_det.py", line 45, in __init__
    self.write_coco_json(det_file)
  File "/home/test/PycharmProjects/AlphaPose/alphapose/datasets/coco_det.py", line 96, in write_coco_json
    det = det_model.detect_one_img(abs_path)
  File "/home/test/PycharmProjects/AlphaPose/detector/yolo_api.py", line 253, in detect_one_img
    self.load_model()
  File "/home/test/PycharmProjects/AlphaPose/detector/yolo_api.py", line 48, in load_model
    self.model = Darknet(self.model_cfg)
  File "/home/test/PycharmProjects/AlphaPose/detector/yolo/darknet.py", line 306, in __init__
    self.blocks = parse_cfg(cfgfile)
  File "/home/test/PycharmProjects/AlphaPose/detector/yolo/darknet.py", line 67, in parse_cfg
    key,value = line.split("=")
ValueError: too many values to unpack (expected 2)

Looking forward to your reply, thank you very much!
