### ISSUE TITLE
Install error Linux 20.04 cuda 10.1

### ISSUE THREAD

**Issue by connor-john** [MVIG-SJTU/AlphaPose#782]
Hello getting an error during the final installation step `python setup.py build develop`

```1/1] Cythonizing detector/nms/src/soft_nms_cpu.pyx
running build
running build_py
copying alphapose/version.py -> build/lib.linux-x86_64-3.7/alphapose
running build_ext
building 'detector.nms.soft_nms_cpu' extension
Traceback (most recent call last):
  File "setup.py", line 213, in <module>
    zip_safe=False)
  File "/home/connor/anaconda3/envs/alpha/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/connor/anaconda3/envs/alpha/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/connor/anaconda3/envs/alpha/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/connor/anaconda3/envs/alpha/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/connor/anaconda3/envs/alpha/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/connor/anaconda3/envs/alpha/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/connor/anaconda3/envs/alpha/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/connor/anaconda3/envs/alpha/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/connor/anaconda3/envs/alpha/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/connor/anaconda3/envs/alpha/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/connor/anaconda3/envs/alpha/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 670, in build_extensions
    build_ext.build_extensions(self)
  File "/home/connor/anaconda3/envs/alpha/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/home/connor/anaconda3/envs/alpha/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/connor/anaconda3/envs/alpha/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/connor/anaconda3/envs/alpha/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/connor/anaconda3/envs/alpha/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/home/connor/anaconda3/envs/alpha/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 500, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/connor/anaconda3/envs/alpha/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1231, in _write_ninja_file_and_compile_objects
    check_compiler_abi_compatibility(compiler)
  File "/home/connor/anaconda3/envs/alpha/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 265, in check_compiler_abi_compatibility
    if not check_compiler_ok_for_platform(compiler):
  File "/home/connor/anaconda3/envs/alpha/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 225, in check_compiler_ok_for_platform
    which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
  File "/home/connor/anaconda3/envs/alpha/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/home/connor/anaconda3/envs/alpha/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['which', 'c++']' returned non-zero exit status 1.
```

Pytorch 1.7.1
Cuda 10.1
g++ 8.4
Python 3.7

I have tried to install from start twice, my cuda works, my c++ works (compiling with g++) all in this environment.

I have pulled the branch necessary for pytorch 1.7.1

My issue seems to only be with setting up AlphaPose.
Any help is appreciated,

Thanks

**Comment by Fang-Haoshu** [comment]
Hi, can you type ``which c++``  in the shell and check the output? It seems it is related to this problem

**Comment by connor-john** [comment]
Closing this. I can't replicate this issue after creating a new linux environment. 

Thanks.
