### ISSUE TITLE
RuntimeError: shape '[255, 256, 1, 1]' is invalid for input of size 64796

### ISSUE THREAD

**Issue by yeonchae** [MVIG-SJTU/AlphaPose#784]
Hello guys, thanks for visiting this issue. 

I've got the error as below:

RuntimeError: shape '[255, 256, 1, 1]' is invalid for input of size 64796

However, I've already modified the config file as 256X192.
I've run the fast_resnet model as below. 

Actually, I have no idea with the error.

Any comment would be greatly appreciated. 

Thanks a lot. 

(alphapose) yeonchae@snucem:~/anaconda3/envs/alphapose/AlphaPose$ python scripts/demo_inference.py --cfg configs/halpe_26/resnet/256x192_res50_lr1e-3_1x.yaml --checkpoint pretrained_models/halpe26_fast_res50_256x192.pth --indir examples/demo/ --save_img
Corrupt JPEG data: 3 extraneous bytes before marker 0xd9
Corrupt JPEG data: 3 extraneous bytes before marker 0xd9
Loading YOLO model..
Loading pose model from pretrained_models/halpe26_fast_res50_256x192.pth...
Process Process-2:
Traceback (most recent call last):
  File "/home/yeonchae/anaconda3/envs/alphapose/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/yeonchae/anaconda3/envs/alphapose/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yeonchae/anaconda3/envs/alphapose/AlphaPose/alphapose/utils/detector.py", line 223, in image_detection
    dets = self.detector.images_detection(imgs, im_dim_list)
  File "/home/yeonchae/anaconda3/envs/alphapose/AlphaPose/detector/yolo_api.py", line 91, in images_detection
    self.load_model()
  File "/home/yeonchae/anaconda3/envs/alphapose/AlphaPose/detector/yolo_api.py", line 49, in load_model
    self.model.load_weights(self.model_weights)
  File "/home/yeonchae/anaconda3/envs/alphapose/AlphaPose/detector/yolo/darknet.py", line 488, in load_weights
    conv_weights = conv_weights.view_as(conv.weight.data)
RuntimeError: shape '[255, 256, 1, 1]' is invalid for input of size 64796

**Comment by Fang-Haoshu** [comment]
Hi, I am not sure what happened. I suggest using the original config
