### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (136,) (17,) 

### ISSUE THREAD

**Issue by sid0407** [MVIG-SJTU/AlphaPose#793]
Create new model
=> init weights
loading annotations into memory...
Done (t=2.78s)
creating index...
index created!
############# Starting Epoch 0 | LR: 0.001 #############
loss: 10.93754820 | acc: 0.4933: 100%|████████████████████████████████████████████████████████████████████████████████████████████████| 3009/3009 [1:23:12<00:00,  1.66s/it]
Train-0 epoch | loss:10.93754820 | acc:0.4933
loading annotations into memory...
Done (t=0.67s)
creating index...
index created!
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 293/293 [01:54<00:00,  2.56it/s]
Traceback (most recent call last):
  File "./scripts/train.py", line 267, in <module>
    main()
  File "./scripts/train.py", line 224, in main
    gt_AP = validate_gt(m.module, opt, cfg, heatmap_to_coord)
  File "./scripts/train.py", line 172, in validate_gt
    res = evaluate_mAP(os.path.join(opt.work_dir, 'test_gt_kpt.json'), ann_type='keypoints', ann_file=os.path.join(cfg.DATASET.VAL.ROOT, cfg.DATASET.VAL.ANN))
  File "/scratch/ee/btech/ee3180565/AlphaPose/alphapose/utils/metrics.py", line 101, in evaluate_mAP
    cocoEval.evaluate()
  File "/home/ee/btech/ee3180565/.conda/envs/alphapose/lib/python3.6/site-packages/pycocotools-2.0.0-py3.6-linux-x86_64.egg/pycocotools/cocoeval.py", line 150, in evaluate
    for imgId in p.imgIds
  File "/home/ee/btech/ee3180565/.conda/envs/alphapose/lib/python3.6/site-packages/pycocotools-2.0.0-py3.6-linux-x86_64.egg/pycocotools/cocoeval.py", line 151, in <dictcomp>
    for catId in catIds}
  File "/home/ee/btech/ee3180565/.conda/envs/alphapose/lib/python3.6/site-packages/pycocotools-2.0.0-py3.6-linux-x86_64.egg/pycocotools/cocoeval.py", line 230, in computeOks
    e = (dx**2 + dy**2) / vars / (gt['area']+np.spacing(1)) / 2
ValueError: operands could not be broadcast together with shapes (136,) (17,) 

I got this error, I am training the Halpe_136 dataset. Please help.

**Comment by Fang-Haoshu** [comment]
You used the wrong config. Please used the config of halpe136

**Comment by fairleehu** [comment]
> You used the wrong config. Please used the config of halpe136

but i'm sure use the config of halpe136. i got the same error.

File "/home/ee/btech/ee3180565/.conda/envs/alphapose/lib/python3.6/site-packages/pycocotools-2.0.0-py3.6-linux-x86_64.egg/pycocotools/cocoeval.py", line 230, in computeOks
e = (dx2 + dy2) / vars / (gt['area']+np.spacing(1)) / 2
ValueError: operands could not be broadcast together with shapes (136,) (17,)

how can i resolve it
