### ISSUE TITLE
demo error --save video

### ISSUE THREAD

**Issue by armornik** [MVIG-SJTU/AlphaPose#809]
use --sp, have infinity loop. Use collab My error:
===========================> Finish Model Running.
===========================> Rendering remaining images in the queue...
===========================> If this step takes too long, you can enable the --vis_fast flag to use fast rendering (real-time).
Traceback (most recent call last):
  File "scripts/demo_inference.py", line 226, in <module>
    (inps, orig_img, im_name, boxes, scores, ids, cropped_boxes) = det_loader.read()
  File "/content/AlphaPose/alphapose/utils/detector.py", line 269, in read
    return self.wait_and_get(self.pose_queue)
  File "/content/AlphaPose/alphapose/utils/detector.py", line 121, in wait_and_get
    return queue.get()
  File "/usr/lib/python3.6/queue.py", line 164, in get
    self.not_empty.wait()
  File "/usr/lib/python3.6/threading.py", line 295, in wait
    waiter.acquire()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/demo_inference.py", line 288, in <module>
    writer.stop()
  File "/content/AlphaPose/alphapose/utils/writer.py", line 181, in stop
    self.result_worker.join()
  File "/usr/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
Results have been written to json.

**Comment by Fang-Haoshu** [comment]
Hi, it shouldn't have such problems, can you try some other videos? 
And can you also try the demo_api.py in the script folder?

**Comment by armornik** [comment]
Some videos are processed correctly, and some with this problem. I don't understand, is this a problem with the video, or with something else? All videos were shot on one phone.

**Comment by Fang-Haoshu** [comment]
I think it is related to opencv. We used opencv to decode the video and check its length. You can try updating the opencv version.
