### ISSUE TITLE
ImportError: libtorch.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Du-Yao** [MVIG-SJTU/AlphaPose#832]
When I ran the code, everything was ok but there was a problem. I don't know how to solve it.
pytorch version is 1.1.0

'''
Traceback (most recent call last):
  File "./scripts/demo_inference.py", line 175, in <module>
    det_loader = DetectionLoader(input_source, get_detector(args), cfg, args, batchSize=args.detbatch, mode=mode, queueSize=args.qsize)
  File "/home/duyaoo/xp/AlphaPose/detector/apis.py", line 12, in get_detector
    from detector.yolo_api import YOLODetector
  File "/home/duyaoo/xp/AlphaPose/detector/yolo_api.py", line 27, in <module>
    from detector.nms import nms_wrapper
  File "/home/duyaoo/xp/AlphaPose/detector/nms/__init__.py", line 1, in <module>
    from .nms_wrapper import nms, soft_nms
  File "/home/duyaoo/xp/AlphaPose/detector/nms/nms_wrapper.py", line 4, in <module>
    from . import nms_cpu, nms_cuda
ImportError: libtorch.so: cannot open shared object file: No such file or directory
'''
Please help me solve it, thanks!

**Comment by hhh-old** [comment]
i try this and it work:
   rm -r build
   python setup.py develop

**Comment by Youthfeng123** [comment]
> i try this and it work: rm -r build python setup.py develop

thanks a lot!
