### ISSUE TITLE
Ubuntu 18 setup.py build develop error

### ISSUE THREAD

**Issue by hwk0809** [MVIG-SJTU/AlphaPose#838]
Traceback (most recent call last):
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 160, in run
    self.run_command("egg_info")
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 280, in run
    self.find_sources()
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 295, in find_sources
    mm.run()
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 526, in run
    self.add_defaults()
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 562, in add_defaults
    sdist.add_defaults(self)
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/command/py36compat.py", line 34, in add_defaults
    self._add_defaults_python()
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/command/sdist.py", line 135, in _add_defaults_python
    self.filelist.extend(build_py.get_source_files())
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/distutils/command/build_py.py", line 301, in get_source_files
    return [module[-1] for module in self.find_all_modules()]
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/distutils/command/build_py.py", line 296, in find_all_modules
    m = self.find_package_modules(package, package_dir)
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/distutils/command/build_py.py", line 218, in find_package_modules
    self.check_package(package, package_dir)
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/command/build_py.py", line 163, in check_package
    init_py = orig.build_py.check_package(self, package, package_dir)
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/distutils/command/build_py.py", line 191, in check_package
    "package directory '%s' does not exist" % package_dir)
distutils.errors.DistutilsFileError: package directory 'find_namespace:' does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/sandbox.py", line 158, in save_modules
    yield saved
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/sandbox.py", line 199, in setup_context
    yield
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/sandbox.py", line 254, in run_setup
    _execfile(setup_script, ns)
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/sandbox.py", line 49, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-fly4h8xs/pytest-runner-5.3.0/setup.py", line 21, in <module>
    def readme():
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/distutils/core.py", line 163, in setup
    raise SystemExit("error: " + str(msg))
SystemExit: error: package directory 'find_namespace:' does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1104, in run_setup
    run_setup(setup_script, args)
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/sandbox.py", line 257, in run_setup
    raise
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/sandbox.py", line 199, in setup_context
    yield
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/sandbox.py", line 170, in save_modules
    saved_exc.resume()
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/sandbox.py", line 145, in resume
    six.reraise(type, exc, self._tb)
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/site-packages/pkg_resources/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/sandbox.py", line 158, in save_modules
    yield saved
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/sandbox.py", line 199, in setup_context
    yield
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/sandbox.py", line 254, in run_setup
    _execfile(setup_script, ns)
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/sandbox.py", line 49, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-fly4h8xs/pytest-runner-5.3.0/setup.py", line 21, in <module>
    def readme():
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/distutils/core.py", line 163, in setup
    raise SystemExit("error: " + str(msg))
SystemExit: error: package directory 'find_namespace:' does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 214, in <module>
    zip_safe=False)
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/dist.py", line 335, in __init__
    self.fetch_build_eggs(attrs['setup_requires'])
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/dist.py", line 456, in fetch_build_eggs
    replace_conflicting=True,
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/site-packages/pkg_resources/__init__.py", line 863, in resolve
    replace_conflicting=replace_conflicting
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1141, in best_match
    return self.obtain(req, installer)
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1153, in obtain
    return installer(requirement)
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/dist.py", line 522, in fetch_build_egg
    return cmd.easy_install(req)
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 672, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 698, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 879, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1118, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/hwk/anaconda3/envs/alphapose/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1106, in run_setup
    raise DistutilsError("Setup script exited with %s" % (v.args[0],))
distutils.errors.DistutilsError: Setup script exited with error: package directory 'find_namespace:' does not exist

**Comment by qhdqhd** [comment]
ubuntu20.04 is same，can anyone help?

**Comment by JcJinChen** [comment]
check the version of the python-package setuptools, if <40.0 you can try upgrade setuptools >= 40.0

**Comment by qhdqhd** [comment]
how can I upgrade setuptools?can you please show me, thanks a lot.  @JcJinChen

**Comment by JcJinChen** [comment]
if you have installed pip，just run pip3 install setuptools==40.0.0 or  pip install setuptools==40.0.0 @qhdqhd

**Comment by qhdqhd** [comment]
Thank you my friend

**Comment by Fang-Haoshu** [comment]
Thanks. Add it to the requirements.
