### ISSUE TITLE
Infinite loop 

### ISSUE THREAD

**Issue by jangmingyu** [MVIG-SJTU/AlphaPose#855]
I'm currently running a video demo and it got stuck in an infinite loop. 

```
the video is 29.97 f/s
Loading YOLO model..
Loading pose model from joints_detectors/Alphapose/models/sppe/duc_se.pth
Start pose estimation...
  1%|█                                                                                  | 1/75 [00:00<00:55,  1.32it/s]Exception in thread Thread-4:
Traceback (most recent call last):
  File "E:\anaconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "E:\anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\video-to-pose3D-master\joints_detectors\Alphapose\dataloader.py", line 678, in update
    img = vis_frame(orig_img, result)
  File "C:\video-to-pose3D-master\joints_detectors\Alphapose\fn.py", line 198, in vis_frame
    img = cv2.addWeighted(bg, transparency, img, 1 - transparency, 0)
cv2.error: OpenCV(4.5.2) :-1: error: (-5:Bad argument) in function 'addWeighted'
> Overload resolution failed:
>  - Argument 'alpha' can not be treated as a double
>  - Argument 'alpha' can not be treated as a double

100%|██████████████████████████████████████████████████████████████████████████████████| 75/75 [00:05<00:00, 12.54it/s]
===========================> Rendering remaining images in the queue...
===========================> If this step takes too long, you can enable the --vis_fast flag to use fast rendering (real-time).
74
74
74
74
74
74
74
74
74
74
74
```

I need to render and save it as a video, but no help would be appreciated.

**Comment by Fang-Haoshu** [comment]
Hi, are you using the latest code? This bug was assumed to be fixed 9 months ago.
'transparency' and '1 - transparency' should be float.

Please update your code to the latest pytorch branch
