### ISSUE TITLE
Unable to use any tracker

### ISSUE THREAD

**Issue by kuba-wolf** [MVIG-SJTU/AlphaPose#861]
I'm trying to use a tracker on the google colab example, but I keep getting errors.
When I run this script: !python3 scripts/demo_inference.py --cfg configs/coco/resnet/256x192_res50_lr1e-3_1x.yaml --checkpoint pretrained_models/fast_res50_256x192.pth --video video.avi --outdir ../ --save_video --detector tracker
I get this error:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/content/AlphaPose/alphapose/utils/detector.py", line 223, in image_detection
    dets = self.detector.images_detection(imgs, im_dim_list)
  File "/content/AlphaPose/detector/tracker_api.py", line 100, in images_detection
    self.load_model()
  File "/content/AlphaPose/detector/tracker_api.py", line 56, in load_model
    self.model.load_state_dict(torch.load(self.model_weights, map_location='cpu')['model'], strict=False)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 381, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'detector/tracker/data/jde.1088x608.uncertainty.pt'

I noticed that the file is named /content/AlphaPose/detector/tracker/data/JDE-1088x608-uncertainty in the google colab file system, so I'm not sure if that makes a difference.

**Comment by BenjaminFraser** [comment]
Hello @kuba-wolf 

I know its been a long time since your issue was raised, but you could solve this by simply renaming the weights file in Colab to the name expected by the tracker_api.py file, like so:

!mv detector/tracker/data/JDE-1088x608-uncertainty detector/tracker/data/jde.1088x608.uncertainty.pt

You should then be able to run tracking as required. Hopefully that helps.
