### ISSUE TITLE
Error in `python2': corrupted size vs. prev_size: 0x0000000002981e70

### ISSUE THREAD

**Issue by kitlien** [MVIG-SJTU/AlphaPose#88]
I got this problem when I run './run.sh'. Could you please figure out what's the reason?

guest@ubuntu-PR6620GT2:~/perDen/AlphaPose_torch$ ./run.sh --indir examples/demo/ --outdir examples/results/ --vis
0
generating bbox from Faster RCNN...
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.22) or chardet (2.0.1) doesn't match a supported version!
  RequestsDependencyWarning)
2018-08-08 14:09:38.678871: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-08-08 14:09:38.909521: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:02:00.0
totalMemory: 10.90GiB freeMemory: 10.21GiB
2018-08-08 14:09:38.909579: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:02:00.0, compute capability: 6.1)
Loaded network ../output/res152/coco_2014_train+coco_2014_valminusminival/default/res152.ckpt
/home/guest/perDen/AlphaPose_torch/examples/demo/

100%|█████████████████████████████████████████████| 3/3 [00:03<00:00,  1.06s/it]
*** Error in `python2': corrupted size vs. prev_size: 0x0000000002981e70 ***
./run.sh: line 65: 11628 Aborted                 (core dumped) CUDA_VISIBLE_DEVICES=${GPU_ID} python2 demo-alpha-pose.py --inputlist=${LIST_FILE} --inputpath=${INPUT_PATH} --outputpath=${OUTPUT_PATH} --mode=${MODE}
pose estimation with RMPE...
/home/guest/torch/install/bin/lua: /home/guest/torch/install/share/lua/5.2/trepl/init.lua:389: /home/guest/torch/install/share/lua/5.2/hdf5/ffi.lua:56: expected align(#) on line 572
stack traceback:
	[C]: in function 'error'
	/home/guest/torch/install/share/lua/5.2/trepl/init.lua:389: in function 'require'
	/home/guest/perDen/AlphaPose_torch/predict/util.lua:7: in main chunk
	[C]: in function 'dofile'
	/home/guest/torch/install/share/lua/5.2/paths/init.lua:84: in function 'dofile'
	main-alpha-pose.lua:7: in main chunk
	[C]: in function 'dofile'
	...uest/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: in ?
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "parametric-pose-nms-MPII.py", line 256, in <module>
    get_result_json(args)
  File "parametric-pose-nms-MPII.py", line 243, in get_result_json
    test_parametric_pose_NMS_json(delta1, delta2, mu, gamma,args.outputpath)
  File "parametric-pose-nms-MPII.py", line 99, in test_parametric_pose_NMS_json
    h5file = h5py.File(os.path.join(outputpath,"POSE/test-pose.h5"), 'r')
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 271, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 101, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip_build_root/h5py/h5py/_objects.c:2840)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip_build_root/h5py/h5py/_objects.c:2798)
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open (/tmp/pip_build_root/h5py/h5py/h5f.c:2117)
IOError: Unable to open file (Unable to open file: name = '/home/guest/perden/alphapose_torch/examples/results/pose/test-pose.h5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)
visualization...
Traceback (most recent call last):
  File "json-video.py", line 63, in <module>
    with open(jsonpath) as f:
IOError: [Errno 2] No such file or directory: '/home/guest/perDen/AlphaPose_torch/examples/results/POSE/alpha-pose-results-forvis.json'

**Comment by Fang-Haoshu** [comment]
Seems a problem of the python2. Not sure what's the reason. How about the pytorch version?

**Comment by kitlien** [comment]
Thanks. I will try. Does the pytorch version has the implementation of 'PoseFlow'?

**Comment by Fang-Haoshu** [comment]
For 'PoseFlow', it's independent of the pose estimation step. So you can use the pytorch version to estimate the pose and then use the 'PoseFlow' in master branch to do pose tracking. We will also add that to pytorch version soon.
