### ISSUE TITLE
批量处理多个文件夹的问题

### ISSUE THREAD

**Issue by cyy-1102** [MVIG-SJTU/AlphaPose#903]
您好，我创建了一个.txt文件，里面存放着每个文件夹(文件夹里是该视频的图像帧)的路径，格式如下：
'/home/yy/桌面/img/235'
'/home/yy/桌面/img/1722'

当运行
python demo_inference
--cfg=/home/yy/AlphaPose/configs/coco/resnet/256x192_res152_lr1e-3_1x-duc.yaml
--checkpoint=/home/yy/AlphaPose/pretrained_models/fast_421_res152_256x192.pth
--list=/home/yy/桌面/123.txt
--outdir=/home/yy/桌面/examples
--pose_track

会出错：
Load SE Resnet...
Process Process-1:
Traceback (most recent call last):
File "/home/yy/anaconda3/envs/alphapose/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/home/yy/anaconda3/envs/alphapose/lib/python3.6/multiprocessing/process.py", line 93, in run
self._target(*self._args, **self._kwargs)
File "/home/yy/AlphaPose/alphapose/utils/detector.py", line 136, in image_preprocess
img_k = self.detector.image_preprocess(im_name_k)
File "/home/yy/AlphaPose/detector/yolo_api.py", line 69, in image_preprocess
img, orig_img, im_dim_list = prep_image(img_source, self.inp_dim)
File "/home/yy/AlphaPose/detector/yolo/preprocess.py", line 42, in prep_image
dim = orig_im.shape[1], orig_im.shape[0]
AttributeError: 'NoneType' object has no attribute 'shape'

谢谢您

**Comment by Fang-Haoshu** [comment]
list里为什么不加文件后缀呢

**Comment by cyy-1102** [comment]
> list里为什么不加文件后缀呢

您指的是什么意思呢?是.txt文件中的文件路径后缀吗
