### ISSUE TITLE
Error when installing 

### ISSUE THREAD

**Issue by saniazahan** [MVIG-SJTU/AlphaPose#910]
Machine: ubuntu 18.04.5

locale-gen C.UTF-8
Error: 'C.UTF-8' is not a supported language or locale

python setup.py build develop
Compiling detector/nms/src/soft_nms_cpu.pyx because it depends on .../linux/anaconda3/envs/alphapose/lib/python3.6/site-packages/Cython/Includes/cpython/buffer.pxd.
[1/1] Cythonizing detector/nms/src/soft_nms_cpu.pyx
Traceback (most recent call last):
  File "setup.py", line 211, in <module>
    ext_modules=get_ext_modules(),
  File "setup.py", line 134, in get_ext_modules
    sources=['src/nms_cpu.cpp']),
  File "setup.py", line 114, in make_cuda_ext
    '-D__CUDA_NO_HALF2_OPERATORS__',
  File ".../linux/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 868, in CUDAExtension
    library_dirs += library_paths(cuda=True)
  File "~/linux/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 976, in library_paths
    if (not os.path.exists(_join_cuda_home(lib_dir)) and
  File ".../linux/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1984, in _join_cuda_home
    raise EnvironmentError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

**Comment by Fang-Haoshu** [comment]
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

**Comment by saniazahan** [comment]
But where should I set it.

**Comment by 1702609** [comment]
I am getting the same problem. Have you fixed it?

**Comment by saniazahan** [comment]
I didn't. Ended up using openpose binary on my windows machine.
