### ISSUE TITLE
使用python3 setup.py build develop时报的错，求助大佬们！

### ISSUE THREAD

**Issue by huntlin** [MVIG-SJTU/AlphaPose#928]
Traceback (most recent call last):
  File "setup.py", line 213, in <module>
    zip_safe=False)
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 78, in run
    _build_ext.run(self)
  File "/home/hunt/.local/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/hunt/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 709, in build_extensions
    build_ext.build_extensions(self)
  File "/home/hunt/.local/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 199, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/usr/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/home/hunt/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 457, in unix_wrap_single_compile
    cflags = unix_cuda_flags(cflags)
  File "/home/hunt/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 424, in unix_cuda_flags
    cflags + _get_cuda_arch_flags(cflags))
  File "/home/hunt/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1562, in _get_cuda_arch_flags
    arch_list[-1] += '+PTX'
IndexError: list index out of range

**Comment by huntlin** [comment]
> Hi, it is related to cuda. I google it and find many answers. Perhaps you can try them: https://www.google.com/search?q=_get_cuda_arch_flags+arch_list%5B-1%5D+%2B%3D+%27%2BPTX%27+IndexError%3A+list+index+out+of+range&newwindow=1&ei=kT9kYcnIGfiB9u8PwpK4wAk&ved=0ahUKEwiJ1eLXvsLzAhX4gP0HHUIJDpgQ4dUDCA4&uact=5&oq=_get_cuda_arch_flags+arch_list%5B-1%5D+%2B%3D+%27%2BPTX%27+IndexError%3A+list+index+out+of+range&gs_lcp=Cgdnd3Mtd2l6EAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsANKBAhBGABQv4jtJ1i_iO0nYLyO7SdoA3ACeACAAQCIAQCSAQCYAQCgAQKgAQHIAQjAAQE&sclient=gws-wiz

感谢能给予答案，我这边检查了是我自身笔记本的显卡驱动有问题，在我export CUDA_HOME它识别不了cuda，所以我就重装了nvidia-driver和cuda，目前卡在的问题在于我用apt安装的nvidia-cuda-toolkit中，bin目录下并没有nvcc的可执行文件，所以打算直接从官网下载安装cuda再试试

**Comment by justsingular** [comment]
同学，你后来解决这个问题了吗，我也出现了这个问题，重新安装了cuda也没有解决。

**Comment by justsingular** [comment]
重新装个环境，换换torch版本可能就能解决




在2023年01月05日 18:53，mylittlebuds 写道：

我也是这个问题，请问怎么解决呀，谢谢。
