### ISSUE TITLE
'detector/nms/src/soft_nms_cpu.pyx' doesn't match any files

### ISSUE THREAD

**Issue by dekathomas** [MVIG-SJTU/AlphaPose#969]
Hello I tried to install the AlphaPose in Google Colab for training needs and I find this error.
```
Traceback (most recent call last):
  File "AlphaPose/setup.py", line 214, in <module>
    ext_modules=get_ext_modules(),
  File "AlphaPose/setup.py", line 133, in get_ext_modules
    sources=['src/soft_nms_cpu.pyx']),
  File "AlphaPose/setup.py", line 103, in make_cython_ext
    extension, = cythonize(extension)
  File "/usr/local/lib/python3.7/dist-packages/Cython/Build/Dependencies.py", line 972, in cythonize
    aliases=aliases)
  File "/usr/local/lib/python3.7/dist-packages/Cython/Build/Dependencies.py", line 815, in create_extension_list
    for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
  File "/usr/local/lib/python3.7/dist-packages/Cython/Build/Dependencies.py", line 114, in nonempty
    raise ValueError(error_msg)
ValueError: 'detector/nms/src/soft_nms_cpu.pyx' doesn't match any files
```
It happens when I run `!python3 AlphaPose/setup.py build develop --user`
Do you have any ideas about this? Thank you

**Comment by dekathomas** [comment]
Okay I have solved this problem of using colab (maybe it's a like unix system) you have to command `ext_modules=get_ext_modules()` in `setup.py`!
