### ISSUE TITLE
undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E

### ISSUE THREAD

**Issue by armornik** [MVIG-SJTU/AlphaPose#990]
CPU - only
Ubuntu 20.04.4 LTS

My actions:

Install Cuda: Cuda compilation tools, release 10.1, V10.1.243

conda create -n alphapose python=3.6 -y
conda activate alphapose

python -V
Python 3.6.13 :: Anaconda, Inc.

conda install pytorch==1.1.0 torchvision==0.3.0

git clone https://github.com/MVIG-SJTU/AlphaPose.git

**del line 211 in setup.py (ext_modules=get_ext_modules(),)**

export PATH=/usr/local/cuda/bin/:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda/lib64/:$LD_LIBRARY_PATH
python -m pip install cython
sudo apt-get install libyaml-dev
python setup.py build develop

run Alphapose:
python scripts/demo_inference.py --cfg configs/halpe_26/resnet/256x192_res50_lr1e-3_1x.yaml --checkpoint pretrained_models/halpe26_fast_res50_256x192.pth --indir examples/demo/ **--gpus -1**

But have error:
Traceback (most recent call last):
  File "scripts/demo_inference.py", line 19, in <module>
    from alphapose.utils.detector import DetectionLoader
  File "/home/snapper/Diagnosis/AlphaPose/alphapose/utils/detector.py", line 12, in <module>
    from alphapose.utils.presets import SimpleTransform
  File "/home/snapper/Diagnosis/AlphaPose/alphapose/utils/presets/__init__.py", line 1, in <module>
    from .simple_transform import SimpleTransform
  File "/home/snapper/Diagnosis/AlphaPose/alphapose/utils/presets/simple_transform.py", line 22, in <module>
    from ..roi_align import RoIAlign
  File "/home/snapper/Diagnosis/AlphaPose/alphapose/utils/roi_align/__init__.py", line 1, in <module>
    from .roi_align import roi_align, RoIAlign
  File "/home/snapper/Diagnosis/AlphaPose/alphapose/utils/roi_align/roi_align.py", line 6, in <module>
    from . import roi_align_cuda
ImportError: /home/snapper/Diagnosis/AlphaPose/alphapose/utils/roi_align/roi_align_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E

**Comment by armornik** [comment]
When: "python setup.py build develop"

No CUDA runtime is found, using CUDA_HOME='/usr'
running install

**Comment by anas-zafar** [comment]
@armornik were you able to solve this?
