### ISSUE TITLE
cannot import name 'roi_align_cuda'

### ISSUE THREAD

**Issue by creator-xi** [MVIG-SJTU/AlphaPose#995]
in ubuntu20.04.4LTS
i have followed with install.md and had no error
then i run "python scripts/demo_inference.py  --cfg" as the getting_started.md says
there is a import error:

Traceback (most recent call last):
  File "scripts/demo_inference.py", line 19, in <module>
    from alphapose.utils.detector import DetectionLoader
  File "/home/user811/xi/AlphaPose/scripts/alphapose/utils/detector.py", line 12, in <module>
    from alphapose.utils.presets import SimpleTransform
  File "/home/user811/xi/AlphaPose/scripts/alphapose/utils/presets/__init__.py", line 1, in <module>
    from .simple_transform import SimpleTransform
  File "/home/user811/xi/AlphaPose/scripts/alphapose/utils/presets/simple_transform.py", line 22, in <module>
    from ..roi_align import RoIAlign
  File "/home/user811/xi/AlphaPose/scripts/alphapose/utils/roi_align/__init__.py", line 1, in <module>
    from .roi_align import roi_align, RoIAlign
  File "/home/user811/xi/AlphaPose/scripts/alphapose/utils/roi_align/roi_align.py", line 6, in <module>
    from . import roi_align_cuda
ImportError: cannot import name 'roi_align_cuda'

**Comment by hmishra2250** [comment]
@creator-xi how did you solve this issue?
